$axure.loadCurrentPage({
  "url":"教材详情.html",
  "generationDate":new Date(1494572334167.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6656b4b6e85744edaf31cbf3aa9b76b2",
    "type":"Axure:Page",
    "name":"教材详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b6f44bebb5364802b4660bd66b8a965f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":230},
            "size":{
              "width":268,
              "height":240},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd4c60fed45048ba95b39441b9832943",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":230},
                "size":{
                  "width":268,
                  "height":240},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材详情/u0.png"}},
{
          "id":"afb42c49e9c04a3a888eec569c23ccaa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":1420},
            "size":{
              "width":964,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1125980a273546c5884b413fe597f435",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":1420},
                "size":{
                  "width":964,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/备课/u131.png"}},
{
          "id":"4655d6502534426caf5e347853296246",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF336666,
              "opacity":1},
            "location":{
              "x":78,
              "y":1433},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61309e8869ff43ef8edbe1fe4ffc2179",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF336666,
                  "opacity":1},
                "location":{
                  "x":78,
                  "y":1433},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ab720701f224b29a4784e1da695de44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":1210,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed41b5b5d220407e974da48ac2789888",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":1210,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材购买/u8.png"}},
{
          "id":"4e00a2d0b149406390a9a8087f14a50e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":50},
            "size":{
              "width":53,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b6c6d2b0a79438fab3f59d4e9a86ab0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":50},
                "size":{
                  "width":53,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ad59e2adf40489da6b8091f333a0743",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":100,
              "y":70},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1319ccf7b18497b8710054c9c99398d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":70},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36127b0e3944484a9ed13bfcd7ea7f23",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":57},
            "size":{
              "width":340,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1d1636341764683b077186fb0bdea36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":57},
                "size":{
                  "width":340,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材购买/u14.png"}},
{
          "id":"2dec983b60f94f14bbf4bf9f74837081",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3333},
            "location":{
              "x":720,
              "y":57},
            "size":{
              "width":72,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8137df86ec644bba47fa93ee1b92f38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3333},
                "location":{
                  "x":720,
                  "y":57},
                "size":{
                  "width":72,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材购买/u16.png"}},
{
          "id":"150e343f2a9b468bb0a4121527468c8a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":386,
              "y":59},
            "size":{
              "width":319,
              "height":30}},
          "adaptiveStyles":{
},
          "placeholderText":"金八力作文"},
{
          "id":"77de7845d185448aa497125daa71573e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":1210,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9f4cfed196a4f14bf45758860c5e7ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":1210,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材购买/u19.png"}},
{
          "id":"4acf71cf81764165953d50ff3f15182a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":16,
              "y":7},
            "size":{
              "width":113,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10261823a35441128c8addc1e1f359f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":7},
                "size":{
                  "width":113,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da2fb157afa448d8bd6e47e4d186dad3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":1020,
              "y":7},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4af4f221bdc48d59b12b25c67518ae6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":1020,
                  "y":7},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc16ce83c82f46b69715577d304d75c3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":170},
            "size":{
              "width":1210,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3366}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/教材购买/u25_line.png"}},
{
          "id":"be54bda437e74d649c674a34da0a0386",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":65,
              "y":144},
            "size":{
              "width":224,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddd4c790785e448ca0078c0c21c1f61c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":65,
                  "y":144},
                "size":{
                  "width":224,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材购买/u26.png"}},
{
          "id":"2aa2d1912ab444c19950b127606374b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":327,
              "y":148},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2b0516de62c4f06b6c2fe5b275dac5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":327,
                  "y":148},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 教材购买",
                      "target":{
                        "targetType":"page",
                        "url":"教材购买.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"45012053906b421fa647bd9d7f370cc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":420,
              "y":148},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c57a27526f645e6991605f2c305effd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":420,
                  "y":148},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 教材赛选",
                      "target":{
                        "targetType":"page",
                        "url":"教材赛选.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"3517c3cb30cf47a3953b691d46787cc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":505,
              "y":148},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f29075f0d7e4d2981b6ca202adf85e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":505,
                  "y":148},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 教具",
                      "target":{
                        "targetType":"page",
                        "url":"教具.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"cfbe3374fb974777bb2a7174c6d73edc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":580,
              "y":148},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09b71cc45fef4c93bad75c4508f7945b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":580,
                  "y":148},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 物料",
                      "target":{
                        "targetType":"page",
                        "url":"物料.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"4b93adb994af4de28ef1a4dd105ca83d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":62,
              "y":187},
            "size":{
              "width":233,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fce7eb51e9b44719780bb2eae227a29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":62,
                  "y":187},
                "size":{
                  "width":233,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05f09149538d4527a92e30a1f4d25629",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1270,
              "y":200},
            "size":{
              "width":196,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e15aca7c770842caa72674e74d9de482",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1270,
                  "y":200},
                "size":{
                  "width":196,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d8e77ce440d4a52ab68433e8a90a201",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1270,
              "y":258},
            "size":{
              "width":105,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00955993559342c9b203c4b3ef42dfcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1270,
                  "y":258},
                "size":{
                  "width":105,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0bfa005275cc4f0aaf73bbc8e78d3c01",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":244},
            "size":{
              "width":198,
              "height":196},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5788b0593e5c4d7f9c4f6ebde1310b65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":244},
                "size":{
                  "width":198,
                  "height":196},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材购买/u40.png"}},
{
          "id":"593ed97855964179af11f984b4c64162",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0033,
              "opacity":1},
            "location":{
              "x":399,
              "y":303},
            "size":{
              "width":71,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcc1e2fd253f49f2b43035203961a295",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033,
                  "opacity":1},
                "location":{
                  "x":399,
                  "y":303},
                "size":{
                  "width":71,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"534525d185504016ab608895b23c78b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":397,
              "y":395},
            "size":{
              "width":75,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a520d0a8b34f4093aa01a65c2740a687",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":397,
                  "y":395},
                "size":{
                  "width":75,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61a546f33caa4cccaecbf501f701f16f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":402,
              "y":253},
            "size":{
              "width":113,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2169727428fb4bbca115ee8fb34c589c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":402,
                  "y":253},
                "size":{
                  "width":113,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"469bbadbdba84a8d95589a9d2832a05e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":399,
              "y":351},
            "size":{
              "width":209,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e8f30ff4563411bb19f25d5e4399f6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":399,
                  "y":351},
                "size":{
                  "width":209,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01a15714437542fb85ae8822a06a84c7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":89,
              "y":539},
            "size":{
              "width":781,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/教材详情/u50_line.png"}},
{
          "id":"ef9900ff23494f1ca63ab720f0248884",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":89,
              "y":513},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b59c69f33d7403e80ba6c7ffd51a1ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":89,
                  "y":513},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17c86a09c7594fa591d505a8522a5769",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":89,
              "y":570},
            "size":{
              "width":781,
              "height":410},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc14a0cea214495f8b8f130b1da86583",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":89,
                  "y":570},
                "size":{
                  "width":781,
                  "height":410},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材详情/u53.png"}},
{
          "id":"0e0539ad7fcd43d5a1df7e55fd3e67ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":89,
              "y":990},
            "size":{
              "width":781,
              "height":410},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0e8a8d4d99644b88805e913cea4c586",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":89,
                  "y":990},
                "size":{
                  "width":781,
                  "height":410},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材详情/u53.png"}},
{
          "id":"5c4c721c6cb34b8aa3ec915bf9d88e11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366}}},
            "location":{
              "x":399,
              "y":439},
            "size":{
              "width":91,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbd5ecf596024641b03361b7c729f61c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366}}},
                "location":{
                  "x":399,
                  "y":439},
                "size":{
                  "width":91,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 立即购买订单",
                      "target":{
                        "targetType":"page",
                        "url":"立即购买订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/教材详情/u57.png",
            "mouseOver~":"images/教材详情/u57_mouseOver.png"}},
{
          "id":"82d54b93f3824005aa02a0e3802de07d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366}}},
            "location":{
              "x":517,
              "y":439},
            "size":{
              "width":91,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f276b6d5ea74b07b3bdd1de06315e02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366}}},
                "location":{
                  "x":517,
                  "y":439},
                "size":{
                  "width":91,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 shoop",
                      "objectsToFades":[{
                          "objectPath":["e4b1357f73af4d779f5d0fa6334d9ebc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"wait",
                      "description":"等待3000毫秒",
                      "waitTime":3000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 shoop",
                      "objectsToFades":[{
                          "objectPath":["e4b1357f73af4d779f5d0fa6334d9ebc"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/教材详情/u57.png",
            "mouseOver~":"images/教材详情/u57_mouseOver.png"}},
{
          "id":"e4b1357f73af4d779f5d0fa6334d9ebc",
          "label":"shoop",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":310,
              "y":273},
            "size":{
              "width":320,
              "height":75},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e5115efab854f22b8c5a91edfbe72ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":310,
                  "y":273},
                "size":{
                  "width":320,
                  "height":75},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材购买/shoop_u292.png"}},
{
          "id":"c82db060c0b24c60bec4fe34eb7b6e61",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":991,
              "y":46},
            "size":{
              "width":94,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69fa836c1344488d95690994d9fef368",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":991,
                  "y":46},
                "size":{
                  "width":94,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 购物车",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/教材购买/u294.png"}},
{
          "id":"832ccb5e947c41aa96fdcfbf77883466",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":991,
              "y":86},
            "size":{
              "width":94,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6eb90dee28b4b1583ecf4dd2d7ecd41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":991,
                  "y":86},
                "size":{
                  "width":94,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/教材购买/u294.png"}},
{
          "id":"9f067dda76e3456a915d1365119dc876",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":984,
              "y":40},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a79fdc3836354f9490d0a52392a23af6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":984,
                  "y":40},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材购买/u298.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b6f44bebb5364802b4660bd66b8a965f":{
      "scriptId":"u0"},
    "bd4c60fed45048ba95b39441b9832943":{
      "scriptId":"u1"},
    "afb42c49e9c04a3a888eec569c23ccaa":{
      "scriptId":"u2"},
    "1125980a273546c5884b413fe597f435":{
      "scriptId":"u3"},
    "4655d6502534426caf5e347853296246":{
      "scriptId":"u4"},
    "61309e8869ff43ef8edbe1fe4ffc2179":{
      "scriptId":"u5"},
    "9ab720701f224b29a4784e1da695de44":{
      "scriptId":"u6"},
    "ed41b5b5d220407e974da48ac2789888":{
      "scriptId":"u7"},
    "4e00a2d0b149406390a9a8087f14a50e":{
      "scriptId":"u8"},
    "4b6c6d2b0a79438fab3f59d4e9a86ab0":{
      "scriptId":"u9"},
    "2ad59e2adf40489da6b8091f333a0743":{
      "scriptId":"u10"},
    "d1319ccf7b18497b8710054c9c99398d":{
      "scriptId":"u11"},
    "36127b0e3944484a9ed13bfcd7ea7f23":{
      "scriptId":"u12"},
    "e1d1636341764683b077186fb0bdea36":{
      "scriptId":"u13"},
    "2dec983b60f94f14bbf4bf9f74837081":{
      "scriptId":"u14"},
    "a8137df86ec644bba47fa93ee1b92f38":{
      "scriptId":"u15"},
    "150e343f2a9b468bb0a4121527468c8a":{
      "scriptId":"u16"},
    "77de7845d185448aa497125daa71573e":{
      "scriptId":"u17"},
    "d9f4cfed196a4f14bf45758860c5e7ef":{
      "scriptId":"u18"},
    "4acf71cf81764165953d50ff3f15182a":{
      "scriptId":"u19"},
    "10261823a35441128c8addc1e1f359f0":{
      "scriptId":"u20"},
    "da2fb157afa448d8bd6e47e4d186dad3":{
      "scriptId":"u21"},
    "a4af4f221bdc48d59b12b25c67518ae6":{
      "scriptId":"u22"},
    "cc16ce83c82f46b69715577d304d75c3":{
      "scriptId":"u23"},
    "be54bda437e74d649c674a34da0a0386":{
      "scriptId":"u24"},
    "ddd4c790785e448ca0078c0c21c1f61c":{
      "scriptId":"u25"},
    "2aa2d1912ab444c19950b127606374b7":{
      "scriptId":"u26"},
    "a2b0516de62c4f06b6c2fe5b275dac5e":{
      "scriptId":"u27"},
    "45012053906b421fa647bd9d7f370cc1":{
      "scriptId":"u28"},
    "1c57a27526f645e6991605f2c305effd":{
      "scriptId":"u29"},
    "3517c3cb30cf47a3953b691d46787cc4":{
      "scriptId":"u30"},
    "1f29075f0d7e4d2981b6ca202adf85e5":{
      "scriptId":"u31"},
    "cfbe3374fb974777bb2a7174c6d73edc":{
      "scriptId":"u32"},
    "09b71cc45fef4c93bad75c4508f7945b":{
      "scriptId":"u33"},
    "4b93adb994af4de28ef1a4dd105ca83d":{
      "scriptId":"u34"},
    "7fce7eb51e9b44719780bb2eae227a29":{
      "scriptId":"u35"},
    "05f09149538d4527a92e30a1f4d25629":{
      "scriptId":"u36"},
    "e15aca7c770842caa72674e74d9de482":{
      "scriptId":"u37"},
    "9d8e77ce440d4a52ab68433e8a90a201":{
      "scriptId":"u38"},
    "00955993559342c9b203c4b3ef42dfcd":{
      "scriptId":"u39"},
    "0bfa005275cc4f0aaf73bbc8e78d3c01":{
      "scriptId":"u40"},
    "5788b0593e5c4d7f9c4f6ebde1310b65":{
      "scriptId":"u41"},
    "593ed97855964179af11f984b4c64162":{
      "scriptId":"u42"},
    "dcc1e2fd253f49f2b43035203961a295":{
      "scriptId":"u43"},
    "534525d185504016ab608895b23c78b6":{
      "scriptId":"u44"},
    "a520d0a8b34f4093aa01a65c2740a687":{
      "scriptId":"u45"},
    "61a546f33caa4cccaecbf501f701f16f":{
      "scriptId":"u46"},
    "2169727428fb4bbca115ee8fb34c589c":{
      "scriptId":"u47"},
    "469bbadbdba84a8d95589a9d2832a05e":{
      "scriptId":"u48"},
    "4e8f30ff4563411bb19f25d5e4399f6c":{
      "scriptId":"u49"},
    "01a15714437542fb85ae8822a06a84c7":{
      "scriptId":"u50"},
    "ef9900ff23494f1ca63ab720f0248884":{
      "scriptId":"u51"},
    "1b59c69f33d7403e80ba6c7ffd51a1ef":{
      "scriptId":"u52"},
    "17c86a09c7594fa591d505a8522a5769":{
      "scriptId":"u53"},
    "fc14a0cea214495f8b8f130b1da86583":{
      "scriptId":"u54"},
    "0e0539ad7fcd43d5a1df7e55fd3e67ed":{
      "scriptId":"u55"},
    "b0e8a8d4d99644b88805e913cea4c586":{
      "scriptId":"u56"},
    "5c4c721c6cb34b8aa3ec915bf9d88e11":{
      "scriptId":"u57"},
    "dbd5ecf596024641b03361b7c729f61c":{
      "scriptId":"u58"},
    "82d54b93f3824005aa02a0e3802de07d":{
      "scriptId":"u59"},
    "9f276b6d5ea74b07b3bdd1de06315e02":{
      "scriptId":"u60"},
    "e4b1357f73af4d779f5d0fa6334d9ebc":{
      "scriptId":"u61"},
    "4e5115efab854f22b8c5a91edfbe72ad":{
      "scriptId":"u62"},
    "c82db060c0b24c60bec4fe34eb7b6e61":{
      "scriptId":"u63"},
    "69fa836c1344488d95690994d9fef368":{
      "scriptId":"u64"},
    "832ccb5e947c41aa96fdcfbf77883466":{
      "scriptId":"u65"},
    "a6eb90dee28b4b1583ecf4dd2d7ecd41":{
      "scriptId":"u66"},
    "9f067dda76e3456a915d1365119dc876":{
      "scriptId":"u67"},
    "a79fdc3836354f9490d0a52392a23af6":{
      "scriptId":"u68"}}});