$axure.loadCurrentPage({
  "url":"测评.html",
  "generationDate":new Date(1494572344381.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0e43409351dc4efb9cd4e4ba58cb3466",
    "type":"Axure:Page",
    "name":"测评",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7fc7b00b936a4d5fb10fdb4f4f88c7f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":950,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d43f3021af564079925e862d701fcd36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":950,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/备课/u2.png"}},
{
          "id":"8f08a024e089451a87934f0a760247ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":9},
            "size":{
              "width":68,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d995a805fd3b4f3fa8f2e9c666b41808",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":9},
                "size":{
                  "width":68,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa67a45c28e4470aa6dc018447612c51",
          "label":"beike",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":119,
              "y":14},
            "size":{
              "width":80,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29465cb1f40347dab1d0b41d439b501f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":119,
                  "y":14},
                "size":{
                  "width":80,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 beike = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["fa67a45c28e4470aa6dc018447612c51"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 beike = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["fa67a45c28e4470aa6dc018447612c51"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/备课/beike_u6.png",
            "selected~":"images/备课/beike_u6_selected.png"}},
{
          "id":"0043ab2cf372492fb3f617d9943874af",
          "label":"souke",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":208,
              "y":14},
            "size":{
              "width":65,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"064670eaebc9420b8182c57769adc843",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":208,
                  "y":14},
                "size":{
                  "width":65,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 souke = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["0043ab2cf372492fb3f617d9943874af"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 souke = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["0043ab2cf372492fb3f617d9943874af"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/备课/souke_u8.png",
            "selected~":"images/备课/souke_u8_selected.png"}},
{
          "id":"a8f7c05ea25d48b99561ed105331bd51",
          "label":"guanli",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":282,
              "y":14},
            "size":{
              "width":70,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ae5901bc2544b51b5d7f654707cbcbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":282,
                  "y":14},
                "size":{
                  "width":70,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 guanli = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a8f7c05ea25d48b99561ed105331bd51"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 guanli = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a8f7c05ea25d48b99561ed105331bd51"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/校内管理/guanli_u13.png",
            "selected~":"images/校内管理/guanli_u13_selected.png"}},
{
          "id":"ba13b7d4b728432abade0dd36af1a934",
          "label":"ceping",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":362,
              "y":14},
            "size":{
              "width":51,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2bc1374ced1454c92aeae84601e7118",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":362,
                  "y":14},
                "size":{
                  "width":51,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 ceping = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["ba13b7d4b728432abade0dd36af1a934"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 ceping = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["ba13b7d4b728432abade0dd36af1a934"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/备课/ceping_u12.png",
            "selected~":"images/备课/ceping_u12_selected.png"}},
{
          "id":"a7e425e29bee4f7fbe39e2eeaa3561e6",
          "label":"peixun",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":423,
              "y":14},
            "size":{
              "width":58,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"702f4b4d0acb4c6baed6552e32a93d73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":423,
                  "y":14},
                "size":{
                  "width":58,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a7e425e29bee4f7fbe39e2eeaa3561e6"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a7e425e29bee4f7fbe39e2eeaa3561e6"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/备课/peixun_u14.png",
            "selected~":"images/备课/peixun_u14_selected.png"}},
{
          "id":"9753f21a5d6a43348ab54aef717cec7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":14},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a81296e6018d42f0877ab933617d2197",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":850,
                  "y":14},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 user 弹出效果",
                      "objectsToFades":[{
                          "objectPath":["824c144a0f994745b53176ade441db42"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"flyout"}}}]}]}]}},
          "images":{
            "normal~":"images/备课/u16.png"}},
{
          "id":"547622a47fe044ae9876038504130c3c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":723},
            "size":{
              "width":964,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"736dfd85336844229880bad3f5da1954",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":723},
                "size":{
                  "width":964,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/备课/u131.png"}},
{
          "id":"378fe36319284f3bb466efd2a51ac07a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF336666,
              "opacity":1},
            "location":{
              "x":38,
              "y":736},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30fe606a1b1d4a91a4f0925837939b79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF336666,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":736},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6512967dddb4b058079973e27dbf446",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":39},
            "size":{
              "width":79,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF33CCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/校内管理/u27_line.png"}},
{
          "id":"60dbc29dce3a480e9004ed0e7cf8b470",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":678,
              "y":9},
            "size":{
              "width":79,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a5f1f42204f4f86a4eb125cb08916db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":678,
                  "y":9},
                "size":{
                  "width":79,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23b175dcdcb6493c92adc4c83acfa56c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":13,
              "y":106},
            "size":{
              "width":920,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72fa9ff898ae4a3ebe9e53435619f8c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":13,
                  "y":106},
                "size":{
                  "width":920,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u23.png"}},
{
          "id":"efd9176e7d4e4dafba1dda9a1686f463",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "location":{
              "x":37,
              "y":123},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab63068177f44d04999234af6f8a9766",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "location":{
                  "x":37,
                  "y":123},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16777a604ff940b2a175c6f21fd3ecb2",
          "label":"ggxiaotu",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":55},
            "size":{
              "width":950,
              "height":50}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"885802a9c65d4b638469f5212d57304e",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f830c5ecaf28429190b8ce504a382a13",
                  "label":"",
                  "parentDynamicPanel":"16777a604ff940b2a175c6f21fd3ecb2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF66CCFF,
                      "opacity":1},
                    "size":{
                      "width":950,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6ae0f2a8eef74c3bb30d32bbd4f028ee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"16777a604ff940b2a175c6f21fd3ecb2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF66CCFF,
                          "opacity":1},
                        "size":{
                          "width":950,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/测评/u28.png"}},
{
                  "id":"d01c7491e415411383de2d49cb429cc6",
                  "label":"kongzhiqi",
                  "parentDynamicPanel":"16777a604ff940b2a175c6f21fd3ecb2",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":884,
                      "y":0},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"24ff17ad40d2448f892d2c29941a7df9",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"99a0dd0951054427b179822e8b195e79",
                          "label":"",
                          "parentDynamicPanel":"d01c7491e415411383de2d49cb429cc6",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":66,
                              "height":30}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"ee837d821a654e27bf3531ec5a9c40c0",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"d01c7491e415411383de2d49cb429cc6",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":66,
                                  "height":30}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/校内管理/u32.png"}}]}]}]}]},
{
          "id":"824c144a0f994745b53176ade441db42",
          "label":"user",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":850,
              "y":44},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"cb6e4784d5bb4e9883d2406246904a00",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2db2094e863f44c7baebf86b4d8966c6",
                  "label":"",
                  "parentDynamicPanel":"824c144a0f994745b53176ade441db42",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFA1A1A1,
                      "opacity":1},
                    "size":{
                      "width":90,
                      "height":27},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF3399}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"09dea76125ba49eb9f08a57c7b783c57",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"824c144a0f994745b53176ade441db42",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFA1A1A1,
                          "opacity":1},
                        "size":{
                          "width":90,
                          "height":27},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF3399}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/备课/u53.png"}},
{
                  "id":"aa54b43c83e0426790c23beb99a78a0b",
                  "label":"",
                  "parentDynamicPanel":"824c144a0f994745b53176ade441db42",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFA1A1A1,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":26},
                    "size":{
                      "width":90,
                      "height":27},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF3399}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd338cd956954442b15cabbf925364ba",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"824c144a0f994745b53176ade441db42",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFA1A1A1,
                          "opacity":1},
                        "location":{
                          "x":0,
                          "y":26},
                        "size":{
                          "width":90,
                          "height":27},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF3399}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/备课/u53.png"}}]}]},
{
          "id":"cf2bfd6483164296a09db241d7991785",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":13,
              "y":172},
            "size":{
              "width":920,
              "height":108},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecb5827d22eb45bba4908ebf940e2733",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":13,
                  "y":172},
                "size":{
                  "width":920,
                  "height":108},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u38.png"}},
{
          "id":"70df6528f4b14d8db43fae45717019df",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":210},
            "size":{
              "width":890,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/测评/u40_line.png"}},
{
          "id":"34c0810dc43e41fdbde9f3ab76d0aedc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":25,
              "y":182},
            "size":{
              "width":93,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c65e5bc1dd4c4e468c22383773a8c16d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":25,
                  "y":182},
                "size":{
                  "width":93,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u41.png"}},
{
          "id":"d74f4fd9f0d740829bf4fd78e2b3b08b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":210},
            "size":{
              "width":93,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF33CCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/测评/u43_line.png"}},
{
          "id":"ccb99020b71d4c7081bc475df78e1085",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":118,
              "y":182},
            "size":{
              "width":93,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0db894e0c3fc431fa0733b270afa4e5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":118,
                  "y":182},
                "size":{
                  "width":93,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测评报告",
                      "target":{
                        "targetType":"page",
                        "url":"测评报告.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/测评/u41.png"}},
{
          "id":"523d730b069646af8c49124eeb82fa3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":790,
              "y":182},
            "size":{
              "width":110,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1974b245ac87454e964f025e3d092de4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":790,
                  "y":182},
                "size":{
                  "width":110,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u46.png"}},
{
          "id":"c80719855463454e8b823ed49382fb68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":21,
              "y":222},
            "size":{
              "width":78,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33017a5f5bbd4948bd3417f7d8402ff7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF33CCCC,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":21,
                  "y":222},
                "size":{
                  "width":78,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u48.png",
            "mouseOver~":"images/测评/u48.png"}},
{
          "id":"e87fb2a0e3c948baa05cdae1807bee85",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":99,
              "y":222},
            "size":{
              "width":78,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a5db0279edb4b938bbda7d0a9d11142",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF33CCCC,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":99,
                  "y":222},
                "size":{
                  "width":78,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u48.png",
            "mouseOver~":"images/测评/u48.png"}},
{
          "id":"2ae58d385e914ecf91bf897bceb9aa36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":177,
              "y":222},
            "size":{
              "width":78,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"516d2a1b8e0e4d189c7378327fd3659b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF33CCCC,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":177,
                  "y":222},
                "size":{
                  "width":78,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u48.png",
            "mouseOver~":"images/测评/u48.png"}},
{
          "id":"6f384d8d51fc4a05af793ca6bddc71f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":255,
              "y":222},
            "size":{
              "width":78,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8eb807c144e48ea870c768366833245",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF33CCCC,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":255,
                  "y":222},
                "size":{
                  "width":78,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u48.png",
            "mouseOver~":"images/测评/u48.png"}},
{
          "id":"05d6dc7dd30f4ce0a5aeaa3ee007e3b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":333,
              "y":222},
            "size":{
              "width":78,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cad54847ddd4082887d97856f12ad1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF33CCCC,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":333,
                  "y":222},
                "size":{
                  "width":78,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u48.png",
            "mouseOver~":"images/测评/u48.png"}},
{
          "id":"7e968cd1cbdb4ecea3975df4e5e2fe38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":411,
              "y":222},
            "size":{
              "width":78,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eba18dfb9b1b4acb9dbf77235aab79b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF33CCCC,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":411,
                  "y":222},
                "size":{
                  "width":78,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u48.png",
            "mouseOver~":"images/测评/u48.png"}},
{
          "id":"4fd999d88c4147e4ba0fe6b09d311a67",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":489,
              "y":222},
            "size":{
              "width":78,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"275dfaac00bf4a28b78e845ad1692984",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF33CCCC,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":489,
                  "y":222},
                "size":{
                  "width":78,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u48.png",
            "mouseOver~":"images/测评/u48.png"}},
{
          "id":"60e028626df64553a35002887fe08024",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":567,
              "y":222},
            "size":{
              "width":78,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1cdb3651ff84292b59d300c9fc324a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF33CCCC,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":567,
                  "y":222},
                "size":{
                  "width":78,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u48.png",
            "mouseOver~":"images/测评/u48.png"}},
{
          "id":"aeab452ee10142c7aea210f435179ec5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":13,
              "y":314},
            "size":{
              "width":920,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb9f7c8efd754eab90215cb7df7d0f2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":13,
                  "y":314},
                "size":{
                  "width":920,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测评试卷详情",
                      "target":{
                        "targetType":"page",
                        "url":"测评试卷详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/测评/u64.png",
            "mouseOver~":"images/测评/u23.png"}},
{
          "id":"a9021c290ecb4dc7851a3eb5f2fd7a27",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "location":{
              "x":19,
              "y":290},
            "size":{
              "width":91,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89ae259e33dd4c86ab64b0876cabe11d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":290},
                "size":{
                  "width":91,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ddaa671a94149aca680cf2f7c32e58b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":819,
              "y":322},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"31"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50fc6fc5b1774382b1c72181e427cda1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":819,
                  "y":322},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"31"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u68.png"}},
{
          "id":"2b892dadf79d4600ac4f38c866c3cd2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":322},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"32"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09bdf3081d224430b1f403d6c709aa70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":322},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"32"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u70.png"}},
{
          "id":"378580bf581a4ad4ba668b70d44fdc0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":13,
              "y":369},
            "size":{
              "width":920,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"429ba7d9e1df4abb8ee8079016e1692c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":13,
                  "y":369},
                "size":{
                  "width":920,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测评试卷详情",
                      "target":{
                        "targetType":"page",
                        "url":"测评试卷详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/测评/u64.png",
            "mouseOver~":"images/测评/u23.png"}},
{
          "id":"0684d15273164ddfb54f6cf17eefd045",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":819,
              "y":377},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"31"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3524fea7b3d54dcb9bd694f412049d0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":819,
                  "y":377},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"31"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u68.png"}},
{
          "id":"d6dccf718251474bb9803c4d545c9b62",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":377},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"32"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"220bf3705cda45dc83a777ae18a232f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":377},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"32"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u70.png"}},
{
          "id":"9d51bdc430744577b3a246a2977d7169",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":13,
              "y":424},
            "size":{
              "width":920,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3aa26ce3b721469cbd98371da2d59d25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":13,
                  "y":424},
                "size":{
                  "width":920,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测评试卷详情",
                      "target":{
                        "targetType":"page",
                        "url":"测评试卷详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/测评/u64.png",
            "mouseOver~":"images/测评/u23.png"}},
{
          "id":"b693525ba4724335828b72f3019e059f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":819,
              "y":432},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"31"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a77070f2fc5342bc8bbeedaa1013e197",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":819,
                  "y":432},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"31"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u68.png"}},
{
          "id":"53e320f88940440c9d899171ec4cb923",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":432},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"32"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9177bbb306a84281a34230848e18f649",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":432},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"32"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u70.png"}},
{
          "id":"21fd193e03014938bfd8c226e8917d5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":13,
              "y":479},
            "size":{
              "width":920,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56511f8e60744eb2b9d327f9d30e1c12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":13,
                  "y":479},
                "size":{
                  "width":920,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测评试卷详情",
                      "target":{
                        "targetType":"page",
                        "url":"测评试卷详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/测评/u64.png",
            "mouseOver~":"images/测评/u23.png"}},
{
          "id":"54eeaa66846e4588935250ed6f794f50",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":819,
              "y":487},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"31"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c764e96d96d64a758257ba5e83865560",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":819,
                  "y":487},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"31"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u68.png"}},
{
          "id":"6718546662194350afe20a7d2ac519c2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":487},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"32"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99b1e4ac927f4c11af13dc47a29acb19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":487},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"32"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u70.png"}},
{
          "id":"72704bf306894d5988935037762ada67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":578,
              "y":574},
            "size":{
              "width":103,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7269ed2a70d43a5a254cfdc27e0c8f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":578,
                  "y":574},
                "size":{
                  "width":103,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8449a2d4398943359f802f6c2dad40d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":138,
              "y":123},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aa39cd727d34b359706a7aa2920a987",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":123},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 考试测评",
                      "target":{
                        "targetType":"page",
                        "url":"考试测评.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfda0caaf21e4470b780359183e16f84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":236,
              "y":123},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e352505ee6c341daa66518f49bd0082e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":236,
                  "y":123},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 老师测评",
                      "target":{
                        "targetType":"page",
                        "url":"老师测评.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7fc7b00b936a4d5fb10fdb4f4f88c7f8":{
      "scriptId":"u0"},
    "d43f3021af564079925e862d701fcd36":{
      "scriptId":"u1"},
    "8f08a024e089451a87934f0a760247ee":{
      "scriptId":"u2"},
    "d995a805fd3b4f3fa8f2e9c666b41808":{
      "scriptId":"u3"},
    "fa67a45c28e4470aa6dc018447612c51":{
      "scriptId":"u4"},
    "29465cb1f40347dab1d0b41d439b501f":{
      "scriptId":"u5"},
    "0043ab2cf372492fb3f617d9943874af":{
      "scriptId":"u6"},
    "064670eaebc9420b8182c57769adc843":{
      "scriptId":"u7"},
    "a8f7c05ea25d48b99561ed105331bd51":{
      "scriptId":"u8"},
    "9ae5901bc2544b51b5d7f654707cbcbc":{
      "scriptId":"u9"},
    "ba13b7d4b728432abade0dd36af1a934":{
      "scriptId":"u10"},
    "f2bc1374ced1454c92aeae84601e7118":{
      "scriptId":"u11"},
    "a7e425e29bee4f7fbe39e2eeaa3561e6":{
      "scriptId":"u12"},
    "702f4b4d0acb4c6baed6552e32a93d73":{
      "scriptId":"u13"},
    "9753f21a5d6a43348ab54aef717cec7e":{
      "scriptId":"u14"},
    "a81296e6018d42f0877ab933617d2197":{
      "scriptId":"u15"},
    "547622a47fe044ae9876038504130c3c":{
      "scriptId":"u16"},
    "736dfd85336844229880bad3f5da1954":{
      "scriptId":"u17"},
    "378fe36319284f3bb466efd2a51ac07a":{
      "scriptId":"u18"},
    "30fe606a1b1d4a91a4f0925837939b79":{
      "scriptId":"u19"},
    "c6512967dddb4b058079973e27dbf446":{
      "scriptId":"u20"},
    "60dbc29dce3a480e9004ed0e7cf8b470":{
      "scriptId":"u21"},
    "4a5f1f42204f4f86a4eb125cb08916db":{
      "scriptId":"u22"},
    "23b175dcdcb6493c92adc4c83acfa56c":{
      "scriptId":"u23"},
    "72fa9ff898ae4a3ebe9e53435619f8c6":{
      "scriptId":"u24"},
    "efd9176e7d4e4dafba1dda9a1686f463":{
      "scriptId":"u25"},
    "ab63068177f44d04999234af6f8a9766":{
      "scriptId":"u26"},
    "16777a604ff940b2a175c6f21fd3ecb2":{
      "scriptId":"u27"},
    "f830c5ecaf28429190b8ce504a382a13":{
      "scriptId":"u28"},
    "6ae0f2a8eef74c3bb30d32bbd4f028ee":{
      "scriptId":"u29"},
    "d01c7491e415411383de2d49cb429cc6":{
      "scriptId":"u30"},
    "99a0dd0951054427b179822e8b195e79":{
      "scriptId":"u31"},
    "ee837d821a654e27bf3531ec5a9c40c0":{
      "scriptId":"u32"},
    "824c144a0f994745b53176ade441db42":{
      "scriptId":"u33"},
    "2db2094e863f44c7baebf86b4d8966c6":{
      "scriptId":"u34"},
    "09dea76125ba49eb9f08a57c7b783c57":{
      "scriptId":"u35"},
    "aa54b43c83e0426790c23beb99a78a0b":{
      "scriptId":"u36"},
    "cd338cd956954442b15cabbf925364ba":{
      "scriptId":"u37"},
    "cf2bfd6483164296a09db241d7991785":{
      "scriptId":"u38"},
    "ecb5827d22eb45bba4908ebf940e2733":{
      "scriptId":"u39"},
    "70df6528f4b14d8db43fae45717019df":{
      "scriptId":"u40"},
    "34c0810dc43e41fdbde9f3ab76d0aedc":{
      "scriptId":"u41"},
    "c65e5bc1dd4c4e468c22383773a8c16d":{
      "scriptId":"u42"},
    "d74f4fd9f0d740829bf4fd78e2b3b08b":{
      "scriptId":"u43"},
    "ccb99020b71d4c7081bc475df78e1085":{
      "scriptId":"u44"},
    "0db894e0c3fc431fa0733b270afa4e5c":{
      "scriptId":"u45"},
    "523d730b069646af8c49124eeb82fa3f":{
      "scriptId":"u46"},
    "1974b245ac87454e964f025e3d092de4":{
      "scriptId":"u47"},
    "c80719855463454e8b823ed49382fb68":{
      "scriptId":"u48"},
    "33017a5f5bbd4948bd3417f7d8402ff7":{
      "scriptId":"u49"},
    "e87fb2a0e3c948baa05cdae1807bee85":{
      "scriptId":"u50"},
    "2a5db0279edb4b938bbda7d0a9d11142":{
      "scriptId":"u51"},
    "2ae58d385e914ecf91bf897bceb9aa36":{
      "scriptId":"u52"},
    "516d2a1b8e0e4d189c7378327fd3659b":{
      "scriptId":"u53"},
    "6f384d8d51fc4a05af793ca6bddc71f5":{
      "scriptId":"u54"},
    "a8eb807c144e48ea870c768366833245":{
      "scriptId":"u55"},
    "05d6dc7dd30f4ce0a5aeaa3ee007e3b2":{
      "scriptId":"u56"},
    "8cad54847ddd4082887d97856f12ad1b":{
      "scriptId":"u57"},
    "7e968cd1cbdb4ecea3975df4e5e2fe38":{
      "scriptId":"u58"},
    "eba18dfb9b1b4acb9dbf77235aab79b3":{
      "scriptId":"u59"},
    "4fd999d88c4147e4ba0fe6b09d311a67":{
      "scriptId":"u60"},
    "275dfaac00bf4a28b78e845ad1692984":{
      "scriptId":"u61"},
    "60e028626df64553a35002887fe08024":{
      "scriptId":"u62"},
    "d1cdb3651ff84292b59d300c9fc324a9":{
      "scriptId":"u63"},
    "aeab452ee10142c7aea210f435179ec5":{
      "scriptId":"u64"},
    "eb9f7c8efd754eab90215cb7df7d0f2c":{
      "scriptId":"u65"},
    "a9021c290ecb4dc7851a3eb5f2fd7a27":{
      "scriptId":"u66"},
    "89ae259e33dd4c86ab64b0876cabe11d":{
      "scriptId":"u67"},
    "8ddaa671a94149aca680cf2f7c32e58b":{
      "scriptId":"u68"},
    "50fc6fc5b1774382b1c72181e427cda1":{
      "scriptId":"u69"},
    "2b892dadf79d4600ac4f38c866c3cd2a":{
      "scriptId":"u70"},
    "09bdf3081d224430b1f403d6c709aa70":{
      "scriptId":"u71"},
    "378580bf581a4ad4ba668b70d44fdc0a":{
      "scriptId":"u72"},
    "429ba7d9e1df4abb8ee8079016e1692c":{
      "scriptId":"u73"},
    "0684d15273164ddfb54f6cf17eefd045":{
      "scriptId":"u74"},
    "3524fea7b3d54dcb9bd694f412049d0c":{
      "scriptId":"u75"},
    "d6dccf718251474bb9803c4d545c9b62":{
      "scriptId":"u76"},
    "220bf3705cda45dc83a777ae18a232f1":{
      "scriptId":"u77"},
    "9d51bdc430744577b3a246a2977d7169":{
      "scriptId":"u78"},
    "3aa26ce3b721469cbd98371da2d59d25":{
      "scriptId":"u79"},
    "b693525ba4724335828b72f3019e059f":{
      "scriptId":"u80"},
    "a77070f2fc5342bc8bbeedaa1013e197":{
      "scriptId":"u81"},
    "53e320f88940440c9d899171ec4cb923":{
      "scriptId":"u82"},
    "9177bbb306a84281a34230848e18f649":{
      "scriptId":"u83"},
    "21fd193e03014938bfd8c226e8917d5a":{
      "scriptId":"u84"},
    "56511f8e60744eb2b9d327f9d30e1c12":{
      "scriptId":"u85"},
    "54eeaa66846e4588935250ed6f794f50":{
      "scriptId":"u86"},
    "c764e96d96d64a758257ba5e83865560":{
      "scriptId":"u87"},
    "6718546662194350afe20a7d2ac519c2":{
      "scriptId":"u88"},
    "99b1e4ac927f4c11af13dc47a29acb19":{
      "scriptId":"u89"},
    "72704bf306894d5988935037762ada67":{
      "scriptId":"u90"},
    "f7269ed2a70d43a5a254cfdc27e0c8f2":{
      "scriptId":"u91"},
    "8449a2d4398943359f802f6c2dad40d2":{
      "scriptId":"u92"},
    "0aa39cd727d34b359706a7aa2920a987":{
      "scriptId":"u93"},
    "dfda0caaf21e4470b780359183e16f84":{
      "scriptId":"u94"},
    "e352505ee6c341daa66518f49bd0082e":{
      "scriptId":"u95"}}});