$axure.loadCurrentPage({
  "url":"设置_个人中心.html",
  "generationDate":new Date(1494572330585.17),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6d84bdebbb7e4b00902fff8911cf301d",
    "type":"Axure:Page",
    "name":"设置/个人中心",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4ba50b5621c74f4a93464a12dd9d79ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":55},
            "size":{
              "width":736,
              "height":167}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43c3b40e5ec7428993baf0ac1947c405",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":55},
                "size":{
                  "width":736,
                  "height":167}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/授课/u0.png"}},
{
          "id":"f307ead0313a4c26bbffda408f531746",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":65},
            "size":{
              "width":97,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06ba751694704624827ac0f312c73faf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":65},
                "size":{
                  "width":97,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/授课/u2.png"}},
{
          "id":"a8ee575197c94a3c80125676446ced86",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":65},
            "size":{
              "width":97,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edaa00fd40da4bf6be16efc9abd1e264",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":65},
                "size":{
                  "width":97,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/授课/u2.png"}},
{
          "id":"d3c5d7b045af46da8226ba17fc4dd858",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":81},
            "size":{
              "width":97,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41688ef3882a40a488731b191bc3208d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":81},
                "size":{
                  "width":97,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/授课/u2.png"}},
{
          "id":"6c4c11abcee0489495eb323488624b0b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":84},
            "size":{
              "width":97,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21444eac75ec40acab02752c48703eba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":84},
                "size":{
                  "width":97,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/授课/u2.png"}},
{
          "id":"80fd40b0495b4e6cbbf9e2cc468ce97f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF434343,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xE2AEDE7B},
            "location":{
              "x":235,
              "y":126},
            "size":{
              "width":60,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF8CC55A},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a464d700aaa748e89c09902f6f2fdb38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF434343,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xE2AEDE7B},
                "location":{
                  "x":235,
                  "y":126},
                "size":{
                  "width":60,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF8CC55A},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页/授课",
                      "target":{
                        "targetType":"page",
                        "url":"首页_授课.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/授课/u34.png"}},
{
          "id":"fb9fe1c8bda04636a74c9e5d3f9bae6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF515151,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFABDD75},
            "location":{
              "x":295,
              "y":122},
            "size":{
              "width":60,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF8CC55A},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3d6a378fcab43a7937a5e90b1fc86c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFABDD75},
                "location":{
                  "x":295,
                  "y":122},
                "size":{
                  "width":60,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF8CC55A},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 授课",
                      "target":{
                        "targetType":"page",
                        "url":"授课.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/课表管理/u34.png"}},
{
          "id":"f3e3385ed14b4218a1a9b80241d12279",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF434343,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFAEDE7B},
            "location":{
              "x":355,
              "y":126},
            "size":{
              "width":60,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF8CC55A},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9120477e62284df8a12ffe03a6608eac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF434343,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFAEDE7B},
                "location":{
                  "x":355,
                  "y":126},
                "size":{
                  "width":60,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF8CC55A},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课表管理",
                      "target":{
                        "targetType":"page",
                        "url":"课表管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/分享_班级/u16.png"}},
{
          "id":"bc07d5d4965747488dfc145ec45f4686",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF515151,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFACDD76},
            "location":{
              "x":415,
              "y":122},
            "size":{
              "width":60,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF8CC55A},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2ab52de367d4572865bd5526e87ae60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFACDD76},
                "location":{
                  "x":415,
                  "y":122},
                "size":{
                  "width":60,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF8CC55A},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 分享/班级",
                      "target":{
                        "targetType":"page",
                        "url":"分享_班级.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/记录_学员聊天/u16.png"}},
{
          "id":"2ec47f6026ae4ab48c1b19e98f141b89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFAEDB78},
            "location":{
              "x":475,
              "y":122},
            "size":{
              "width":60,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF8CC55A},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4b6894273674847888fcc7b6c39594e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFAEDB78},
                "location":{
                  "x":475,
                  "y":122},
                "size":{
                  "width":60,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF8CC55A},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 记录/学员聊天",
                      "target":{
                        "targetType":"page",
                        "url":"记录_学员聊天.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/设置_个人中心/u18.png"}},
{
          "id":"94046ff57e724447a5c1cd4d075b92c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xE266CC66},
            "location":{
              "x":535,
              "y":126},
            "size":{
              "width":60,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF8CC55A},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77420ea4c6084f93bdc143659c67b4ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xE266CC66},
                "location":{
                  "x":535,
                  "y":126},
                "size":{
                  "width":60,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF8CC55A},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置/个人中心",
                      "target":{
                        "targetType":"page",
                        "url":"设置_个人中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/设置_个人中心/u20.png"}},
{
          "id":"1e89eb4cf0a846b4afc78cd361ba277d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3300FF,
              "opacity":1},
            "location":{
              "x":780,
              "y":84},
            "size":{
              "width":170,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a667595c77847b9bccec14fcfc8f38a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF,
                  "opacity":1},
                "location":{
                  "x":780,
                  "y":84},
                "size":{
                  "width":170,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"801f1094108e4898a953b8cda6b66255",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3300FF,
              "opacity":1},
            "location":{
              "x":164,
              "y":214},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"582dad3088334e799328316a3088e6d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF,
                  "opacity":1},
                "location":{
                  "x":164,
                  "y":214},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置/个人中心",
                      "target":{
                        "targetType":"page",
                        "url":"设置_个人中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6682a7d4ef541c6acb3fbe4a353c100",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":254,
              "y":195},
            "size":{
              "width":57,
              "height":16},
            "rotation":"353",
            "textRotation":"353"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc4c3d930df84072997ea76687291b27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":254,
                  "y":195},
                "size":{
                  "width":57,
                  "height":16},
                "rotation":"353",
                "textRotation":"353"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的收藏",
                      "target":{
                        "targetType":"page",
                        "url":"我的收藏.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b3b641afd45452a93c61491e8317284",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":820},
            "size":{
              "width":832,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a808f630ab441880b0db51e285d3fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":820},
                "size":{
                  "width":832,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/备课/u131.png"}},
{
          "id":"856316e05c50447b89e709c5d55a7c26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF336666,
              "opacity":1},
            "location":{
              "x":66,
              "y":833},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1412a6e813348c1b466b4e0d322cb90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF336666,
                  "opacity":1},
                "location":{
                  "x":66,
                  "y":833},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77453d2bb7f541eba982ddde6336d7fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":260},
            "size":{
              "width":60,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3a31381ae69438a88519c7d2ea06959",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":260},
                "size":{
                  "width":60,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学员分组/u72.png"}},
{
          "id":"924b7207ce494c5f9eefe4745942167f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":284,
              "y":364},
            "size":{
              "width":66,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"705a2681b25847a2904bf0078bc30631",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":284,
                  "y":364},
                "size":{
                  "width":66,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6514f793b70549ed91cb97e26a66e65a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":340,
              "y":330},
            "size":{
              "width":40,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2854dd2b24f2450baf644c3708601e5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":340,
                  "y":330},
                "size":{
                  "width":40,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4129090ed56d426d86f4900b857ec178",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":284,
              "y":390},
            "size":{
              "width":105,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6afca41c38e4167bc3c35e95f396b02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":284,
                  "y":390},
                "size":{
                  "width":105,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b009d153bf5942628f1e34f5639e33b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":284,
              "y":416},
            "size":{
              "width":92,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c1c16e0278646b0a44bf0ecb7d4f91f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":284,
                  "y":416},
                "size":{
                  "width":92,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e400087c1b794f629cd0b77c2108ae7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":104,
              "y":470},
            "size":{
              "width":528,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9f5ceecdc9a41cbb747b4dd219f0774",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":104,
                  "y":470},
                "size":{
                  "width":528,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd308fd79fb2445497be7472d84721b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":104,
              "y":452},
            "size":{
              "width":27,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b05ce32a8cc34024b47c0290a102d4db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":104,
                  "y":452},
                "size":{
                  "width":27,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3f43fe2e1fd4f3b9f638d2468537f5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":104,
              "y":583},
            "size":{
              "width":226,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4737d55a7d554b26af61f8e9a675acdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":104,
                  "y":583},
                "size":{
                  "width":226,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea9c9832705540cb89036485201aa8ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":104,
              "y":565},
            "size":{
              "width":27,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"371ee34d522b49eb873eeb7b5446d690",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":104,
                  "y":565},
                "size":{
                  "width":27,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a32109cfb74a47c48c12f1f9833c60e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":104,
              "y":630},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfbd1422bd454451a283fa2d9a2919fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":104,
                  "y":630},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd69b88bf63e4664a31df65fb7c4b7f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":104,
              "y":612},
            "size":{
              "width":53,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f160a4758cb46729ba99b5d80c63560",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":104,
                  "y":612},
                "size":{
                  "width":53,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4c79b05c7bd4e8699b18130dca9ba90",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":85.5,
              "y":656},
            "size":{
              "width":489,
              "height":85}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c44c60f09494931a83bf08118517b9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":85.5,
                  "y":656},
                "size":{
                  "width":489,
                  "height":85}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置_个人中心/u54.png"}},
{
          "id":"a49643f845e140eba8fa513c3666f5a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3300FF,
              "opacity":1},
            "location":{
              "x":690,
              "y":244},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2ae3e627cd64d1285e5537b6d35d884",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF,
                  "opacity":1},
                "location":{
                  "x":690,
                  "y":244},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 修改个人信息",
                      "target":{
                        "targetType":"page",
                        "url":"修改个人信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11ddaccd5e3d45c6a2f8598a19103770",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":41},
            "size":{
              "width":77,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF33CCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/备课/u137_line.png"}},
{
          "id":"4bd74264f52e4f92ae4aef41b33bc3c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":123,
              "y":70},
            "size":{
              "width":93,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"345971fe2abc4d36828b4ce439ab4c30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":123,
                  "y":70},
                "size":{
                  "width":93,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97bc611f880e43139bc5e5c361648cc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":740,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3e97349d4e6431d9e0cf18ec8463939",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":740,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/授课/u104.png"}},
{
          "id":"8ccf89177f094e488b6311261e93ed59",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":9},
            "size":{
              "width":68,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c5273bd8e6a48d191a536dae8f6206f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":9},
                "size":{
                  "width":68,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"985ff4ec25d640b695d55d9914258c32",
          "label":"beike",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":119,
              "y":14},
            "size":{
              "width":80,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23dff8873ff44f6dab4031f43e2c6d79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":119,
                  "y":14},
                "size":{
                  "width":80,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 备课",
                      "target":{
                        "targetType":"page",
                        "url":"备课.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 beike = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["985ff4ec25d640b695d55d9914258c32"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 beike = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["985ff4ec25d640b695d55d9914258c32"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/备课/beike_u6.png",
            "selected~":"images/备课/beike_u6_selected.png"}},
{
          "id":"11a7483a66a64f40af3644152090e8f1",
          "label":"souke",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":215,
              "y":14},
            "size":{
              "width":80,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a97477e4ca3a42b7aa7ca3462be4f2e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":215,
                  "y":14},
                "size":{
                  "width":80,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页/授课",
                      "target":{
                        "targetType":"page",
                        "url":"首页_授课.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 souke = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["11a7483a66a64f40af3644152090e8f1"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 souke = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["11a7483a66a64f40af3644152090e8f1"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/备课/beike_u6.png",
            "selected~":"images/备课/beike_u6_selected.png"}},
{
          "id":"dd3b2350c5b244718f1d68be7b33dc3c",
          "label":"guanli",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":310,
              "y":14},
            "size":{
              "width":80,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"553ef894c1d248f88e722de5c9d2ec3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":310,
                  "y":14},
                "size":{
                  "width":80,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 校内管理",
                      "target":{
                        "targetType":"page",
                        "url":"校内管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 guanli = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["dd3b2350c5b244718f1d68be7b33dc3c"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 guanli = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["dd3b2350c5b244718f1d68be7b33dc3c"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/备课/beike_u6.png",
            "selected~":"images/备课/beike_u6_selected.png"}},
{
          "id":"42d840af6b8c4115bcb234f0bc2bbaf0",
          "label":"ceping",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":409,
              "y":14},
            "size":{
              "width":80,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69513a98ab3b4067991cd427daa8ced2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":409,
                  "y":14},
                "size":{
                  "width":80,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测评",
                      "target":{
                        "targetType":"page",
                        "url":"测评.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 ceping = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["42d840af6b8c4115bcb234f0bc2bbaf0"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 ceping = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["42d840af6b8c4115bcb234f0bc2bbaf0"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/备课/beike_u6.png",
            "selected~":"images/备课/beike_u6_selected.png"}},
{
          "id":"40b410c1382f42ae84663fc45092d161",
          "label":"peixun",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":512,
              "y":14},
            "size":{
              "width":80,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e9b7bf2cee748da8cfccf554b431adc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":512,
                  "y":14},
                "size":{
                  "width":80,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 培训",
                      "target":{
                        "targetType":"page",
                        "url":"培训.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["40b410c1382f42ae84663fc45092d161"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["40b410c1382f42ae84663fc45092d161"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/备课/beike_u6.png",
            "selected~":"images/备课/beike_u6_selected.png"}},
{
          "id":"3a25a19805c045219bd4a3876164736f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":14},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3399},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffa9e3c31bde41f49d202c0411f3543a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":14},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3399},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 user 弹出效果",
                      "objectsToFades":[{
                          "objectPath":["000592e0f63143fd9e15bb8d33626690"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"flyout"}}}]}]}]}},
          "images":{
            "normal~":"images/首页_授课/u112.png"}},
{
          "id":"000592e0f63143fd9e15bb8d33626690",
          "label":"user",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":630,
              "y":43},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"2be70590ba5e4fda909426114e418f30",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f429f86a7af44438802fe8a97c5b9fe1",
                  "label":"",
                  "parentDynamicPanel":"000592e0f63143fd9e15bb8d33626690",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFA1A1A1,
                      "opacity":1},
                    "size":{
                      "width":90,
                      "height":27},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF3399}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c8aba2aa4bf84749bfae3519939692a7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"000592e0f63143fd9e15bb8d33626690",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFA1A1A1,
                          "opacity":1},
                        "size":{
                          "width":90,
                          "height":27},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF3399}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/备课/u53.png"}},
{
                  "id":"faa94c2a588a4fb48075221853dcc7cd",
                  "label":"",
                  "parentDynamicPanel":"000592e0f63143fd9e15bb8d33626690",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFA1A1A1,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":26},
                    "size":{
                      "width":90,
                      "height":27},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF3399}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7e1971dffcaa4b5e85a42531a5a194e7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"000592e0f63143fd9e15bb8d33626690",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFA1A1A1,
                          "opacity":1},
                        "location":{
                          "x":0,
                          "y":26},
                        "size":{
                          "width":90,
                          "height":27},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF3399}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/备课/u53.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "4ba50b5621c74f4a93464a12dd9d79ec":{
      "scriptId":"u0"},
    "43c3b40e5ec7428993baf0ac1947c405":{
      "scriptId":"u1"},
    "f307ead0313a4c26bbffda408f531746":{
      "scriptId":"u2"},
    "06ba751694704624827ac0f312c73faf":{
      "scriptId":"u3"},
    "a8ee575197c94a3c80125676446ced86":{
      "scriptId":"u4"},
    "edaa00fd40da4bf6be16efc9abd1e264":{
      "scriptId":"u5"},
    "d3c5d7b045af46da8226ba17fc4dd858":{
      "scriptId":"u6"},
    "41688ef3882a40a488731b191bc3208d":{
      "scriptId":"u7"},
    "6c4c11abcee0489495eb323488624b0b":{
      "scriptId":"u8"},
    "21444eac75ec40acab02752c48703eba":{
      "scriptId":"u9"},
    "80fd40b0495b4e6cbbf9e2cc468ce97f":{
      "scriptId":"u10"},
    "a464d700aaa748e89c09902f6f2fdb38":{
      "scriptId":"u11"},
    "fb9fe1c8bda04636a74c9e5d3f9bae6d":{
      "scriptId":"u12"},
    "c3d6a378fcab43a7937a5e90b1fc86c5":{
      "scriptId":"u13"},
    "f3e3385ed14b4218a1a9b80241d12279":{
      "scriptId":"u14"},
    "9120477e62284df8a12ffe03a6608eac":{
      "scriptId":"u15"},
    "bc07d5d4965747488dfc145ec45f4686":{
      "scriptId":"u16"},
    "c2ab52de367d4572865bd5526e87ae60":{
      "scriptId":"u17"},
    "2ec47f6026ae4ab48c1b19e98f141b89":{
      "scriptId":"u18"},
    "d4b6894273674847888fcc7b6c39594e":{
      "scriptId":"u19"},
    "94046ff57e724447a5c1cd4d075b92c0":{
      "scriptId":"u20"},
    "77420ea4c6084f93bdc143659c67b4ad":{
      "scriptId":"u21"},
    "1e89eb4cf0a846b4afc78cd361ba277d":{
      "scriptId":"u22"},
    "7a667595c77847b9bccec14fcfc8f38a":{
      "scriptId":"u23"},
    "801f1094108e4898a953b8cda6b66255":{
      "scriptId":"u24"},
    "582dad3088334e799328316a3088e6d6":{
      "scriptId":"u25"},
    "a6682a7d4ef541c6acb3fbe4a353c100":{
      "scriptId":"u26"},
    "fc4c3d930df84072997ea76687291b27":{
      "scriptId":"u27"},
    "9b3b641afd45452a93c61491e8317284":{
      "scriptId":"u28"},
    "e1a808f630ab441880b0db51e285d3fa":{
      "scriptId":"u29"},
    "856316e05c50447b89e709c5d55a7c26":{
      "scriptId":"u30"},
    "b1412a6e813348c1b466b4e0d322cb90":{
      "scriptId":"u31"},
    "77453d2bb7f541eba982ddde6336d7fb":{
      "scriptId":"u32"},
    "a3a31381ae69438a88519c7d2ea06959":{
      "scriptId":"u33"},
    "924b7207ce494c5f9eefe4745942167f":{
      "scriptId":"u34"},
    "705a2681b25847a2904bf0078bc30631":{
      "scriptId":"u35"},
    "6514f793b70549ed91cb97e26a66e65a":{
      "scriptId":"u36"},
    "2854dd2b24f2450baf644c3708601e5e":{
      "scriptId":"u37"},
    "4129090ed56d426d86f4900b857ec178":{
      "scriptId":"u38"},
    "b6afca41c38e4167bc3c35e95f396b02":{
      "scriptId":"u39"},
    "b009d153bf5942628f1e34f5639e33b1":{
      "scriptId":"u40"},
    "3c1c16e0278646b0a44bf0ecb7d4f91f":{
      "scriptId":"u41"},
    "e400087c1b794f629cd0b77c2108ae7f":{
      "scriptId":"u42"},
    "f9f5ceecdc9a41cbb747b4dd219f0774":{
      "scriptId":"u43"},
    "dd308fd79fb2445497be7472d84721b3":{
      "scriptId":"u44"},
    "b05ce32a8cc34024b47c0290a102d4db":{
      "scriptId":"u45"},
    "c3f43fe2e1fd4f3b9f638d2468537f5f":{
      "scriptId":"u46"},
    "4737d55a7d554b26af61f8e9a675acdb":{
      "scriptId":"u47"},
    "ea9c9832705540cb89036485201aa8ad":{
      "scriptId":"u48"},
    "371ee34d522b49eb873eeb7b5446d690":{
      "scriptId":"u49"},
    "a32109cfb74a47c48c12f1f9833c60e0":{
      "scriptId":"u50"},
    "dfbd1422bd454451a283fa2d9a2919fe":{
      "scriptId":"u51"},
    "cd69b88bf63e4664a31df65fb7c4b7f3":{
      "scriptId":"u52"},
    "0f160a4758cb46729ba99b5d80c63560":{
      "scriptId":"u53"},
    "a4c79b05c7bd4e8699b18130dca9ba90":{
      "scriptId":"u54"},
    "0c44c60f09494931a83bf08118517b9c":{
      "scriptId":"u55"},
    "a49643f845e140eba8fa513c3666f5a2":{
      "scriptId":"u56"},
    "c2ae3e627cd64d1285e5537b6d35d884":{
      "scriptId":"u57"},
    "11ddaccd5e3d45c6a2f8598a19103770":{
      "scriptId":"u58"},
    "4bd74264f52e4f92ae4aef41b33bc3c3":{
      "scriptId":"u59"},
    "345971fe2abc4d36828b4ce439ab4c30":{
      "scriptId":"u60"},
    "97bc611f880e43139bc5e5c361648cc3":{
      "scriptId":"u61"},
    "d3e97349d4e6431d9e0cf18ec8463939":{
      "scriptId":"u62"},
    "8ccf89177f094e488b6311261e93ed59":{
      "scriptId":"u63"},
    "5c5273bd8e6a48d191a536dae8f6206f":{
      "scriptId":"u64"},
    "985ff4ec25d640b695d55d9914258c32":{
      "scriptId":"u65"},
    "23dff8873ff44f6dab4031f43e2c6d79":{
      "scriptId":"u66"},
    "11a7483a66a64f40af3644152090e8f1":{
      "scriptId":"u67"},
    "a97477e4ca3a42b7aa7ca3462be4f2e3":{
      "scriptId":"u68"},
    "dd3b2350c5b244718f1d68be7b33dc3c":{
      "scriptId":"u69"},
    "553ef894c1d248f88e722de5c9d2ec3f":{
      "scriptId":"u70"},
    "42d840af6b8c4115bcb234f0bc2bbaf0":{
      "scriptId":"u71"},
    "69513a98ab3b4067991cd427daa8ced2":{
      "scriptId":"u72"},
    "40b410c1382f42ae84663fc45092d161":{
      "scriptId":"u73"},
    "7e9b7bf2cee748da8cfccf554b431adc":{
      "scriptId":"u74"},
    "3a25a19805c045219bd4a3876164736f":{
      "scriptId":"u75"},
    "ffa9e3c31bde41f49d202c0411f3543a":{
      "scriptId":"u76"},
    "000592e0f63143fd9e15bb8d33626690":{
      "scriptId":"u77"},
    "f429f86a7af44438802fe8a97c5b9fe1":{
      "scriptId":"u78"},
    "c8aba2aa4bf84749bfae3519939692a7":{
      "scriptId":"u79"},
    "faa94c2a588a4fb48075221853dcc7cd":{
      "scriptId":"u80"},
    "7e1971dffcaa4b5e85a42531a5a194e7":{
      "scriptId":"u81"}}});