$axure.loadCurrentPage({
  "url":"金八力课程.html",
  "generationDate":new Date(1494572348332.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f89995e9d265469b9f2ccbd2392bcf8c",
    "type":"Axure:Page",
    "name":"金八力课程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b465a73c06fd46b4ae894baf746069bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":102},
            "size":{
              "width":1150,
              "height":128},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7eedd425207d4da195c969ecc555787b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":1150,
                  "height":128},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u0.png"}},
{
          "id":"447f9ff7522a466080083431be61de8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "size":{
              "width":1150,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee8b123c882a44048042e383ecfa3dec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "size":{
                  "width":1150,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"c21c7c7a84f1463eab8b5e4d63888362",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF515151,
              "opacity":1},
            "location":{
              "x":20,
              "y":7},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"260aa195a7f04a57961fbf0ce21305cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":7},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c10715e1509643fba5cf10de87b5bdc3",
          "label":"login",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1}}},
            "location":{
              "x":730,
              "y":7},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5120be87c1e4a99aa40f9742bec4b0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333,
                      "opacity":1}}},
                "location":{
                  "x":730,
                  "y":7},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["c10715e1509643fba5cf10de87b5bdc3"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["c10715e1509643fba5cf10de87b5bdc3"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif"}},
{
          "id":"4d1d9b2afe994f00a68cdef0a13316a9",
          "label":"2weima",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":1024,
              "y":29},
            "size":{
              "width":126,
              "height":100},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"687c0a73fdd04dcabaa4f5368e736b4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":1024,
                  "y":29},
                "size":{
                  "width":126,
                  "height":100},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/2weima_u10.png"}},
{
          "id":"ad7e5f211cb7460c8f27f201d851543a",
          "label":"login",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1}}},
            "location":{
              "x":950,
              "y":7},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6115150faa748b5ac7236b417095b0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333,
                      "opacity":1}}},
                "location":{
                  "x":950,
                  "y":7},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["ad7e5f211cb7460c8f27f201d851543a"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["ad7e5f211cb7460c8f27f201d851543a"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif"}},
{
          "id":"f52d99d8bd0a462dad0f4c99002d3155",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":34,
              "y":52},
            "size":{
              "width":60,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a81cb63fefa42578d80a627499f6ef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":34,
                  "y":52},
                "size":{
                  "width":60,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d84dc86e43044e838445706038d8fb2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":64},
            "size":{
              "width":79,
              "height":16},
            "rotation":"353",
            "textRotation":"353"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c38b4cb0c5474037a37394196c586215",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":64},
                "size":{
                  "width":79,
                  "height":16},
                "rotation":"353",
                "textRotation":"353"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc5964e3df9841fa8efc8a07307a353b",
          "label":"kefu",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1}}},
            "location":{
              "x":867,
              "y":7},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af4552e90ea040d79761981da4c9a2f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333,
                      "opacity":1}}},
                "location":{
                  "x":867,
                  "y":7},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 kefu = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["bc5964e3df9841fa8efc8a07307a353b"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"fadeWidget",
                      "description":"显示 qq 弹出效果",
                      "objectsToFades":[{
                          "objectPath":["81e62311b5d04e28b4245a8261a32a9d"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"flyout"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 kefu = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["bc5964e3df9841fa8efc8a07307a353b"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif"}},
{
          "id":"81e62311b5d04e28b4245a8261a32a9d",
          "label":"qq",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":867,
              "y":29},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5c541e6f09034606aa314cdd72fed0aa",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c635bf3258d3424995b57a2a81e17f3c",
                  "label":"",
                  "parentDynamicPanel":"81e62311b5d04e28b4245a8261a32a9d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":100},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"556f6234a53b45bb91c23357cffaf9de",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"81e62311b5d04e28b4245a8261a32a9d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":100},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u21.png"}},
{
                  "id":"38cf059477b0447d9a08328ed980269d",
                  "label":"",
                  "parentDynamicPanel":"81e62311b5d04e28b4245a8261a32a9d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF868686,
                      "opacity":1},
                    "location":{
                      "x":23,
                      "y":11},
                    "size":{
                      "width":99,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe27386b9b0d42c6a6df95a8baece77a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"81e62311b5d04e28b4245a8261a32a9d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF868686,
                          "opacity":1},
                        "location":{
                          "x":23,
                          "y":11},
                        "size":{
                          "width":99,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6eb0efb9bfb24aafad02aa7b2c663e5d",
                  "label":"",
                  "parentDynamicPanel":"81e62311b5d04e28b4245a8261a32a9d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF868686,
                      "opacity":1},
                    "location":{
                      "x":23,
                      "y":37},
                    "size":{
                      "width":99,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c68a3a71b58d4629ad85512d57f900ab",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"81e62311b5d04e28b4245a8261a32a9d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF868686,
                          "opacity":1},
                        "location":{
                          "x":23,
                          "y":37},
                        "size":{
                          "width":99,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4f9a56b87b664bafbcb8424d02ca0950",
                  "label":"",
                  "parentDynamicPanel":"81e62311b5d04e28b4245a8261a32a9d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF868686,
                      "opacity":1},
                    "location":{
                      "x":23,
                      "y":63},
                    "size":{
                      "width":99,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0e182d8195d54c46ad60740d7ecec955",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"81e62311b5d04e28b4245a8261a32a9d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF868686,
                          "opacity":1},
                        "location":{
                          "x":23,
                          "y":63},
                        "size":{
                          "width":99,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"5790a9880365496186964bf4e6d10aaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":230,
              "y":78},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d99ae81ce8c54ae9933f963aad313524",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":78},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f86552663db413ab96528a4f25b62b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3366,
              "opacity":1},
            "location":{
              "x":292,
              "y":78},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72669f41d59842518d1557fdf9e0699b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1},
                "location":{
                  "x":292,
                  "y":78},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 金八力课程",
                      "target":{
                        "targetType":"page",
                        "url":"金八力课程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ab2ff2807cd4f9b8ff51cd98c459b1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":399,
              "y":78},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a1c946c27db4391ad431e442d13abb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":399,
                  "y":78},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 项目优势",
                      "target":{
                        "targetType":"page",
                        "url":"项目优势.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1550974fa2a14aefb6114c0b5cb42c6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":590,
              "y":78},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ace0d7e4bfd94db78646b5f60ea2a6b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":590,
                  "y":78},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 校区分布",
                      "target":{
                        "targetType":"page",
                        "url":"校区分布.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a602cafd27c541df9042b511638a4899",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":497,
              "y":78},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbe25ca44f784100a60d4a150374a732",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":497,
                  "y":78},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 加盟服务",
                      "target":{
                        "targetType":"page",
                        "url":"加盟服务.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bebb6cc8cfbb400293c01e8987bb6af2",
          "label":"login",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1}}},
            "location":{
              "x":795,
              "y":7},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3369d206b244aa5a2d3e639a3745708",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333,
                      "opacity":1}}},
                "location":{
                  "x":795,
                  "y":7},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 注册",
                      "target":{
                        "targetType":"page",
                        "url":"注册.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["bebb6cc8cfbb400293c01e8987bb6af2"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["bebb6cc8cfbb400293c01e8987bb6af2"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif"}},
{
          "id":"25a0bb3d24324c148ce63fc1ce18cdac",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":124,
              "y":2910},
            "size":{
              "width":53,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8286b265d36f4327a2d9d6a0efd351bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":124,
                  "y":2910},
                "size":{
                  "width":53,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c694d4ff824d433ebd9ba4864dd48a76",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":230,
              "y":2916},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe70887cb0534a7f93bdbec04e0aede4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":2916},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54c6e8e17c12420e9f46ef1e1daefd55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":20,
              "y":124},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"862f0a77fad74ee9ac243c69829f61e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":124},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51c4e543262b478899e7de36badc8836",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":88,
              "y":124},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a9eeea3af0a435ab9c5fc986579783c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":124},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcadebceedcd4422832cd8c305b2ed7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":150,
              "y":124},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed8b9fb1f79647008e1eef010d43ee13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":150,
                  "y":124},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61c87e2ae4fc4b6f81d2884af594a08e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":220,
              "y":124},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74e6454d9d7146f785b0bec6c7f94c8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":220,
                  "y":124},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"939c6597e5654177be1d1afe16638c87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":293,
              "y":124},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35fe87e387b546cdadc4bc6d0446831f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":293,
                  "y":124},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8a398a3ab4044f9b2d01879c5966146",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":389,
              "y":124},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8f02629de7e475aba23854d4a26415a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":389,
                  "y":124},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cea7953ffa01474396e123379f80d104",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":484,
              "y":124},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"970445342fb24d17856442dcae0caf4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":484,
                  "y":124},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4e0172285b44e8da71e780ff0e8ce98",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":570,
              "y":124},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0792accdec4c42ceb94f758b48bfcfea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":570,
                  "y":124},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10e6488250654fc386c58af8943b7f52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":655,
              "y":124},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03dc5629866b4ddabe27adf86b964e92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":655,
                  "y":124},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7be5488a8c1448caba884fb4fb74d12a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":20,
              "y":177},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5b197002c174e48ac26cd79d3280de9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":177},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54076d6aa045449fbaaf077a3e2b5c69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":88,
              "y":177},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f13acc830d7f482c9ea6c4f423b80d2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":88,
                  "y":177},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"662c5f237365426fae0e21031505d5c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":220,
              "y":177},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"451fba689ceb4916a4b23a20a74fb6f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":220,
                  "y":177},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d521cc5dbda400ab1c054743b5d370f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":419,
              "y":177},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57741645811f4fbc9e9ac3110be6ec82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":419,
                  "y":177},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6d774d5ac9843dab89f5ffb3aeb6fcd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":153},
            "size":{
              "width":1128,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/金八力课程/u69_line.png"}},
{
          "id":"c9fbeeceda814c9b9ca8b0be239523fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":240},
            "size":{
              "width":261,
              "height":670},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"177f09ac5b2b46aeb1800a8bb5fb7aa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":240},
                "size":{
                  "width":261,
                  "height":670},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u70.png"}},
{
          "id":"bdf054af6cc840cdb068fd30fa219a0d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":271,
              "y":240},
            "size":{
              "width":879,
              "height":670},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fecd369697e4f27b99c80e5d490f4f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":271,
                  "y":240},
                "size":{
                  "width":879,
                  "height":670},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u72.png"}},
{
          "id":"96b4b4aebc8b4064be3f537313073017",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":11,
              "y":248},
            "size":{
              "width":153,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"263d93d0f87043e4bb47b1b5a0bd2f4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":11,
                  "y":248},
                "size":{
                  "width":153,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a911455f9d94195bd37f9e17924713a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":281,
              "y":248},
            "size":{
              "width":208,
              "height":201}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fe6a76684b74676aada571a9c8ce4dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":281,
                  "y":248},
                "size":{
                  "width":208,
                  "height":201}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u76.png"}},
{
          "id":"e7baa904ffaa428ab940374820431e1e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":277},
            "size":{
              "width":243,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fcfd48f27474224bade4b8028f6da66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":277},
                "size":{
                  "width":243,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u78.png"}},
{
          "id":"25834c6a76cf4824b1cdb441a69f4108",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":370},
            "size":{
              "width":238,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/金八力课程/u80_line.png"}},
{
          "id":"7fd4406674284655b8ca6eaa1c08c0bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":7,
              "y":384},
            "size":{
              "width":243,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf2623a1c1ad4a1daadb18995d61e249",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":7,
                  "y":384},
                "size":{
                  "width":243,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u78.png"}},
{
          "id":"f8d4e75daa4649778692e6e6e66173d7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":477},
            "size":{
              "width":238,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/金八力课程/u80_line.png"}},
{
          "id":"7af408ad897b4d78afd5d532315a4dbe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":493},
            "size":{
              "width":243,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebc88a85443d43c09dbd3132dc4a0b94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":493},
                "size":{
                  "width":243,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u78.png"}},
{
          "id":"74f03c9a0d55467fa8b7c9e2f2848d0b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":586},
            "size":{
              "width":238,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/金八力课程/u80_line.png"}},
{
          "id":"ef12a5957ecb4176b49af1fd28a6a9bc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":602},
            "size":{
              "width":243,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7437b2b374fd449694b609a642a53659",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":602},
                "size":{
                  "width":243,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u78.png"}},
{
          "id":"a6c67cbdd38a42eca68a52d45f033372",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":499,
              "y":248},
            "size":{
              "width":208,
              "height":201}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e25dfc17f1a483f816fb123f5443300",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":499,
                  "y":248},
                "size":{
                  "width":208,
                  "height":201}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u76.png"}},
{
          "id":"5532265142cd429781d36ffc1905a907",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":717,
              "y":248},
            "size":{
              "width":208,
              "height":201}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3d2903226104cce92ff4107b867c8b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":717,
                  "y":248},
                "size":{
                  "width":208,
                  "height":201}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u76.png"}},
{
          "id":"a1dff567ec6249b5b1fd74f2e9c07a99",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":934,
              "y":248},
            "size":{
              "width":208,
              "height":201}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7d8c8056b6a407db15e088ab63670fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":934,
                  "y":248},
                "size":{
                  "width":208,
                  "height":201}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u76.png"}},
{
          "id":"038de08a4d36473087056187c7622140",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":457},
            "size":{
              "width":208,
              "height":201}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89b6bc693c9341cb93a2dd0a4cb59c2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":279,
                  "y":457},
                "size":{
                  "width":208,
                  "height":201}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u76.png"}},
{
          "id":"d5728866a1364b4d977ca29c3f0d76c5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":497,
              "y":457},
            "size":{
              "width":208,
              "height":201}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77cfce4bbce14da880727983f628bb8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":497,
                  "y":457},
                "size":{
                  "width":208,
                  "height":201}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u76.png"}},
{
          "id":"33682b4ed2944f1d96a2737afbab732b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":715,
              "y":457},
            "size":{
              "width":208,
              "height":201}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb7b10a51dbe455b96dc3fa37e24dd2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":715,
                  "y":457},
                "size":{
                  "width":208,
                  "height":201}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u76.png"}},
{
          "id":"6fa2e512e6a04b27b43b1678b6d981f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":932,
              "y":457},
            "size":{
              "width":208,
              "height":201}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b662492c60b4792b6f1ac09575de322",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":932,
                  "y":457},
                "size":{
                  "width":208,
                  "height":201}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u76.png"}},
{
          "id":"eea71ba11c654b6290ec63131fbf3be5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":660},
            "size":{
              "width":865,
              "height":224}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5132133fd604b50ba666cd4daeea87f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":277,
                  "y":660},
                "size":{
                  "width":865,
                  "height":224}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u103.jpg"}},
{
          "id":"66e079fa8cb34fa6b2b7091c21e84d74",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":552,
              "y":930},
            "size":{
              "width":248,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5be36865fd3b4ca58fe6202f12a41588",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":552,
                  "y":930},
                "size":{
                  "width":248,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u105.png"}},
{
          "id":"42657cb821e4467396b6115a85d493a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":0,
              "y":1002},
            "size":{
              "width":1250,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0922ad811b6497f8c7aef93058dff74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":0,
                  "y":1002},
                "size":{
                  "width":1250,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u69.png"}},
{
          "id":"5340c3b8ef90418bbfab5b1f730f4aec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":124,
              "y":1042},
            "size":{
              "width":53,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"258c2b8f181941eb9ca5b4497fc7f9f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":124,
                  "y":1042},
                "size":{
                  "width":53,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"678e319ed5aa47c2a092d84d141c903e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":230,
              "y":1048},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1feb9bedd73447a4833715b55fa7280a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":1048},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f862f7babed4e62b35ff36a7ba27390",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":290},
            "size":{
              "width":240,
              "height":400}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 视频详情",
                      "target":{
                        "targetType":"page",
                        "url":"视频详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"c84cf4b4882e4e0da83b8f2f303ec4e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":282,
              "y":402},
            "size":{
              "width":109,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d45dd129b3674ea99ea502d112dc48a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":282,
                  "y":402},
                "size":{
                  "width":109,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u114.png"}},
{
          "id":"4c45729fc37b411f94a9df2a9016010e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":499,
              "y":402},
            "size":{
              "width":109,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56e88fdf87ad4e0b8923791224c84a26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":499,
                  "y":402},
                "size":{
                  "width":109,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u114.png"}},
{
          "id":"afc8804854da4ecda149ef7bb31a3942",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":717,
              "y":402},
            "size":{
              "width":109,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57c3dfc386e94b4c89779655a5fb3e77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":717,
                  "y":402},
                "size":{
                  "width":109,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/金八力课程/u114.png"}},
{
          "id":"cbbe23de9cbb479c83ac69b91343938f",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":248},
            "size":{
              "width":865,
              "height":642}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 视频详情",
                      "target":{
                        "targetType":"page",
                        "url":"视频详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "b465a73c06fd46b4ae894baf746069bb":{
      "scriptId":"u0"},
    "7eedd425207d4da195c969ecc555787b":{
      "scriptId":"u1"},
    "447f9ff7522a466080083431be61de8d":{
      "scriptId":"u2"},
    "ee8b123c882a44048042e383ecfa3dec":{
      "scriptId":"u3"},
    "c21c7c7a84f1463eab8b5e4d63888362":{
      "scriptId":"u4"},
    "260aa195a7f04a57961fbf0ce21305cf":{
      "scriptId":"u5"},
    "c10715e1509643fba5cf10de87b5bdc3":{
      "scriptId":"u6"},
    "d5120be87c1e4a99aa40f9742bec4b0d":{
      "scriptId":"u7"},
    "4d1d9b2afe994f00a68cdef0a13316a9":{
      "scriptId":"u8"},
    "687c0a73fdd04dcabaa4f5368e736b4e":{
      "scriptId":"u9"},
    "ad7e5f211cb7460c8f27f201d851543a":{
      "scriptId":"u10"},
    "d6115150faa748b5ac7236b417095b0e":{
      "scriptId":"u11"},
    "f52d99d8bd0a462dad0f4c99002d3155":{
      "scriptId":"u12"},
    "7a81cb63fefa42578d80a627499f6ef6":{
      "scriptId":"u13"},
    "d84dc86e43044e838445706038d8fb2e":{
      "scriptId":"u14"},
    "c38b4cb0c5474037a37394196c586215":{
      "scriptId":"u15"},
    "bc5964e3df9841fa8efc8a07307a353b":{
      "scriptId":"u16"},
    "af4552e90ea040d79761981da4c9a2f0":{
      "scriptId":"u17"},
    "81e62311b5d04e28b4245a8261a32a9d":{
      "scriptId":"u18"},
    "c635bf3258d3424995b57a2a81e17f3c":{
      "scriptId":"u19"},
    "556f6234a53b45bb91c23357cffaf9de":{
      "scriptId":"u20"},
    "38cf059477b0447d9a08328ed980269d":{
      "scriptId":"u21"},
    "fe27386b9b0d42c6a6df95a8baece77a":{
      "scriptId":"u22"},
    "6eb0efb9bfb24aafad02aa7b2c663e5d":{
      "scriptId":"u23"},
    "c68a3a71b58d4629ad85512d57f900ab":{
      "scriptId":"u24"},
    "4f9a56b87b664bafbcb8424d02ca0950":{
      "scriptId":"u25"},
    "0e182d8195d54c46ad60740d7ecec955":{
      "scriptId":"u26"},
    "5790a9880365496186964bf4e6d10aaa":{
      "scriptId":"u27"},
    "d99ae81ce8c54ae9933f963aad313524":{
      "scriptId":"u28"},
    "0f86552663db413ab96528a4f25b62b9":{
      "scriptId":"u29"},
    "72669f41d59842518d1557fdf9e0699b":{
      "scriptId":"u30"},
    "1ab2ff2807cd4f9b8ff51cd98c459b1b":{
      "scriptId":"u31"},
    "8a1c946c27db4391ad431e442d13abb9":{
      "scriptId":"u32"},
    "1550974fa2a14aefb6114c0b5cb42c6a":{
      "scriptId":"u33"},
    "ace0d7e4bfd94db78646b5f60ea2a6b9":{
      "scriptId":"u34"},
    "a602cafd27c541df9042b511638a4899":{
      "scriptId":"u35"},
    "bbe25ca44f784100a60d4a150374a732":{
      "scriptId":"u36"},
    "bebb6cc8cfbb400293c01e8987bb6af2":{
      "scriptId":"u37"},
    "a3369d206b244aa5a2d3e639a3745708":{
      "scriptId":"u38"},
    "25a0bb3d24324c148ce63fc1ce18cdac":{
      "scriptId":"u39"},
    "8286b265d36f4327a2d9d6a0efd351bc":{
      "scriptId":"u40"},
    "c694d4ff824d433ebd9ba4864dd48a76":{
      "scriptId":"u41"},
    "fe70887cb0534a7f93bdbec04e0aede4":{
      "scriptId":"u42"},
    "54c6e8e17c12420e9f46ef1e1daefd55":{
      "scriptId":"u43"},
    "862f0a77fad74ee9ac243c69829f61e6":{
      "scriptId":"u44"},
    "51c4e543262b478899e7de36badc8836":{
      "scriptId":"u45"},
    "6a9eeea3af0a435ab9c5fc986579783c":{
      "scriptId":"u46"},
    "dcadebceedcd4422832cd8c305b2ed7f":{
      "scriptId":"u47"},
    "ed8b9fb1f79647008e1eef010d43ee13":{
      "scriptId":"u48"},
    "61c87e2ae4fc4b6f81d2884af594a08e":{
      "scriptId":"u49"},
    "74e6454d9d7146f785b0bec6c7f94c8c":{
      "scriptId":"u50"},
    "939c6597e5654177be1d1afe16638c87":{
      "scriptId":"u51"},
    "35fe87e387b546cdadc4bc6d0446831f":{
      "scriptId":"u52"},
    "a8a398a3ab4044f9b2d01879c5966146":{
      "scriptId":"u53"},
    "a8f02629de7e475aba23854d4a26415a":{
      "scriptId":"u54"},
    "cea7953ffa01474396e123379f80d104":{
      "scriptId":"u55"},
    "970445342fb24d17856442dcae0caf4d":{
      "scriptId":"u56"},
    "c4e0172285b44e8da71e780ff0e8ce98":{
      "scriptId":"u57"},
    "0792accdec4c42ceb94f758b48bfcfea":{
      "scriptId":"u58"},
    "10e6488250654fc386c58af8943b7f52":{
      "scriptId":"u59"},
    "03dc5629866b4ddabe27adf86b964e92":{
      "scriptId":"u60"},
    "7be5488a8c1448caba884fb4fb74d12a":{
      "scriptId":"u61"},
    "f5b197002c174e48ac26cd79d3280de9":{
      "scriptId":"u62"},
    "54076d6aa045449fbaaf077a3e2b5c69":{
      "scriptId":"u63"},
    "f13acc830d7f482c9ea6c4f423b80d2a":{
      "scriptId":"u64"},
    "662c5f237365426fae0e21031505d5c5":{
      "scriptId":"u65"},
    "451fba689ceb4916a4b23a20a74fb6f2":{
      "scriptId":"u66"},
    "3d521cc5dbda400ab1c054743b5d370f":{
      "scriptId":"u67"},
    "57741645811f4fbc9e9ac3110be6ec82":{
      "scriptId":"u68"},
    "f6d774d5ac9843dab89f5ffb3aeb6fcd":{
      "scriptId":"u69"},
    "c9fbeeceda814c9b9ca8b0be239523fe":{
      "scriptId":"u70"},
    "177f09ac5b2b46aeb1800a8bb5fb7aa3":{
      "scriptId":"u71"},
    "bdf054af6cc840cdb068fd30fa219a0d":{
      "scriptId":"u72"},
    "8fecd369697e4f27b99c80e5d490f4f3":{
      "scriptId":"u73"},
    "96b4b4aebc8b4064be3f537313073017":{
      "scriptId":"u74"},
    "263d93d0f87043e4bb47b1b5a0bd2f4c":{
      "scriptId":"u75"},
    "5a911455f9d94195bd37f9e17924713a":{
      "scriptId":"u76"},
    "3fe6a76684b74676aada571a9c8ce4dc":{
      "scriptId":"u77"},
    "e7baa904ffaa428ab940374820431e1e":{
      "scriptId":"u78"},
    "5fcfd48f27474224bade4b8028f6da66":{
      "scriptId":"u79"},
    "25834c6a76cf4824b1cdb441a69f4108":{
      "scriptId":"u80"},
    "7fd4406674284655b8ca6eaa1c08c0bb":{
      "scriptId":"u81"},
    "cf2623a1c1ad4a1daadb18995d61e249":{
      "scriptId":"u82"},
    "f8d4e75daa4649778692e6e6e66173d7":{
      "scriptId":"u83"},
    "7af408ad897b4d78afd5d532315a4dbe":{
      "scriptId":"u84"},
    "ebc88a85443d43c09dbd3132dc4a0b94":{
      "scriptId":"u85"},
    "74f03c9a0d55467fa8b7c9e2f2848d0b":{
      "scriptId":"u86"},
    "ef12a5957ecb4176b49af1fd28a6a9bc":{
      "scriptId":"u87"},
    "7437b2b374fd449694b609a642a53659":{
      "scriptId":"u88"},
    "a6c67cbdd38a42eca68a52d45f033372":{
      "scriptId":"u89"},
    "7e25dfc17f1a483f816fb123f5443300":{
      "scriptId":"u90"},
    "5532265142cd429781d36ffc1905a907":{
      "scriptId":"u91"},
    "e3d2903226104cce92ff4107b867c8b2":{
      "scriptId":"u92"},
    "a1dff567ec6249b5b1fd74f2e9c07a99":{
      "scriptId":"u93"},
    "c7d8c8056b6a407db15e088ab63670fa":{
      "scriptId":"u94"},
    "038de08a4d36473087056187c7622140":{
      "scriptId":"u95"},
    "89b6bc693c9341cb93a2dd0a4cb59c2d":{
      "scriptId":"u96"},
    "d5728866a1364b4d977ca29c3f0d76c5":{
      "scriptId":"u97"},
    "77cfce4bbce14da880727983f628bb8d":{
      "scriptId":"u98"},
    "33682b4ed2944f1d96a2737afbab732b":{
      "scriptId":"u99"},
    "eb7b10a51dbe455b96dc3fa37e24dd2c":{
      "scriptId":"u100"},
    "6fa2e512e6a04b27b43b1678b6d981f2":{
      "scriptId":"u101"},
    "0b662492c60b4792b6f1ac09575de322":{
      "scriptId":"u102"},
    "eea71ba11c654b6290ec63131fbf3be5":{
      "scriptId":"u103"},
    "a5132133fd604b50ba666cd4daeea87f":{
      "scriptId":"u104"},
    "66e079fa8cb34fa6b2b7091c21e84d74":{
      "scriptId":"u105"},
    "5be36865fd3b4ca58fe6202f12a41588":{
      "scriptId":"u106"},
    "42657cb821e4467396b6115a85d493a4":{
      "scriptId":"u107"},
    "b0922ad811b6497f8c7aef93058dff74":{
      "scriptId":"u108"},
    "5340c3b8ef90418bbfab5b1f730f4aec":{
      "scriptId":"u109"},
    "258c2b8f181941eb9ca5b4497fc7f9f6":{
      "scriptId":"u110"},
    "678e319ed5aa47c2a092d84d141c903e":{
      "scriptId":"u111"},
    "1feb9bedd73447a4833715b55fa7280a":{
      "scriptId":"u112"},
    "3f862f7babed4e62b35ff36a7ba27390":{
      "scriptId":"u113"},
    "c84cf4b4882e4e0da83b8f2f303ec4e8":{
      "scriptId":"u114"},
    "d45dd129b3674ea99ea502d112dc48a6":{
      "scriptId":"u115"},
    "4c45729fc37b411f94a9df2a9016010e":{
      "scriptId":"u116"},
    "56e88fdf87ad4e0b8923791224c84a26":{
      "scriptId":"u117"},
    "afc8804854da4ecda149ef7bb31a3942":{
      "scriptId":"u118"},
    "57c3dfc386e94b4c89779655a5fb3e77":{
      "scriptId":"u119"},
    "cbbe23de9cbb479c83ac69b91343938f":{
      "scriptId":"u120"}}});