$axure.loadCurrentPage({
  "url":"充值.html",
  "generationDate":new Date(1494572339315.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"66b77aabf2604fcc9a52993181cf084e",
    "type":"Axure:Page",
    "name":"充值",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4d4e8a65ddfc4c3ca887c479f389c084",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":770},
            "size":{
              "width":964,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55ce433fc4a94f918f35d7316913141d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":770},
                "size":{
                  "width":964,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/备课/u131.png"}},
{
          "id":"270fcdc5f8294e8ea0fa2196213eabbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF336666,
              "opacity":1},
            "location":{
              "x":68,
              "y":783},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dcc0f3687724ad996d11c215bddb520",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF336666,
                  "opacity":1},
                "location":{
                  "x":68,
                  "y":783},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c1a1a4ce5a545dfbb2c099f6224fc8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":980,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d6946d585ee45e893ca802bcac1a1ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":980,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u4.png"}},
{
          "id":"ecf17719640f414abfc784226ca649cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":16,
              "y":15},
            "size":{
              "width":39,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a97378d032f4cdd835bdbf8877f10ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":15},
                "size":{
                  "width":39,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9b9b373ae654700b0b59c05ddfff71d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":72,
              "y":18},
            "size":{
              "width":55,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad4cdc27675f4d7093218e75fdf2e0f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":72,
                  "y":18},
                "size":{
                  "width":55,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a96069785d09480e9c91e5f8cdc1aeaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":779,
              "y":15},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84bcc73304b14bddb009e47a97513398",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":779,
                  "y":15},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"101cc5433a8f4d99b6b88b3fef2204af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":87},
            "size":{
              "width":930,
              "height":483},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b17759ca55a46d6870b5120afbeaf7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":87},
                "size":{
                  "width":930,
                  "height":483},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u12.png"}},
{
          "id":"5a23e58ab274498cae1d4927f03c691d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF515151,
              "opacity":1},
            "location":{
              "x":104,
              "y":122},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eff26ce5653c477390d471d89ad013f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "location":{
                  "x":104,
                  "y":122},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43c0051383c14c2ca1244beaa5d97eba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF515151,
              "opacity":1},
            "location":{
              "x":195,
              "y":130},
            "size":{
              "width":222,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0776ddc87c6646a19ce072de20793bd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "location":{
                  "x":195,
                  "y":130},
                "size":{
                  "width":222,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6c7d7bbd7084ef187860fb52f3c1f39",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":160},
            "size":{
              "width":760,
              "height":196},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"886427beed064dd99967e2a53b5bd8e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":160},
                "size":{
                  "width":760,
                  "height":196},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u18.png"}},
{
          "id":"cbb6bfdfca2749689632c59234f77914",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF515151,
              "opacity":1},
            "location":{
              "x":138,
              "y":180},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e269af2a63dd48309cbdf19d5a87e0e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":180},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"47a7513281b148d6bd1d122aa8b5d0b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":175},
            "size":{
              "width":225,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92bdaaa8ce9f436e8dd19c3f91fe12cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":205,
                  "y":175},
                "size":{
                  "width":225,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值/u22.png"}},
{
          "id":"5a63ff51f8de424189d47e054f96fd32",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":215,
              "y":177},
            "size":{
              "width":202,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入您要充值的数量"},
{
          "id":"a11bee5b4f7949d6b2ae46cf1af188b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "location":{
              "x":444,
              "y":181},
            "size":{
              "width":137,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d867f8dedd59467eb13a1da1cb5c5ffb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "location":{
                  "x":444,
                  "y":181},
                "size":{
                  "width":137,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7495c6cf27294ae68d8c27e8a17c799f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF515151,
              "opacity":1},
            "location":{
              "x":138,
              "y":217},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e31182d1f57041999b1b22bdfb338c08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":217},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97d2a9dfe3b641a49495d98ca68ae087",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "location":{
              "x":229,
              "y":217},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddfac693ebbe4a6eadc28f3a52e2f79d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "location":{
                  "x":229,
                  "y":217},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00068e5a04e94504a036206ed51c7822",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "location":{
              "x":423,
              "y":284},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aafcc0808777413e8e903ed82b917021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "location":{
                  "x":423,
                  "y":284},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 chongzhiDIV",
                      "objectsToFades":[{
                          "objectPath":["707278490d794c688f9e08879d062497"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/充值/u31.png"}},
{
          "id":"200b6a643532410dbeaf2aa55e30429d",
          "label":"1",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":110,
              "y":366},
            "size":{
              "width":672,
              "height":194},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"d22f5504a06d4a2eaf4d26ae17a926a4",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e1a5d02a09094766a417a9128604b9b4",
                  "label":"",
                  "parentDynamicPanel":"200b6a643532410dbeaf2aa55e30429d",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF515151,
                      "opacity":1},
                    "size":{
                      "width":81,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"58f187baebfd487e9da7f95403ce24f8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"200b6a643532410dbeaf2aa55e30429d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF515151,
                          "opacity":1},
                        "size":{
                          "width":81,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"740221a70a09452b81a16cc0c9273d59",
                  "label":"",
                  "parentDynamicPanel":"200b6a643532410dbeaf2aa55e30429d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF797979,
                      "opacity":1},
                    "location":{
                      "x":55,
                      "y":41},
                    "size":{
                      "width":617,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1bc932fe72f840a9862fead69354c9e6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"200b6a643532410dbeaf2aa55e30429d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF797979,
                          "opacity":1},
                        "location":{
                          "x":55,
                          "y":41},
                        "size":{
                          "width":617,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5617c5f23937412fb6f18f8e3082404b",
                  "label":"",
                  "parentDynamicPanel":"200b6a643532410dbeaf2aa55e30429d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF797979,
                      "opacity":1},
                    "location":{
                      "x":55,
                      "y":67},
                    "size":{
                      "width":603,
                      "height":44}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"427c5544c67c4d84b16916c96a898863",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"200b6a643532410dbeaf2aa55e30429d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF797979,
                          "opacity":1},
                        "location":{
                          "x":55,
                          "y":67},
                        "size":{
                          "width":603,
                          "height":44}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"34cba96488324ca0b876daf622342312",
                  "label":"",
                  "parentDynamicPanel":"200b6a643532410dbeaf2aa55e30429d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":55,
                      "y":121},
                    "size":{
                      "width":244,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aed774c539e646209e4e4b42eaae7cd4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"200b6a643532410dbeaf2aa55e30429d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":55,
                          "y":121},
                        "size":{
                          "width":244,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"78e9e3238c0044349207f4dffd4fe307",
                  "label":"",
                  "parentDynamicPanel":"200b6a643532410dbeaf2aa55e30429d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFA1A1A1,
                      "opacity":1},
                    "location":{
                      "x":55,
                      "y":153},
                    "size":{
                      "width":161,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"37e40cbd65074da4b92da988a4a0767f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"200b6a643532410dbeaf2aa55e30429d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFA1A1A1,
                          "opacity":1},
                        "location":{
                          "x":55,
                          "y":153},
                        "size":{
                          "width":161,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"707278490d794c688f9e08879d062497",
          "label":"chongzhiDIV",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":288,
              "y":160},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"a161ce9333954ec9a73ac17633d15738",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d95fd184805040ee8fa1e851d9260fa6",
                  "label":"",
                  "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF949494,
                      "opacity":1},
                    "size":{
                      "width":414,
                      "height":212},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2eed59bc515c46c28d1fc60c034dc523",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF949494,
                          "opacity":1},
                        "size":{
                          "width":414,
                          "height":212},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/充值/u45.png"}},
{
                  "id":"6f3ddd1ace6549a5b28ffb9ca50acd50",
                  "label":"",
                  "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF949494,
                      "opacity":1},
                    "location":{
                      "x":21,
                      "y":36},
                    "size":{
                      "width":348,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5b26da33387448e5afdd30307db2f870",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF949494,
                          "opacity":1},
                        "location":{
                          "x":21,
                          "y":36},
                        "size":{
                          "width":348,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"86abdd5250bc49fb885654a50285461b",
                  "label":"",
                  "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF949494,
                      "opacity":1},
                    "location":{
                      "x":47,
                      "y":80},
                    "size":{
                      "width":46,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0e113489d62d495fa2c241bb814d5654",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF949494,
                          "opacity":1},
                        "location":{
                          "x":47,
                          "y":80},
                        "size":{
                          "width":46,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5b57e218be824fafb46d4e636dc6a907",
                  "label":"",
                  "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":103,
                      "y":73},
                    "size":{
                      "width":101,
                      "height":33},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"74644f2ea4cb4db9b27ed6be45965a35",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":103,
                          "y":73},
                        "size":{
                          "width":101,
                          "height":33},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/充值/u51.png"}},
{
                  "id":"5faa6d30f6d34106a6a018c4a220a419",
                  "label":"",
                  "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":107,
                      "y":77},
                    "size":{
                      "width":87,
                      "height":26}},
                  "adaptiveStyles":{
}},
{
                  "id":"3af93da7cc224810ac5daefe3e52e216",
                  "label":"",
                  "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "location":{
                      "x":214,
                      "y":73},
                    "size":{
                      "width":101,
                      "height":33},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"182bcaaac47941848da901eac0eec71b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "location":{
                          "x":214,
                          "y":73},
                        "size":{
                          "width":101,
                          "height":33},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/充值/u54.png"}},
{
                  "id":"438d810dc03a48b7837ed30261d93d37",
                  "label":"",
                  "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF949494,
                      "opacity":1},
                    "location":{
                      "x":88,
                      "y":156},
                    "size":{
                      "width":59,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"12636813b8e6438b8b3de3c855433523",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF949494,
                          "opacity":1},
                        "location":{
                          "x":88,
                          "y":156},
                        "size":{
                          "width":59,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 chongzhiDIV to 状态2",
                              "panelsToStates":[{
                                  "panelPath":["707278490d794c688f9e08879d062497"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"wait",
                              "description":"等待2000毫秒",
                              "waitTime":2000},
{
                              "action":"fadeWidget",
                              "description":"隐藏 chongzhiDIV",
                              "objectsToFades":[{
                                  "objectPath":["707278490d794c688f9e08879d062497"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示 1",
                              "objectsToFades":[{
                                  "objectPath":["200b6a643532410dbeaf2aa55e30429d"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"setPanelState",
                              "description":"设置 chongzhiDIV to 状态1",
                              "panelsToStates":[{
                                  "panelPath":["707278490d794c688f9e08879d062497"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/充值/u56.png"}},
{
                  "id":"880baf309d834730a507923e4e19dd75",
                  "label":"",
                  "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF949494,
                      "opacity":1},
                    "location":{
                      "x":265,
                      "y":156},
                    "size":{
                      "width":59,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8f319212cdd44de1aa4ebcbd587e1e4a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF949494,
                          "opacity":1},
                        "location":{
                          "x":265,
                          "y":156},
                        "size":{
                          "width":59,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 chongzhiDIV",
                              "objectsToFades":[{
                                  "objectPath":["707278490d794c688f9e08879d062497"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/充值/u56.png"}}]},
{
              "id":"2e6aedfc8d1244dc9455bd04f254ae52",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7c34c69bb7d74657b9f5fe838fddb9e3",
                  "label":"",
                  "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF949494,
                      "opacity":1},
                    "size":{
                      "width":414,
                      "height":212},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d975e6417f4544cbaf8506a9d19c3b11",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF949494,
                          "opacity":1},
                        "size":{
                          "width":414,
                          "height":212},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFE4E4E4}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/充值/u45.png"}},
{
                  "id":"9796861597d34828a7a0e3fc5e026915",
                  "label":"",
                  "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"15px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF949494,
                      "opacity":1},
                    "location":{
                      "x":86,
                      "y":83},
                    "size":{
                      "width":241,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b870d2da1b7d4ad99d938eab468050b7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"707278490d794c688f9e08879d062497",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"15px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF949494,
                          "opacity":1},
                        "location":{
                          "x":86,
                          "y":83},
                        "size":{
                          "width":241,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"6b1cbd6c3f2340f891b5e130085b044d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3300FF,
              "opacity":1},
            "location":{
              "x":988,
              "y":160},
            "size":{
              "width":205,
              "height":165}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58c40be1e1d441ecad0362efc3bca7a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF,
                  "opacity":1},
                "location":{
                  "x":988,
                  "y":160},
                "size":{
                  "width":205,
                  "height":165}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4d4e8a65ddfc4c3ca887c479f389c084":{
      "scriptId":"u0"},
    "55ce433fc4a94f918f35d7316913141d":{
      "scriptId":"u1"},
    "270fcdc5f8294e8ea0fa2196213eabbf":{
      "scriptId":"u2"},
    "6dcc0f3687724ad996d11c215bddb520":{
      "scriptId":"u3"},
    "0c1a1a4ce5a545dfbb2c099f6224fc8b":{
      "scriptId":"u4"},
    "2d6946d585ee45e893ca802bcac1a1ef":{
      "scriptId":"u5"},
    "ecf17719640f414abfc784226ca649cd":{
      "scriptId":"u6"},
    "9a97378d032f4cdd835bdbf8877f10ba":{
      "scriptId":"u7"},
    "d9b9b373ae654700b0b59c05ddfff71d":{
      "scriptId":"u8"},
    "ad4cdc27675f4d7093218e75fdf2e0f7":{
      "scriptId":"u9"},
    "a96069785d09480e9c91e5f8cdc1aeaa":{
      "scriptId":"u10"},
    "84bcc73304b14bddb009e47a97513398":{
      "scriptId":"u11"},
    "101cc5433a8f4d99b6b88b3fef2204af":{
      "scriptId":"u12"},
    "4b17759ca55a46d6870b5120afbeaf7e":{
      "scriptId":"u13"},
    "5a23e58ab274498cae1d4927f03c691d":{
      "scriptId":"u14"},
    "eff26ce5653c477390d471d89ad013f1":{
      "scriptId":"u15"},
    "43c0051383c14c2ca1244beaa5d97eba":{
      "scriptId":"u16"},
    "0776ddc87c6646a19ce072de20793bd3":{
      "scriptId":"u17"},
    "b6c7d7bbd7084ef187860fb52f3c1f39":{
      "scriptId":"u18"},
    "886427beed064dd99967e2a53b5bd8e1":{
      "scriptId":"u19"},
    "cbb6bfdfca2749689632c59234f77914":{
      "scriptId":"u20"},
    "e269af2a63dd48309cbdf19d5a87e0e5":{
      "scriptId":"u21"},
    "47a7513281b148d6bd1d122aa8b5d0b6":{
      "scriptId":"u22"},
    "92bdaaa8ce9f436e8dd19c3f91fe12cd":{
      "scriptId":"u23"},
    "5a63ff51f8de424189d47e054f96fd32":{
      "scriptId":"u24"},
    "a11bee5b4f7949d6b2ae46cf1af188b6":{
      "scriptId":"u25"},
    "d867f8dedd59467eb13a1da1cb5c5ffb":{
      "scriptId":"u26"},
    "7495c6cf27294ae68d8c27e8a17c799f":{
      "scriptId":"u27"},
    "e31182d1f57041999b1b22bdfb338c08":{
      "scriptId":"u28"},
    "97d2a9dfe3b641a49495d98ca68ae087":{
      "scriptId":"u29"},
    "ddfac693ebbe4a6eadc28f3a52e2f79d":{
      "scriptId":"u30"},
    "00068e5a04e94504a036206ed51c7822":{
      "scriptId":"u31"},
    "aafcc0808777413e8e903ed82b917021":{
      "scriptId":"u32"},
    "200b6a643532410dbeaf2aa55e30429d":{
      "scriptId":"u33"},
    "e1a5d02a09094766a417a9128604b9b4":{
      "scriptId":"u34"},
    "58f187baebfd487e9da7f95403ce24f8":{
      "scriptId":"u35"},
    "740221a70a09452b81a16cc0c9273d59":{
      "scriptId":"u36"},
    "1bc932fe72f840a9862fead69354c9e6":{
      "scriptId":"u37"},
    "5617c5f23937412fb6f18f8e3082404b":{
      "scriptId":"u38"},
    "427c5544c67c4d84b16916c96a898863":{
      "scriptId":"u39"},
    "34cba96488324ca0b876daf622342312":{
      "scriptId":"u40"},
    "aed774c539e646209e4e4b42eaae7cd4":{
      "scriptId":"u41"},
    "78e9e3238c0044349207f4dffd4fe307":{
      "scriptId":"u42"},
    "37e40cbd65074da4b92da988a4a0767f":{
      "scriptId":"u43"},
    "707278490d794c688f9e08879d062497":{
      "scriptId":"u44"},
    "d95fd184805040ee8fa1e851d9260fa6":{
      "scriptId":"u45"},
    "2eed59bc515c46c28d1fc60c034dc523":{
      "scriptId":"u46"},
    "6f3ddd1ace6549a5b28ffb9ca50acd50":{
      "scriptId":"u47"},
    "5b26da33387448e5afdd30307db2f870":{
      "scriptId":"u48"},
    "86abdd5250bc49fb885654a50285461b":{
      "scriptId":"u49"},
    "0e113489d62d495fa2c241bb814d5654":{
      "scriptId":"u50"},
    "5b57e218be824fafb46d4e636dc6a907":{
      "scriptId":"u51"},
    "74644f2ea4cb4db9b27ed6be45965a35":{
      "scriptId":"u52"},
    "5faa6d30f6d34106a6a018c4a220a419":{
      "scriptId":"u53"},
    "3af93da7cc224810ac5daefe3e52e216":{
      "scriptId":"u54"},
    "182bcaaac47941848da901eac0eec71b":{
      "scriptId":"u55"},
    "438d810dc03a48b7837ed30261d93d37":{
      "scriptId":"u56"},
    "12636813b8e6438b8b3de3c855433523":{
      "scriptId":"u57"},
    "880baf309d834730a507923e4e19dd75":{
      "scriptId":"u58"},
    "8f319212cdd44de1aa4ebcbd587e1e4a":{
      "scriptId":"u59"},
    "7c34c69bb7d74657b9f5fe838fddb9e3":{
      "scriptId":"u60"},
    "d975e6417f4544cbaf8506a9d19c3b11":{
      "scriptId":"u61"},
    "9796861597d34828a7a0e3fc5e026915":{
      "scriptId":"u62"},
    "b870d2da1b7d4ad99d938eab468050b7":{
      "scriptId":"u63"},
    "6b1cbd6c3f2340f891b5e130085b044d":{
      "scriptId":"u64"},
    "58c40be1e1d441ecad0362efc3bca7a5":{
      "scriptId":"u65"}}});