$axure.loadCurrentPage({
  "url":"广告详情.html",
  "generationDate":new Date(1494572349337.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"32ed599c052a4b14913e1f2402a50cf1",
    "type":"Axure:Page",
    "name":"广告详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fcda69f61bd643ceac0c94f863949398",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":18,
              "y":117},
            "size":{
              "width":1102,
              "height":402},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92cf2e0be3a245d68c0e7dab0bbc8377",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":18,
                  "y":117},
                "size":{
                  "width":1102,
                  "height":402},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 广告详情",
                      "target":{
                        "targetType":"page",
                        "url":"广告详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/广告详情/u0.png"}},
{
          "id":"fcf3590db48344008ac963378d3a1a44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "size":{
              "width":1150,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c7c31a95cbb4a4cb7f2ce9184c83125",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "size":{
                  "width":1150,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"2c92beb649ce4f33a69ecb505aa209b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF515151,
              "opacity":1},
            "location":{
              "x":20,
              "y":7},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77dbf363f1ee40469fc5de6b80e3b0c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":7},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0d8f4f58a494b3f99a156d0def87540",
          "label":"login",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1}}},
            "location":{
              "x":730,
              "y":7},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdd776689e8d4f2191c526da2fe3630d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333,
                      "opacity":1}}},
                "location":{
                  "x":730,
                  "y":7},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["c0d8f4f58a494b3f99a156d0def87540"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["c0d8f4f58a494b3f99a156d0def87540"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif"}},
{
          "id":"cbbd8be674e242ae9413c5a0130ae5d8",
          "label":"2weima",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":1024,
              "y":29},
            "size":{
              "width":126,
              "height":100},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a167bc19fc74798af2e662c8e8bcd25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":1024,
                  "y":29},
                "size":{
                  "width":126,
                  "height":100},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/2weima_u10.png"}},
{
          "id":"9b40f4222f1746a1be318778e2d4fd94",
          "label":"login",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1}}},
            "location":{
              "x":950,
              "y":7},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deaf75c7d86b46989c0778877819c27d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333,
                      "opacity":1}}},
                "location":{
                  "x":950,
                  "y":7},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["9b40f4222f1746a1be318778e2d4fd94"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["9b40f4222f1746a1be318778e2d4fd94"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif"}},
{
          "id":"2fb57a8269ae4b5c9adb215af2fb6d3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":34,
              "y":52},
            "size":{
              "width":60,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddaff7deb8834c009d0b4962e6fbd76e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":34,
                  "y":52},
                "size":{
                  "width":60,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19cda780e23542f39c3c967159b7403b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":64},
            "size":{
              "width":79,
              "height":16},
            "rotation":"353",
            "textRotation":"353"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb182445a10a461aa4a172c2eece8cca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":64},
                "size":{
                  "width":79,
                  "height":16},
                "rotation":"353",
                "textRotation":"353"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"612a635c3d204842a9f7df64ae22d423",
          "label":"kefu",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1}}},
            "location":{
              "x":867,
              "y":7},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67ac66dbc8de40dbabe911f7166b8d7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333,
                      "opacity":1}}},
                "location":{
                  "x":867,
                  "y":7},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 kefu = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["612a635c3d204842a9f7df64ae22d423"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"fadeWidget",
                      "description":"显示 qq 弹出效果",
                      "objectsToFades":[{
                          "objectPath":["ff75288433bb40938ec6a69e660eaf76"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"flyout"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 kefu = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["612a635c3d204842a9f7df64ae22d423"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif"}},
{
          "id":"ff75288433bb40938ec6a69e660eaf76",
          "label":"qq",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":867,
              "y":29},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"c37cdda3054d4df3bb9333ff1412a125",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6709eb89ebbd4e329478aee877c883e5",
                  "label":"",
                  "parentDynamicPanel":"ff75288433bb40938ec6a69e660eaf76",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":100},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"877249c81fac4b49a446f1d1dca4d07c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff75288433bb40938ec6a69e660eaf76",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":100},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u21.png"}},
{
                  "id":"e27e3ee5eaf04e19a7ce601a7f96cffd",
                  "label":"",
                  "parentDynamicPanel":"ff75288433bb40938ec6a69e660eaf76",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF868686,
                      "opacity":1},
                    "location":{
                      "x":23,
                      "y":11},
                    "size":{
                      "width":99,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bee2b959670b49548a845b48e18b83df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff75288433bb40938ec6a69e660eaf76",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF868686,
                          "opacity":1},
                        "location":{
                          "x":23,
                          "y":11},
                        "size":{
                          "width":99,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"424b160e89d348f1b9162ff698c441cc",
                  "label":"",
                  "parentDynamicPanel":"ff75288433bb40938ec6a69e660eaf76",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF868686,
                      "opacity":1},
                    "location":{
                      "x":23,
                      "y":37},
                    "size":{
                      "width":99,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"045771e9f8d846a2ba1a18d82614a910",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff75288433bb40938ec6a69e660eaf76",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF868686,
                          "opacity":1},
                        "location":{
                          "x":23,
                          "y":37},
                        "size":{
                          "width":99,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3a1c4b75d2d34209a98f8c25ec58dd4c",
                  "label":"",
                  "parentDynamicPanel":"ff75288433bb40938ec6a69e660eaf76",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF868686,
                      "opacity":1},
                    "location":{
                      "x":23,
                      "y":63},
                    "size":{
                      "width":99,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c893e366d6b54f9facb06229a6934b97",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff75288433bb40938ec6a69e660eaf76",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF868686,
                          "opacity":1},
                        "location":{
                          "x":23,
                          "y":63},
                        "size":{
                          "width":99,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"d8b2144067f1436a995dac4c72cf15db",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":230,
              "y":78},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b171649f9ab4929bbc09c790762b846",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":78},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ea02e44504a447cb099fa3cd066e336",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":292,
              "y":78},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91489d3e5a174a9fa4edaac78cfad3f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":292,
                  "y":78},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 金八力课程",
                      "target":{
                        "targetType":"page",
                        "url":"金八力课程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ecd2ff56afc148dd995ee9d532b8962f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":399,
              "y":78},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d507c530ac4c4dc5b6f2e9e5ee875a73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":399,
                  "y":78},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 项目优势",
                      "target":{
                        "targetType":"page",
                        "url":"项目优势.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b17494af2bfc4e62810ec5681fac9f51",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":590,
              "y":78},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0cc71b869ee4ff9be729aa6f6790ddf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":590,
                  "y":78},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 校区分布",
                      "target":{
                        "targetType":"page",
                        "url":"校区分布.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0a30b4b72db4f48b440218cba8c0e07",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":497,
              "y":78},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0fd6343a95c4475a0eb6a573dea96de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":497,
                  "y":78},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 加盟服务",
                      "target":{
                        "targetType":"page",
                        "url":"加盟服务.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fc430f936e3444b936718061bde9740",
          "label":"login",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1}}},
            "location":{
              "x":795,
              "y":7},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45596250454e4f79aa7928d120681600",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333,
                      "opacity":1}}},
                "location":{
                  "x":795,
                  "y":7},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 注册",
                      "target":{
                        "targetType":"page",
                        "url":"注册.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["1fc430f936e3444b936718061bde9740"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["1fc430f936e3444b936718061bde9740"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif"}},
{
          "id":"d589b0b0ed314a46b33f94385ca2f439",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":0,
              "y":2870},
            "size":{
              "width":1250,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53cee6a69e9e455889dd847bcdf223e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":0,
                  "y":2870},
                "size":{
                  "width":1250,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u69.png"}},
{
          "id":"f7df6c1c78354908823480ad8f5b8cb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":124,
              "y":2910},
            "size":{
              "width":53,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d4714a66b1a415093d78ff2167c294d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":124,
                  "y":2910},
                "size":{
                  "width":53,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13572dd0f570477dba484657690381aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":230,
              "y":2916},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b063b720db7547b5bd580818f73bbb56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":2916},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85a13215c1834e7f909cb864f1013bc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":529},
            "size":{
              "width":1092,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32a12ddb7bce4ce5a5e42f7bb9279bef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":529},
                "size":{
                  "width":1092,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0bca8f3adfe4250b57eaaaadad81a51",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":23,
              "y":587},
            "size":{
              "width":1102,
              "height":402},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6366004152a3440a84a8273c2443cbd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":587},
                "size":{
                  "width":1102,
                  "height":402},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 广告详情",
                      "target":{
                        "targetType":"page",
                        "url":"广告详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/广告详情/u0.png"}},
{
          "id":"3d3b93cdd207430bb6af0f159b86ab6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":999},
            "size":{
              "width":1092,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdfc0bd6981445b6ad869258a4ece8e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":23,
                  "y":999},
                "size":{
                  "width":1092,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcb8c7c9ff76430e95034a00215d6641",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":23,
              "y":1057},
            "size":{
              "width":1102,
              "height":402},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9070a277763448a9ac76edadcb91402",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":1057},
                "size":{
                  "width":1102,
                  "height":402},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 广告详情",
                      "target":{
                        "targetType":"page",
                        "url":"广告详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/广告详情/u0.png"}},
{
          "id":"5c0653acc4f649709625afd6a128b476",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":1469},
            "size":{
              "width":1092,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfcd2808b09d45c7954dec5508da16c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":23,
                  "y":1469},
                "size":{
                  "width":1092,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"277bbb61e0ae4c3eaa72aa04c33b0622",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":0,
              "y":1550},
            "size":{
              "width":1150,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78c664cd7cd74f1f8eeeaedb4ff72cbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":0,
                  "y":1550},
                "size":{
                  "width":1150,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/广告详情/u55.png"}},
{
          "id":"8ad0ece56f7d43c397dafb2d518e27f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":54,
              "y":1590},
            "size":{
              "width":53,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"039b02ea97f64f029e45301d09c029dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":54,
                  "y":1590},
                "size":{
                  "width":53,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fffc3e48808438a886e4adba22aa6cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":160,
              "y":1596},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee0220e5a0b342e0b57180dde6ac58a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":160,
                  "y":1596},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "fcda69f61bd643ceac0c94f863949398":{
      "scriptId":"u0"},
    "92cf2e0be3a245d68c0e7dab0bbc8377":{
      "scriptId":"u1"},
    "fcf3590db48344008ac963378d3a1a44":{
      "scriptId":"u2"},
    "7c7c31a95cbb4a4cb7f2ce9184c83125":{
      "scriptId":"u3"},
    "2c92beb649ce4f33a69ecb505aa209b5":{
      "scriptId":"u4"},
    "77dbf363f1ee40469fc5de6b80e3b0c3":{
      "scriptId":"u5"},
    "c0d8f4f58a494b3f99a156d0def87540":{
      "scriptId":"u6"},
    "bdd776689e8d4f2191c526da2fe3630d":{
      "scriptId":"u7"},
    "cbbd8be674e242ae9413c5a0130ae5d8":{
      "scriptId":"u8"},
    "2a167bc19fc74798af2e662c8e8bcd25":{
      "scriptId":"u9"},
    "9b40f4222f1746a1be318778e2d4fd94":{
      "scriptId":"u10"},
    "deaf75c7d86b46989c0778877819c27d":{
      "scriptId":"u11"},
    "2fb57a8269ae4b5c9adb215af2fb6d3d":{
      "scriptId":"u12"},
    "ddaff7deb8834c009d0b4962e6fbd76e":{
      "scriptId":"u13"},
    "19cda780e23542f39c3c967159b7403b":{
      "scriptId":"u14"},
    "fb182445a10a461aa4a172c2eece8cca":{
      "scriptId":"u15"},
    "612a635c3d204842a9f7df64ae22d423":{
      "scriptId":"u16"},
    "67ac66dbc8de40dbabe911f7166b8d7a":{
      "scriptId":"u17"},
    "ff75288433bb40938ec6a69e660eaf76":{
      "scriptId":"u18"},
    "6709eb89ebbd4e329478aee877c883e5":{
      "scriptId":"u19"},
    "877249c81fac4b49a446f1d1dca4d07c":{
      "scriptId":"u20"},
    "e27e3ee5eaf04e19a7ce601a7f96cffd":{
      "scriptId":"u21"},
    "bee2b959670b49548a845b48e18b83df":{
      "scriptId":"u22"},
    "424b160e89d348f1b9162ff698c441cc":{
      "scriptId":"u23"},
    "045771e9f8d846a2ba1a18d82614a910":{
      "scriptId":"u24"},
    "3a1c4b75d2d34209a98f8c25ec58dd4c":{
      "scriptId":"u25"},
    "c893e366d6b54f9facb06229a6934b97":{
      "scriptId":"u26"},
    "d8b2144067f1436a995dac4c72cf15db":{
      "scriptId":"u27"},
    "2b171649f9ab4929bbc09c790762b846":{
      "scriptId":"u28"},
    "3ea02e44504a447cb099fa3cd066e336":{
      "scriptId":"u29"},
    "91489d3e5a174a9fa4edaac78cfad3f1":{
      "scriptId":"u30"},
    "ecd2ff56afc148dd995ee9d532b8962f":{
      "scriptId":"u31"},
    "d507c530ac4c4dc5b6f2e9e5ee875a73":{
      "scriptId":"u32"},
    "b17494af2bfc4e62810ec5681fac9f51":{
      "scriptId":"u33"},
    "d0cc71b869ee4ff9be729aa6f6790ddf":{
      "scriptId":"u34"},
    "d0a30b4b72db4f48b440218cba8c0e07":{
      "scriptId":"u35"},
    "d0fd6343a95c4475a0eb6a573dea96de":{
      "scriptId":"u36"},
    "1fc430f936e3444b936718061bde9740":{
      "scriptId":"u37"},
    "45596250454e4f79aa7928d120681600":{
      "scriptId":"u38"},
    "d589b0b0ed314a46b33f94385ca2f439":{
      "scriptId":"u39"},
    "53cee6a69e9e455889dd847bcdf223e9":{
      "scriptId":"u40"},
    "f7df6c1c78354908823480ad8f5b8cb7":{
      "scriptId":"u41"},
    "0d4714a66b1a415093d78ff2167c294d":{
      "scriptId":"u42"},
    "13572dd0f570477dba484657690381aa":{
      "scriptId":"u43"},
    "b063b720db7547b5bd580818f73bbb56":{
      "scriptId":"u44"},
    "85a13215c1834e7f909cb864f1013bc2":{
      "scriptId":"u45"},
    "32a12ddb7bce4ce5a5e42f7bb9279bef":{
      "scriptId":"u46"},
    "b0bca8f3adfe4250b57eaaaadad81a51":{
      "scriptId":"u47"},
    "6366004152a3440a84a8273c2443cbd9":{
      "scriptId":"u48"},
    "3d3b93cdd207430bb6af0f159b86ab6d":{
      "scriptId":"u49"},
    "cdfc0bd6981445b6ad869258a4ece8e8":{
      "scriptId":"u50"},
    "dcb8c7c9ff76430e95034a00215d6641":{
      "scriptId":"u51"},
    "a9070a277763448a9ac76edadcb91402":{
      "scriptId":"u52"},
    "5c0653acc4f649709625afd6a128b476":{
      "scriptId":"u53"},
    "cfcd2808b09d45c7954dec5508da16c1":{
      "scriptId":"u54"},
    "277bbb61e0ae4c3eaa72aa04c33b0622":{
      "scriptId":"u55"},
    "78c664cd7cd74f1f8eeeaedb4ff72cbb":{
      "scriptId":"u56"},
    "8ad0ece56f7d43c397dafb2d518e27f5":{
      "scriptId":"u57"},
    "039b02ea97f64f029e45301d09c029dd":{
      "scriptId":"u58"},
    "1fffc3e48808438a886e4adba22aa6cf":{
      "scriptId":"u59"},
    "ee0220e5a0b342e0b57180dde6ac58a3":{
      "scriptId":"u60"}}});