$axure.loadCurrentPage({
  "url":"教材赛选.html",
  "generationDate":new Date(1494572334036.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1bfe150600bc42cd97d5cf621f9c5b3e",
    "type":"Axure:Page",
    "name":"教材赛选",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d0050ce7ed9247e79286520c725b8105",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":1420},
            "size":{
              "width":964,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96d24d7f051b4c4f9b737bfb1a286a1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":1420},
                "size":{
                  "width":964,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/备课/u131.png"}},
{
          "id":"4f174d664e094ef091cbbfe7a03061cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF336666,
              "opacity":1},
            "location":{
              "x":78,
              "y":1433},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"785ab83c5b4543b999b597c5849268c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF336666,
                  "opacity":1},
                "location":{
                  "x":78,
                  "y":1433},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cff36d51e1a541a689a46020189a7b60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":1210,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0f601ad498847f6822d2e90c59168b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":1210,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材购买/u8.png"}},
{
          "id":"3e902c4926e64684892b4be983e1c5b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":27,
              "y":50},
            "size":{
              "width":53,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a83dee21500c4834b131415c819eb9ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":27,
                  "y":50},
                "size":{
                  "width":53,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c297c66c1d74a08900024ae2d22961e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":100,
              "y":70},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2849f56055b478897b3835f7211e303",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":70},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"91652af29458435f8ff5a8f8f37879cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":57},
            "size":{
              "width":340,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8733ca9a84c4a57a2728fff784387c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":57},
                "size":{
                  "width":340,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材购买/u14.png"}},
{
          "id":"1d8dc3f0e3924bf6a56ff65bc9e7c4ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3333},
            "location":{
              "x":720,
              "y":57},
            "size":{
              "width":72,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1119168a13f4349a7cefa1378786ef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3333},
                "location":{
                  "x":720,
                  "y":57},
                "size":{
                  "width":72,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材购买/u16.png"}},
{
          "id":"cb8d28a27e8549e5a464ba09e0ef4da2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":386,
              "y":59},
            "size":{
              "width":319,
              "height":30}},
          "adaptiveStyles":{
},
          "placeholderText":"金八力作文"},
{
          "id":"daf5cc445ace4ce1933b049e396bf19e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "size":{
              "width":1210,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15ed57adc9a1480692907c008d72edee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "size":{
                  "width":1210,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材购买/u19.png"}},
{
          "id":"0d6522a617564001848f4f022344c9c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":16,
              "y":7},
            "size":{
              "width":113,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4805ff6a0914156887a113076b3bb78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":7},
                "size":{
                  "width":113,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"769532decf0548f8996aa9b047b45798",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":1020,
              "y":7},
            "size":{
              "width":160,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70fa87df71714feeb6ffb2737602de30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":1020,
                  "y":7},
                "size":{
                  "width":160,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"864057007a6143388952892a28216365",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":170},
            "size":{
              "width":1210,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3366}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/教材购买/u25_line.png"}},
{
          "id":"50a976679daa4d908a3037aefc48d3d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":65,
              "y":144},
            "size":{
              "width":224,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c84c33ac9ab24015bc27b25066a82abb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":65,
                  "y":144},
                "size":{
                  "width":224,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材购买/u26.png"}},
{
          "id":"206f3b513bdc4b70bf027e2d7a85edea",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":327,
              "y":148},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cace90e73de4d97811caeb92d7e4387",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":327,
                  "y":148},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 教材购买",
                      "target":{
                        "targetType":"page",
                        "url":"教材购买.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"c78954c09990435d9d3e2c1f55ad2033",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3333,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":420,
              "y":148},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f60fce44e1d94797a275a2f16fb5beaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":420,
                  "y":148},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 教材赛选",
                      "target":{
                        "targetType":"page",
                        "url":"教材赛选.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"91b27d558dda463a8ce866e88f3ad058",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":505,
              "y":148},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0348cf72efd48f19d9e695de4a42996",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":505,
                  "y":148},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 教具",
                      "target":{
                        "targetType":"page",
                        "url":"教具.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"3487117f70ef41f398cb9ff767164460",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF797979,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":580,
              "y":148},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"532472836d8e4f78b05de43c691a8924",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF797979,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":580,
                  "y":148},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 物料",
                      "target":{
                        "targetType":"page",
                        "url":"物料.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"44df01c0a6c7470baae2c2e42a8694e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":200},
            "size":{
              "width":1130,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04ef75258c634f75b7584746f0915f69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":200},
                "size":{
                  "width":1130,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材赛选/u32.png"}},
{
          "id":"26b92e28fafa44828fe2609dab649b94",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":225},
            "size":{
              "width":1110,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/教材赛选/u34_line.png"}},
{
          "id":"20a95aa6d50a4823a1aa15c4e606bab6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":62,
              "y":207},
            "size":{
              "width":107,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a95c7f5b7a72442eb0ae0e428de71320",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":62,
                  "y":207},
                "size":{
                  "width":107,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d286f116b2645999f2bb95b4f9fe26b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1270,
              "y":200},
            "size":{
              "width":196,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"564c0173dfff4fdcb29164587303bd18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1270,
                  "y":200},
                "size":{
                  "width":196,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba01b8204ab94ea7b342f5730088e03f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":40,
              "y":231},
            "size":{
              "width":83,
              "height":69},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"468eb39ba86542b9b9875968fe06c962",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":40,
                  "y":231},
                "size":{
                  "width":83,
                  "height":69},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材赛选/u39.png"}},
{
          "id":"1229f145c65749f28b5e23b2a0550d76",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":299},
            "size":{
              "width":1130,
              "height":71},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"826f194c23514a278d62b35f044fafbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":299},
                "size":{
                  "width":1130,
                  "height":71},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材赛选/u41.png"}},
{
          "id":"b0acd3e0ec954eef9b1b6f8e27adb8a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":40,
              "y":300},
            "size":{
              "width":83,
              "height":69},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf50a85b76b345cc96e165887c0c29c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":40,
                  "y":300},
                "size":{
                  "width":83,
                  "height":69},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材赛选/u39.png"}},
{
          "id":"bba6ff4f18874f64b53e3a1d451508df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3366,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":150,
              "y":242},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e829d596655444cadae6c9e9d3e56d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":150,
                  "y":242},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"a5a4d329d0554807a64f17dad81ad475",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":203,
              "y":242},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e8c2b9db166420da6bab52168065b39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":203,
                  "y":242},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"ef6bac28446248799a8aca99ae149838",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":255,
              "y":242},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5172e2e76b742818e80a1e4a6f2987a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":255,
                  "y":242},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"eaceba5086ff4e50a72fbab0b623f5b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3366,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":150,
              "y":310},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a49f617d472247f6b4bb98fabf1c7a8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":150,
                  "y":310},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"6876ada9498342a1b45599e8fed09d8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":229,
              "y":310},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4485d828ba84ec1903b081ee88bcc49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":229,
                  "y":310},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"c282cbe6081149c59c21cd78421a8867",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":310,
              "y":310},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc5d5322df0043fe8c304a24b088835d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":310,
                  "y":310},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"4bbcae91fcc64881a2351321809ffffa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":316,
              "y":242},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e33131982f444d7bbc7a41f87aec441a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":316,
                  "y":242},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"a5084e78cfb648f2a114e6f7993d6e7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":403,
              "y":242},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad9b88ea3ad94a6991cedf45825679b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":403,
                  "y":242},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"ccf11a3f665748e48cfd5a7039b2cc0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":487,
              "y":242},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e36dc1f314a4ebbacede83a00cc6c17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":487,
                  "y":242},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"16dbeec4cdd34f0d84ea46577810ec49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1}}},
            "location":{
              "x":584,
              "y":242},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9d5109ddfd548458c7ef8f147d5d0cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3366,
                      "opacity":1}}},
                "location":{
                  "x":584,
                  "y":242},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"a813556a35bc48f2986ab32ae3d45d12",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1270,
              "y":258},
            "size":{
              "width":105,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"133b765aacf3411b927439d37a77fc73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1270,
                  "y":258},
                "size":{
                  "width":105,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b86ff282bff4e3190f961baae54db29",
          "label":"shukuang",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "selected":{
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}}},
            "location":{
              "x":40,
              "y":379},
            "size":{
              "width":233,
              "height":346},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6494974c632c40c2a7b73f980010e26f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "selected":{
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}}},
                "location":{
                  "x":40,
                  "y":379},
                "size":{
                  "width":233,
                  "height":346},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材购买/shukuang_u0.png",
            "selected~":"images/教材购买/shukuang_u0_selected.png"}},
{
          "id":"6bf92c1d44f7489bbab323dde19d35cc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":56,
              "y":380},
            "size":{
              "width":198,
              "height":196},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca80c67f23804b5db82445262b8a6832",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":56,
                  "y":380},
                "size":{
                  "width":198,
                  "height":196},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材购买/u40.png"}},
{
          "id":"3b3218b42891462889a1dce76bc7fad6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0033,
              "opacity":1},
            "location":{
              "x":55,
              "y":587},
            "size":{
              "width":71,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c59aa3299724328b8c542d4c7e45fea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0033,
                  "opacity":1},
                "location":{
                  "x":55,
                  "y":587},
                "size":{
                  "width":71,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e98ade3f03e4c80b6196ef091c32b77",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":52,
              "y":614},
            "size":{
              "width":205,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1bdcdacb42f4949b4b680f8716f67fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":52,
                  "y":614},
                "size":{
                  "width":205,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9c506c3e0004c15bc27937571464d2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":53,
              "y":641},
            "size":{
              "width":75,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeb430fcd2064295b70279488fbab75d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":53,
                  "y":641},
                "size":{
                  "width":75,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac5e4294972d4e4182bb43d23253528f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":54,
              "y":666},
            "size":{
              "width":99,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee018875ae2e4649bd9d6afc7bd2e2fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":54,
                  "y":666},
                "size":{
                  "width":99,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef9e0a7acdc84a29bd35596e2c45f386",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":379},
            "size":{
              "width":233,
              "height":346}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 教材详情",
                      "target":{
                        "targetType":"page",
                        "url":"教材详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 shukuang = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2b86ff282bff4e3190f961baae54db29"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 shukuang = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2b86ff282bff4e3190f961baae54db29"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true},
{
          "id":"608985327e314cfb988f7cad114893ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333}}},
            "location":{
              "x":52,
              "y":696},
            "size":{
              "width":69,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0548ecdd5ede4c8d9433c9f10988ed65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333,
                      "opacity":1},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333}}},
                "location":{
                  "x":52,
                  "y":696},
                "size":{
                  "width":69,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 shoop",
                      "objectsToFades":[{
                          "objectPath":["ad6a7761760b4ace9b9fd6965816b90a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"wait",
                      "description":"等待2000毫秒",
                      "waitTime":2000},
{
                      "action":"fadeWidget",
                      "description":"隐藏 shoop",
                      "objectsToFades":[{
                          "objectPath":["ad6a7761760b4ace9b9fd6965816b90a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/教材购买/u150.png",
            "mouseOver~":"images/教材购买/u150_mouseOver.png"}},
{
          "id":"5e5643ddb7ca4ed2988dc8a7e25beaef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333}}},
            "location":{
              "x":146,
              "y":696},
            "size":{
              "width":69,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6098bf822bb429190ccc7914ad3b70f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333,
                      "opacity":1},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333}}},
                "location":{
                  "x":146,
                  "y":696},
                "size":{
                  "width":69,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 立即购买订单",
                      "target":{
                        "targetType":"page",
                        "url":"立即购买订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/教材购买/u150.png",
            "mouseOver~":"images/教材购买/u150_mouseOver.png"}},
{
          "id":"ad6a7761760b4ace9b9fd6965816b90a",
          "label":"shoop",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":310,
              "y":485},
            "size":{
              "width":320,
              "height":75},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5e8e6a1692941d4905a0eb9f60a8ff4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":310,
                  "y":485},
                "size":{
                  "width":320,
                  "height":75},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材购买/shoop_u292.png"}},
{
          "id":"8b98665f6ffc4b7a91a95176367dbc17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":991,
              "y":46},
            "size":{
              "width":94,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86028af65611404a85deaab9035cac09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":991,
                  "y":46},
                "size":{
                  "width":94,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 购物车",
                      "target":{
                        "targetType":"page",
                        "url":"购物车.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/教材购买/u294.png"}},
{
          "id":"1dbf7018be3540a2ae166e2c9b5808a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":991,
              "y":86},
            "size":{
              "width":94,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3877b33355bb46a388946de2395ef9a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":991,
                  "y":86},
                "size":{
                  "width":94,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 我的订单",
                      "target":{
                        "targetType":"page",
                        "url":"我的订单.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/教材购买/u294.png"}},
{
          "id":"336d9e2c440248ada6e44ab752a502db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "location":{
              "x":984,
              "y":40},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3366},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a31c9ef36d34584bc26497015956767",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "location":{
                  "x":984,
                  "y":40},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/教材购买/u298.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d0050ce7ed9247e79286520c725b8105":{
      "scriptId":"u0"},
    "96d24d7f051b4c4f9b737bfb1a286a1e":{
      "scriptId":"u1"},
    "4f174d664e094ef091cbbfe7a03061cc":{
      "scriptId":"u2"},
    "785ab83c5b4543b999b597c5849268c1":{
      "scriptId":"u3"},
    "cff36d51e1a541a689a46020189a7b60":{
      "scriptId":"u4"},
    "d0f601ad498847f6822d2e90c59168b3":{
      "scriptId":"u5"},
    "3e902c4926e64684892b4be983e1c5b4":{
      "scriptId":"u6"},
    "a83dee21500c4834b131415c819eb9ce":{
      "scriptId":"u7"},
    "9c297c66c1d74a08900024ae2d22961e":{
      "scriptId":"u8"},
    "e2849f56055b478897b3835f7211e303":{
      "scriptId":"u9"},
    "91652af29458435f8ff5a8f8f37879cd":{
      "scriptId":"u10"},
    "d8733ca9a84c4a57a2728fff784387c8":{
      "scriptId":"u11"},
    "1d8dc3f0e3924bf6a56ff65bc9e7c4ca":{
      "scriptId":"u12"},
    "e1119168a13f4349a7cefa1378786ef6":{
      "scriptId":"u13"},
    "cb8d28a27e8549e5a464ba09e0ef4da2":{
      "scriptId":"u14"},
    "daf5cc445ace4ce1933b049e396bf19e":{
      "scriptId":"u15"},
    "15ed57adc9a1480692907c008d72edee":{
      "scriptId":"u16"},
    "0d6522a617564001848f4f022344c9c3":{
      "scriptId":"u17"},
    "d4805ff6a0914156887a113076b3bb78":{
      "scriptId":"u18"},
    "769532decf0548f8996aa9b047b45798":{
      "scriptId":"u19"},
    "70fa87df71714feeb6ffb2737602de30":{
      "scriptId":"u20"},
    "864057007a6143388952892a28216365":{
      "scriptId":"u21"},
    "50a976679daa4d908a3037aefc48d3d3":{
      "scriptId":"u22"},
    "c84c33ac9ab24015bc27b25066a82abb":{
      "scriptId":"u23"},
    "206f3b513bdc4b70bf027e2d7a85edea":{
      "scriptId":"u24"},
    "7cace90e73de4d97811caeb92d7e4387":{
      "scriptId":"u25"},
    "c78954c09990435d9d3e2c1f55ad2033":{
      "scriptId":"u26"},
    "f60fce44e1d94797a275a2f16fb5beaa":{
      "scriptId":"u27"},
    "91b27d558dda463a8ce866e88f3ad058":{
      "scriptId":"u28"},
    "b0348cf72efd48f19d9e695de4a42996":{
      "scriptId":"u29"},
    "3487117f70ef41f398cb9ff767164460":{
      "scriptId":"u30"},
    "532472836d8e4f78b05de43c691a8924":{
      "scriptId":"u31"},
    "44df01c0a6c7470baae2c2e42a8694e6":{
      "scriptId":"u32"},
    "04ef75258c634f75b7584746f0915f69":{
      "scriptId":"u33"},
    "26b92e28fafa44828fe2609dab649b94":{
      "scriptId":"u34"},
    "20a95aa6d50a4823a1aa15c4e606bab6":{
      "scriptId":"u35"},
    "a95c7f5b7a72442eb0ae0e428de71320":{
      "scriptId":"u36"},
    "9d286f116b2645999f2bb95b4f9fe26b":{
      "scriptId":"u37"},
    "564c0173dfff4fdcb29164587303bd18":{
      "scriptId":"u38"},
    "ba01b8204ab94ea7b342f5730088e03f":{
      "scriptId":"u39"},
    "468eb39ba86542b9b9875968fe06c962":{
      "scriptId":"u40"},
    "1229f145c65749f28b5e23b2a0550d76":{
      "scriptId":"u41"},
    "826f194c23514a278d62b35f044fafbc":{
      "scriptId":"u42"},
    "b0acd3e0ec954eef9b1b6f8e27adb8a4":{
      "scriptId":"u43"},
    "cf50a85b76b345cc96e165887c0c29c8":{
      "scriptId":"u44"},
    "bba6ff4f18874f64b53e3a1d451508df":{
      "scriptId":"u45"},
    "7e829d596655444cadae6c9e9d3e56d4":{
      "scriptId":"u46"},
    "a5a4d329d0554807a64f17dad81ad475":{
      "scriptId":"u47"},
    "1e8c2b9db166420da6bab52168065b39":{
      "scriptId":"u48"},
    "ef6bac28446248799a8aca99ae149838":{
      "scriptId":"u49"},
    "f5172e2e76b742818e80a1e4a6f2987a":{
      "scriptId":"u50"},
    "eaceba5086ff4e50a72fbab0b623f5b4":{
      "scriptId":"u51"},
    "a49f617d472247f6b4bb98fabf1c7a8e":{
      "scriptId":"u52"},
    "6876ada9498342a1b45599e8fed09d8f":{
      "scriptId":"u53"},
    "d4485d828ba84ec1903b081ee88bcc49":{
      "scriptId":"u54"},
    "c282cbe6081149c59c21cd78421a8867":{
      "scriptId":"u55"},
    "cc5d5322df0043fe8c304a24b088835d":{
      "scriptId":"u56"},
    "4bbcae91fcc64881a2351321809ffffa":{
      "scriptId":"u57"},
    "e33131982f444d7bbc7a41f87aec441a":{
      "scriptId":"u58"},
    "a5084e78cfb648f2a114e6f7993d6e7f":{
      "scriptId":"u59"},
    "ad9b88ea3ad94a6991cedf45825679b0":{
      "scriptId":"u60"},
    "ccf11a3f665748e48cfd5a7039b2cc0f":{
      "scriptId":"u61"},
    "8e36dc1f314a4ebbacede83a00cc6c17":{
      "scriptId":"u62"},
    "16dbeec4cdd34f0d84ea46577810ec49":{
      "scriptId":"u63"},
    "f9d5109ddfd548458c7ef8f147d5d0cb":{
      "scriptId":"u64"},
    "a813556a35bc48f2986ab32ae3d45d12":{
      "scriptId":"u65"},
    "133b765aacf3411b927439d37a77fc73":{
      "scriptId":"u66"},
    "2b86ff282bff4e3190f961baae54db29":{
      "scriptId":"u67"},
    "6494974c632c40c2a7b73f980010e26f":{
      "scriptId":"u68"},
    "6bf92c1d44f7489bbab323dde19d35cc":{
      "scriptId":"u69"},
    "ca80c67f23804b5db82445262b8a6832":{
      "scriptId":"u70"},
    "3b3218b42891462889a1dce76bc7fad6":{
      "scriptId":"u71"},
    "2c59aa3299724328b8c542d4c7e45fea":{
      "scriptId":"u72"},
    "0e98ade3f03e4c80b6196ef091c32b77":{
      "scriptId":"u73"},
    "b1bdcdacb42f4949b4b680f8716f67fb":{
      "scriptId":"u74"},
    "f9c506c3e0004c15bc27937571464d2b":{
      "scriptId":"u75"},
    "eeb430fcd2064295b70279488fbab75d":{
      "scriptId":"u76"},
    "ac5e4294972d4e4182bb43d23253528f":{
      "scriptId":"u77"},
    "ee018875ae2e4649bd9d6afc7bd2e2fe":{
      "scriptId":"u78"},
    "ef9e0a7acdc84a29bd35596e2c45f386":{
      "scriptId":"u79"},
    "608985327e314cfb988f7cad114893ab":{
      "scriptId":"u80"},
    "0548ecdd5ede4c8d9433c9f10988ed65":{
      "scriptId":"u81"},
    "5e5643ddb7ca4ed2988dc8a7e25beaef":{
      "scriptId":"u82"},
    "e6098bf822bb429190ccc7914ad3b70f":{
      "scriptId":"u83"},
    "ad6a7761760b4ace9b9fd6965816b90a":{
      "scriptId":"u84"},
    "e5e8e6a1692941d4905a0eb9f60a8ff4":{
      "scriptId":"u85"},
    "8b98665f6ffc4b7a91a95176367dbc17":{
      "scriptId":"u86"},
    "86028af65611404a85deaab9035cac09":{
      "scriptId":"u87"},
    "1dbf7018be3540a2ae166e2c9b5808a2":{
      "scriptId":"u88"},
    "3877b33355bb46a388946de2395ef9a5":{
      "scriptId":"u89"},
    "336d9e2c440248ada6e44ab752a502db":{
      "scriptId":"u90"},
    "9a31c9ef36d34584bc26497015956767":{
      "scriptId":"u91"}}});