$axure.loadCurrentPage({
  "url":"考试结果.html",
  "generationDate":new Date(1494572346398.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"845841368229403591b0cbf7775c2092",
    "type":"Axure:Page",
    "name":"考试结果",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f438cd88610e4f649db291344592918a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":950,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a1e133503664b7487b7de8c15810108",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":950,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/备课/u2.png"}},
{
          "id":"49f3473400184ba1ba8c5bec3e74a737",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":9},
            "size":{
              "width":68,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f1a9fa8479e4d91bcc2cfac5c2b1abe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":9},
                "size":{
                  "width":68,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c05feee14c24859ae4df16a98865dce",
          "label":"beike",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":119,
              "y":14},
            "size":{
              "width":80,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0780834fb35d41cca4dc444435b28af8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":119,
                  "y":14},
                "size":{
                  "width":80,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 beike = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["7c05feee14c24859ae4df16a98865dce"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 beike = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["7c05feee14c24859ae4df16a98865dce"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/备课/beike_u6.png",
            "selected~":"images/备课/beike_u6_selected.png"}},
{
          "id":"3cadbcda60074ba5baf582589562c2cf",
          "label":"souke",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":208,
              "y":14},
            "size":{
              "width":65,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8d27715b87944299c622d559c8c036f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":208,
                  "y":14},
                "size":{
                  "width":65,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 souke = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["3cadbcda60074ba5baf582589562c2cf"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 souke = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["3cadbcda60074ba5baf582589562c2cf"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/备课/souke_u8.png",
            "selected~":"images/备课/souke_u8_selected.png"}},
{
          "id":"78948941bfe441b798ef3fbc3f5011ed",
          "label":"guanli",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":282,
              "y":14},
            "size":{
              "width":70,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74269369fa91442cba6f0cda261d8d0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":282,
                  "y":14},
                "size":{
                  "width":70,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 guanli = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["78948941bfe441b798ef3fbc3f5011ed"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 guanli = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["78948941bfe441b798ef3fbc3f5011ed"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/校内管理/guanli_u13.png",
            "selected~":"images/校内管理/guanli_u13_selected.png"}},
{
          "id":"9f1fcf15c4c34239978f64f1443473d0",
          "label":"ceping",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":362,
              "y":14},
            "size":{
              "width":51,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f40c12c50d944e79a806e926a678ee6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":362,
                  "y":14},
                "size":{
                  "width":51,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 ceping = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["9f1fcf15c4c34239978f64f1443473d0"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 ceping = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["9f1fcf15c4c34239978f64f1443473d0"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/备课/ceping_u12.png",
            "selected~":"images/备课/ceping_u12_selected.png"}},
{
          "id":"a92024b300854e6b828a9f598b62bb34",
          "label":"peixun",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":423,
              "y":14},
            "size":{
              "width":58,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa415c4d45d34902bedc1e6c39d6eaad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":423,
                  "y":14},
                "size":{
                  "width":58,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a92024b300854e6b828a9f598b62bb34"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a92024b300854e6b828a9f598b62bb34"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/备课/peixun_u14.png",
            "selected~":"images/备课/peixun_u14_selected.png"}},
{
          "id":"203ebc3bd2274941b4fb1e021de9ddc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":14},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebfc89427d3944c4b119aed834a6e33e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":850,
                  "y":14},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "images":{
            "normal~":"images/备课/u16.png"}},
{
          "id":"7435ee420a934109a25ba185f23fe55b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":723},
            "size":{
              "width":964,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d28fb01924e490291b0c062e76afa3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":723},
                "size":{
                  "width":964,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/备课/u131.png"}},
{
          "id":"1eca068f231a44baaae952d2cd512fa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF336666,
              "opacity":1},
            "location":{
              "x":38,
              "y":736},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"396e2fe0997e44ec9860809b8b29b708",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF336666,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":736},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"024b620d7f374dd996d9085aa744a424",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":39},
            "size":{
              "width":79,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF33CCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/校内管理/u27_line.png"}},
{
          "id":"40a3503b4943476897484856e1fac3d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":678,
              "y":9},
            "size":{
              "width":79,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a580b8982e641f799ae338fe38d1380",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":678,
                  "y":9},
                "size":{
                  "width":79,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"794a79c433e446ba91362c55529821e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":13,
              "y":106},
            "size":{
              "width":920,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65a0080087034e7bbb2e6d6c5b6d89c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":13,
                  "y":106},
                "size":{
                  "width":920,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u23.png"}},
{
          "id":"a04a8331e290428287e3edc4330b7ded",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":37,
              "y":123},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6640bf0b0c4042388bd0222d83f7a47c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":37,
                  "y":123},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测评",
                      "target":{
                        "targetType":"page",
                        "url":"测评.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6516a8335204c13a6afd40c016cddca",
          "label":"ggxiaotu",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":55},
            "size":{
              "width":950,
              "height":50}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"38c9fbbf0159442d93dda66795bf9503",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5488f36850f24e5a964a071eed2b27fc",
                  "label":"",
                  "parentDynamicPanel":"c6516a8335204c13a6afd40c016cddca",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF66CCFF,
                      "opacity":1},
                    "size":{
                      "width":950,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dd3a3addfdc34904b7c78142505d0c54",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c6516a8335204c13a6afd40c016cddca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF66CCFF,
                          "opacity":1},
                        "size":{
                          "width":950,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/测评/u28.png"}},
{
                  "id":"8e4c77ee888a4ea8bddea415aadf6445",
                  "label":"kongzhiqi",
                  "parentDynamicPanel":"c6516a8335204c13a6afd40c016cddca",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":884,
                      "y":0},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"2b08106042de4d4cb255cdf3bf5b7166",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"3e8d2741b17146169b58d95f828ef8f7",
                          "label":"",
                          "parentDynamicPanel":"8e4c77ee888a4ea8bddea415aadf6445",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":66,
                              "height":30}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"28598424898f4de3862a51edc7a8b0a8",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"8e4c77ee888a4ea8bddea415aadf6445",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":66,
                                  "height":30}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/校内管理/u32.png"}}]}]}]}]},
{
          "id":"735b8f7245bc4f42ad42963b85b1da80",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":13,
              "y":172},
            "size":{
              "width":920,
              "height":108},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5005e2d9cd5b4198b49eaa7f26b9dcc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":13,
                  "y":172},
                "size":{
                  "width":920,
                  "height":108},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u38.png"}},
{
          "id":"bdb2c1e20879424099d42224372fc7e5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":210},
            "size":{
              "width":890,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/测评/u40_line.png"}},
{
          "id":"be2db095c8fd4f19a0f5dfb6aa1734a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":25,
              "y":182},
            "size":{
              "width":93,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c40174206754aa0bc81b295d4f6fada",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":25,
                  "y":182},
                "size":{
                  "width":93,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 考试测评",
                      "target":{
                        "targetType":"page",
                        "url":"考试测评.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/测评/u41.png"}},
{
          "id":"4c2ef285fde34d379c44d3801ab7ae3c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":210},
            "size":{
              "width":93,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF33CCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/测评/u43_line.png"}},
{
          "id":"a4732d7ec14a422593211760f8999549",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":118,
              "y":182},
            "size":{
              "width":93,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd74e973ca624171996b56356c31ff96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":118,
                  "y":182},
                "size":{
                  "width":93,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 考试结果",
                      "target":{
                        "targetType":"page",
                        "url":"考试结果.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/测评/u41.png"}},
{
          "id":"93d984c8d34d4cc6a80bacd345ad3013",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":790,
              "y":182},
            "size":{
              "width":110,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61192f229e344804bdab8898572388d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":790,
                  "y":182},
                "size":{
                  "width":110,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 生成考试卷&nbsp; 不设计",
                      "target":{
                        "targetType":"page",
                        "url":"生成考试卷__不设计.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/测评/u46.png"}},
{
          "id":"9d3b3231468d47b4a5a1e5ca45df71ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "location":{
              "x":19,
              "y":290},
            "size":{
              "width":61,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa08fde406cf4fdd8e202e192ce8ebc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":290},
                "size":{
                  "width":61,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9f16dad3a014616a479651ed340af8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "location":{
              "x":138,
              "y":123},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f47691d503c8421099e375b23088c663",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":123},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 考试测评",
                      "target":{
                        "targetType":"page",
                        "url":"考试测评.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ccd72d0306a8452dad0a699adf23fcd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":44,
              "y":240},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e74d94e8ec445d5af66b3f3bc40d151",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":240},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36cb6b99513e4420bcef67cf4829b4ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":235},
            "size":{
              "width":269,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23c374898a18461e94e5f08f1d165674",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":111,
                  "y":235},
                "size":{
                  "width":269,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考试测评/u73.png"}},
{
          "id":"de475ef09a0b4edd968b5c29d4abb220",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":390,
              "y":235},
            "size":{
              "width":60,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23f6625625484404bfba2ceb3e57742a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":390,
                  "y":235},
                "size":{
                  "width":60,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考试测评/u75.png"}},
{
          "id":"f1fdd2c7126c489292769c9ca18ff835",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":13,
              "y":314},
            "size":{
              "width":97,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa6572e03e5842fc82e00e4b4f3f8a4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":13,
                  "y":314},
                "size":{
                  "width":97,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评报告/u43.png"}},
{
          "id":"31f4992241d2402ca3a07a518401220c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":805,
              "y":354},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"31"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb9d9cee2c5a4479a2bb5ac5ca66008d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":805,
                  "y":354},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"31"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u68.png"}},
{
          "id":"f0af10b25dae4f7a99411a03aaf20343",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":353},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"32"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0b549a4884944eaa59cf53a070f3bc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":353},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"32"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u70.png"}},
{
          "id":"0ce436b88a5643f1aeee50c66c1e9f2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":406,
              "y":431},
            "size":{
              "width":103,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0665a008aa6a40b0a5190a5fceef55b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":406,
                  "y":431},
                "size":{
                  "width":103,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea1b345d857448c988716ef2bca93f69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":260,
              "y":319},
            "size":{
              "width":141,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e381c976777a4f37921dacc4e69359ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":260,
                  "y":319},
                "size":{
                  "width":141,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评报告/u68.png"}},
{
          "id":"28d56bf9bd0a44d1bf21a3c694b86420",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":499,
              "y":314},
            "size":{
              "width":131,
              "height":36},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4b6507c6d1f4cd0b39c0f74eda8b5d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":499,
                  "y":314},
                "size":{
                  "width":131,
                  "height":36},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评报告/u74.png"}},
{
          "id":"ada7b3f70bdf4dbaa7904d2215435e1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00FF66,
                  "opacity":1}}},
            "location":{
              "x":875,
              "y":359},
            "size":{
              "width":27,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbe603df866041138252f2d85adffe69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF00FF66,
                      "opacity":1}}},
                "location":{
                  "x":875,
                  "y":359},
                "size":{
                  "width":27,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"7eb340a1155844d4badc8b0b8b8ab877",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":13,
              "y":349},
            "size":{
              "width":97,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19000468c87245b1ad7fd2a25d702908",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":13,
                  "y":349},
                "size":{
                  "width":97,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评报告/u78.png"}},
{
          "id":"2a64980e3a4340e0a9a6f227b466e7ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":260,
              "y":354},
            "size":{
              "width":141,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"024cad635d69465db239b4b4cb9109fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":260,
                  "y":354},
                "size":{
                  "width":141,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评报告/u80.png"}},
{
          "id":"296f7109d735492eb552a756398d6638",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":499,
              "y":349},
            "size":{
              "width":131,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b28071bd3d1749809f6e2635cfa2c7d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":499,
                  "y":349},
                "size":{
                  "width":131,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评报告/u86.png"}},
{
          "id":"a9a8c8249e364d4f8070cf768fcd038f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":343},
            "size":{
              "width":920,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/测评报告/u88_line.png"}},
{
          "id":"43cb6db59dfb4780bf1b19f07f0c3fdf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":394},
            "size":{
              "width":920,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/测评报告/u88_line.png"}},
{
          "id":"9959eeba343c4ab5bc7fa80586a99a58",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":349},
            "size":{
              "width":675,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true},
{
          "id":"6a4747ce361f4d63bfe2dfcc96f28600",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":236,
              "y":123},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73a2ec670f3749e99ca98d0817cdb604",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":236,
                  "y":123},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 老师测评",
                      "target":{
                        "targetType":"page",
                        "url":"老师测评.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f438cd88610e4f649db291344592918a":{
      "scriptId":"u0"},
    "8a1e133503664b7487b7de8c15810108":{
      "scriptId":"u1"},
    "49f3473400184ba1ba8c5bec3e74a737":{
      "scriptId":"u2"},
    "9f1a9fa8479e4d91bcc2cfac5c2b1abe":{
      "scriptId":"u3"},
    "7c05feee14c24859ae4df16a98865dce":{
      "scriptId":"u4"},
    "0780834fb35d41cca4dc444435b28af8":{
      "scriptId":"u5"},
    "3cadbcda60074ba5baf582589562c2cf":{
      "scriptId":"u6"},
    "e8d27715b87944299c622d559c8c036f":{
      "scriptId":"u7"},
    "78948941bfe441b798ef3fbc3f5011ed":{
      "scriptId":"u8"},
    "74269369fa91442cba6f0cda261d8d0b":{
      "scriptId":"u9"},
    "9f1fcf15c4c34239978f64f1443473d0":{
      "scriptId":"u10"},
    "f40c12c50d944e79a806e926a678ee6c":{
      "scriptId":"u11"},
    "a92024b300854e6b828a9f598b62bb34":{
      "scriptId":"u12"},
    "fa415c4d45d34902bedc1e6c39d6eaad":{
      "scriptId":"u13"},
    "203ebc3bd2274941b4fb1e021de9ddc2":{
      "scriptId":"u14"},
    "ebfc89427d3944c4b119aed834a6e33e":{
      "scriptId":"u15"},
    "7435ee420a934109a25ba185f23fe55b":{
      "scriptId":"u16"},
    "3d28fb01924e490291b0c062e76afa3a":{
      "scriptId":"u17"},
    "1eca068f231a44baaae952d2cd512fa1":{
      "scriptId":"u18"},
    "396e2fe0997e44ec9860809b8b29b708":{
      "scriptId":"u19"},
    "024b620d7f374dd996d9085aa744a424":{
      "scriptId":"u20"},
    "40a3503b4943476897484856e1fac3d6":{
      "scriptId":"u21"},
    "2a580b8982e641f799ae338fe38d1380":{
      "scriptId":"u22"},
    "794a79c433e446ba91362c55529821e3":{
      "scriptId":"u23"},
    "65a0080087034e7bbb2e6d6c5b6d89c6":{
      "scriptId":"u24"},
    "a04a8331e290428287e3edc4330b7ded":{
      "scriptId":"u25"},
    "6640bf0b0c4042388bd0222d83f7a47c":{
      "scriptId":"u26"},
    "c6516a8335204c13a6afd40c016cddca":{
      "scriptId":"u27"},
    "5488f36850f24e5a964a071eed2b27fc":{
      "scriptId":"u28"},
    "dd3a3addfdc34904b7c78142505d0c54":{
      "scriptId":"u29"},
    "8e4c77ee888a4ea8bddea415aadf6445":{
      "scriptId":"u30"},
    "3e8d2741b17146169b58d95f828ef8f7":{
      "scriptId":"u31"},
    "28598424898f4de3862a51edc7a8b0a8":{
      "scriptId":"u32"},
    "735b8f7245bc4f42ad42963b85b1da80":{
      "scriptId":"u33"},
    "5005e2d9cd5b4198b49eaa7f26b9dcc1":{
      "scriptId":"u34"},
    "bdb2c1e20879424099d42224372fc7e5":{
      "scriptId":"u35"},
    "be2db095c8fd4f19a0f5dfb6aa1734a2":{
      "scriptId":"u36"},
    "2c40174206754aa0bc81b295d4f6fada":{
      "scriptId":"u37"},
    "4c2ef285fde34d379c44d3801ab7ae3c":{
      "scriptId":"u38"},
    "a4732d7ec14a422593211760f8999549":{
      "scriptId":"u39"},
    "fd74e973ca624171996b56356c31ff96":{
      "scriptId":"u40"},
    "93d984c8d34d4cc6a80bacd345ad3013":{
      "scriptId":"u41"},
    "61192f229e344804bdab8898572388d4":{
      "scriptId":"u42"},
    "9d3b3231468d47b4a5a1e5ca45df71ae":{
      "scriptId":"u43"},
    "fa08fde406cf4fdd8e202e192ce8ebc3":{
      "scriptId":"u44"},
    "b9f16dad3a014616a479651ed340af8a":{
      "scriptId":"u45"},
    "f47691d503c8421099e375b23088c663":{
      "scriptId":"u46"},
    "ccd72d0306a8452dad0a699adf23fcd6":{
      "scriptId":"u47"},
    "2e74d94e8ec445d5af66b3f3bc40d151":{
      "scriptId":"u48"},
    "36cb6b99513e4420bcef67cf4829b4ef":{
      "scriptId":"u49"},
    "23c374898a18461e94e5f08f1d165674":{
      "scriptId":"u50"},
    "de475ef09a0b4edd968b5c29d4abb220":{
      "scriptId":"u51"},
    "23f6625625484404bfba2ceb3e57742a":{
      "scriptId":"u52"},
    "f1fdd2c7126c489292769c9ca18ff835":{
      "scriptId":"u53"},
    "fa6572e03e5842fc82e00e4b4f3f8a4a":{
      "scriptId":"u54"},
    "31f4992241d2402ca3a07a518401220c":{
      "scriptId":"u55"},
    "fb9d9cee2c5a4479a2bb5ac5ca66008d":{
      "scriptId":"u56"},
    "f0af10b25dae4f7a99411a03aaf20343":{
      "scriptId":"u57"},
    "b0b549a4884944eaa59cf53a070f3bc4":{
      "scriptId":"u58"},
    "0ce436b88a5643f1aeee50c66c1e9f2d":{
      "scriptId":"u59"},
    "0665a008aa6a40b0a5190a5fceef55b3":{
      "scriptId":"u60"},
    "ea1b345d857448c988716ef2bca93f69":{
      "scriptId":"u61"},
    "e381c976777a4f37921dacc4e69359ff":{
      "scriptId":"u62"},
    "28d56bf9bd0a44d1bf21a3c694b86420":{
      "scriptId":"u63"},
    "e4b6507c6d1f4cd0b39c0f74eda8b5d5":{
      "scriptId":"u64"},
    "ada7b3f70bdf4dbaa7904d2215435e1a":{
      "scriptId":"u65"},
    "bbe603df866041138252f2d85adffe69":{
      "scriptId":"u66"},
    "7eb340a1155844d4badc8b0b8b8ab877":{
      "scriptId":"u67"},
    "19000468c87245b1ad7fd2a25d702908":{
      "scriptId":"u68"},
    "2a64980e3a4340e0a9a6f227b466e7ed":{
      "scriptId":"u69"},
    "024cad635d69465db239b4b4cb9109fe":{
      "scriptId":"u70"},
    "296f7109d735492eb552a756398d6638":{
      "scriptId":"u71"},
    "b28071bd3d1749809f6e2635cfa2c7d4":{
      "scriptId":"u72"},
    "a9a8c8249e364d4f8070cf768fcd038f":{
      "scriptId":"u73"},
    "43cb6db59dfb4780bf1b19f07f0c3fdf":{
      "scriptId":"u74"},
    "9959eeba343c4ab5bc7fa80586a99a58":{
      "scriptId":"u75"},
    "6a4747ce361f4d63bfe2dfcc96f28600":{
      "scriptId":"u76"},
    "73a2ec670f3749e99ca98d0817cdb604":{
      "scriptId":"u77"}}});