$axure.loadCurrentPage({
  "url":"更换讲次.html",
  "generationDate":new Date(1494572324995.85),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bfe2668d9c154e55a9eec72ccdabb4c0",
    "type":"Axure:Page",
    "name":"更换讲次",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ebc00762436d42f3ab4cf0077a3f88c9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":668},
            "size":{
              "width":979,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e668c2aebd88435a9b9d923384a36e10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":668},
                "size":{
                  "width":979,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/备课/u131.png"}},
{
          "id":"cd324e736aad4a58b1ef4a7159d77be5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF336666,
              "opacity":1},
            "location":{
              "x":51,
              "y":681},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e8ba93fadf442d7bc380ec5e3c6cc39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF336666,
                  "opacity":1},
                "location":{
                  "x":51,
                  "y":681},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23824ad2a53041cf8804c1ee4b921826",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1020,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ade5c098f034349983bbb6ec94ce231",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1020,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/讲课页面/u4.png"}},
{
          "id":"b9174a9e988c44a2aaf3996b8cd36b64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":20},
            "size":{
              "width":119,
              "height":82},
            "rotation":"270",
            "textRotation":"270",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78865b8a3fb64d7e9c5f5ff2c3da6d28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":20},
                "size":{
                  "width":119,
                  "height":82},
                "rotation":"270",
                "textRotation":"270",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/讲课页面/u6.png"}},
{
          "id":"f20f7abd8cb54db1a628ac69bae2dbc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":19},
            "size":{
              "width":53,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc53a0bc6e8f49c7ad1faff9a0e3599c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":19},
                "size":{
                  "width":53,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e93233d908ff46eca74236d22b4ebc42",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":69},
            "size":{
              "width":34,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cee8d2c31e284e42a8813e3311d29f31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":69},
                "size":{
                  "width":34,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1902b5e0f1674ae89fb2353391aa183f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCAED92},
            "location":{
              "x":944,
              "y":10},
            "size":{
              "width":60,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de0c995a27384eaa8c855b6dfedc47ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCAED92},
                "location":{
                  "x":944,
                  "y":10},
                "size":{
                  "width":60,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 授课",
                      "target":{
                        "targetType":"page",
                        "url":"授课.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课页面/u12.png"}},
{
          "id":"e7c79de7834849959272f90d90424cfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF009933},
            "location":{
              "x":646,
              "y":10},
            "size":{
              "width":60,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51436571df084a5facba1bbf64a8fda1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009933},
                "location":{
                  "x":646,
                  "y":10},
                "size":{
                  "width":60,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讲课页面",
                      "target":{
                        "targetType":"page",
                        "url":"讲课页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课页面/u14.png"}},
{
          "id":"5ce7b7fbc5654525b475bdea106e940f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCAED92},
            "location":{
              "x":730,
              "y":10},
            "size":{
              "width":60,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5addb8a95034afb8fd261d3ae2e4122",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCAED92},
                "location":{
                  "x":730,
                  "y":10},
                "size":{
                  "width":60,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 jifen 向下滑动 500 ms 灯箱效果",
                      "objectsToFades":[{
                          "objectPath":["83aebffb4593450c93f843f4d93dd520"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"lightbox",
                              "lightbox":{
                                "r":67,
                                "g":67,
                                "b":67,
                                "a":155}}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课页面/u12.png"}},
{
          "id":"26bb50768cc8495ea127e8c2fbd29523",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":749,
              "y":32},
            "size":{
              "width":23,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7611c4b6dbc1471eb631129c4e2cb65e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":749,
                  "y":32},
                "size":{
                  "width":23,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3aa2526eeacf4f599a46be26ee4978cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCAED92},
            "location":{
              "x":806,
              "y":10},
            "size":{
              "width":60,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e6e6135a89048e0993d7c8d2bd99371",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCAED92},
                "location":{
                  "x":806,
                  "y":10},
                "size":{
                  "width":60,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 提问",
                      "target":{
                        "targetType":"page",
                        "url":"提问.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课页面/u12.png"}},
{
          "id":"cdd62ce9809549daa13dd04542debcb0",
          "label":"liebiao",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":876,
              "y":10},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 liebiaoDIV 向下滑动 500 ms",
                      "objectsToFades":[{
                          "objectPath":["1d2e6ec1362741e2a385e5ab06b3bcb4"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"a143d6ebbaf343b8a48531b5626b84de",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bb584df297694bbb997da06c9f7ee2ef",
                  "label":"",
                  "parentDynamicPanel":"cdd62ce9809549daa13dd04542debcb0",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCAED92},
                    "size":{
                      "width":60,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "cornerRadiusTopLeft":"30"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cb3c453225fd45c1bbb67b16f1ffd3f8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cdd62ce9809549daa13dd04542debcb0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCAED92},
                        "size":{
                          "width":60,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "cornerRadiusTopLeft":"30"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u12.png"}},
{
                  "id":"7ea211596f9c47a0a2d4f8f52e79ad66",
                  "label":"",
                  "parentDynamicPanel":"cdd62ce9809549daa13dd04542debcb0",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":15,
                      "y":4},
                    "size":{
                      "width":30,
                      "height":10},
                    "borderWidth":"4"},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/讲课页面/u25_line.png"}},
{
                  "id":"d98c4cebb01d4e21bd2a07fb619a4093",
                  "label":"",
                  "parentDynamicPanel":"cdd62ce9809549daa13dd04542debcb0",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":15,
                      "y":15},
                    "size":{
                      "width":30,
                      "height":10},
                    "borderWidth":"4"},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/讲课页面/u25_line.png"}},
{
                  "id":"7f97c1ad44804ce4ba989e3dc2f38f0d",
                  "label":"",
                  "parentDynamicPanel":"cdd62ce9809549daa13dd04542debcb0",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":15,
                      "y":26},
                    "size":{
                      "width":30,
                      "height":10},
                    "borderWidth":"4"},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/讲课页面/u25_line.png"}}]}]},
{
          "id":"7ad384ab4e8a4d59aacfad3c57aec146",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":119,
              "y":110},
            "size":{
              "width":820,
              "height":440},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCC33},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5099152ddfb74de485f53d1c9f7a2642",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":119,
                  "y":110},
                "size":{
                  "width":820,
                  "height":440},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCC33},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/讲课页面/u28.png"}},
{
          "id":"83aebffb4593450c93f843f4d93dd520",
          "label":"jifen",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":99,
              "y":85},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"71c1dc2f0418472fa0b6e97f49ca4e8b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7ea8189267064221bcb8b76b163151f4",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":860,
                      "height":525}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d147528a2ff843c39575dc1369c1600f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":860,
                          "height":525}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u31.png"}},
{
                  "id":"0908d02652d045d5afe6214a2cc185ea",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":828,
                      "y":4},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b43a2aa778c14d4aa8bd3fec9fc02872",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":828,
                          "y":4},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 jifen",
                              "objectsToFades":[{
                                  "objectPath":["83aebffb4593450c93f843f4d93dd520"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0e4be9341ae94976bc382574c3bbb5eb",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":30,
                      "y":24},
                    "size":{
                      "width":33,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"377516b3cf274128b35f156b5a23101f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":30,
                          "y":24},
                        "size":{
                          "width":33,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5700b028a76947ac90a2cbd0cf438210",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":43},
                    "size":{
                      "width":20,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a826a1f4aa604ea4a0af21c0dfdb173e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":19,
                          "y":43},
                        "size":{
                          "width":20,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u38.png"}},
{
                  "id":"a4046ea036ae41ea889632016bdbc8a0",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":49,
                      "y":43},
                    "size":{
                      "width":20,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"71451642950945a4a2d4b6e9096fb015",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":49,
                          "y":43},
                        "size":{
                          "width":20,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u38.png"}},
{
                  "id":"d66a782325c44cd7b582e1559247ae6f",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":86,
                      "y":30},
                    "size":{
                      "width":12,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8594d1c4c9164a8aa26f73631fdc417c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":86,
                          "y":30},
                        "size":{
                          "width":12,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"02768ae0a4cd405995aa4d342a18a8b3",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":171,
                      "y":24},
                    "size":{
                      "width":33,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd6c562bf589444e91ff942527921ff2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":171,
                          "y":24},
                        "size":{
                          "width":33,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"16ba9622f97f41a2a1db980c5e63b175",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":43},
                    "size":{
                      "width":20,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0d293dfd35d24bb89b0834789fa2be8e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":160,
                          "y":43},
                        "size":{
                          "width":20,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u38.png"}},
{
                  "id":"7acd5834a8aa4b1796cfbabd04fa3135",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":190,
                      "y":43},
                    "size":{
                      "width":20,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2df0f7c5cb244b46b7ea7cfde710346a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":190,
                          "y":43},
                        "size":{
                          "width":20,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u38.png"}},
{
                  "id":"a11a07ed3ce84434ba17321e461c71ea",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":227,
                      "y":30},
                    "size":{
                      "width":12,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"086f88bea3484561a6515099d8b2e05a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":227,
                          "y":30},
                        "size":{
                          "width":12,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9afbe27bee4f43a7bc125aedbf5e9f61",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":292,
                      "y":24},
                    "size":{
                      "width":33,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c0fbbdde8566476b94915f697c5cf9ae",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":292,
                          "y":24},
                        "size":{
                          "width":33,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"815f5ccfc900453c95e0052244ab8001",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":281,
                      "y":43},
                    "size":{
                      "width":20,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"34beafceff7f434aa252faa18c1ba58e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":281,
                          "y":43},
                        "size":{
                          "width":20,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u38.png"}},
{
                  "id":"274ffc1198c24d458bdaf31754dbd49e",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":311,
                      "y":43},
                    "size":{
                      "width":20,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ed828ebd58244f1c9366ce221e4ae034",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":311,
                          "y":43},
                        "size":{
                          "width":20,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u38.png"}},
{
                  "id":"42aa9aa82afc4f0296d5ae344e305a8c",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":348,
                      "y":30},
                    "size":{
                      "width":12,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0cac02574c1b449e86999134ded33768",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":348,
                          "y":30},
                        "size":{
                          "width":12,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"683c265d92b94cbfa88ca0222a405a7f",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":411,
                      "y":24},
                    "size":{
                      "width":33,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6c884b7053bf4b07a92e7da7848830d5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":411,
                          "y":24},
                        "size":{
                          "width":33,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"351f89c718344d0d9c5ed5138349b14b",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":43},
                    "size":{
                      "width":20,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d649e728e0364b989ffeb2d0fa53179d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":400,
                          "y":43},
                        "size":{
                          "width":20,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u38.png"}},
{
                  "id":"96386648ad034e5cba17dddfd0e3563a",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":430,
                      "y":43},
                    "size":{
                      "width":20,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e40028b6b6b148a4841102e3f2cc791e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":430,
                          "y":43},
                        "size":{
                          "width":20,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u38.png"}},
{
                  "id":"c7bd9987f1f64c6ca1fc7f341680fa41",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":467,
                      "y":30},
                    "size":{
                      "width":12,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7139a8f210424178a62f1934051b75aa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":467,
                          "y":30},
                        "size":{
                          "width":12,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"324f08e94276461aa41d78289138fba8",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF6699FF},
                    "location":{
                      "x":288,
                      "y":390},
                    "size":{
                      "width":77,
                      "height":30},
                    "cornerRadiusTopLeft":"8"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a9a20ca4c7bc41e6a40e7e5fb8c451eb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF6699FF},
                        "location":{
                          "x":288,
                          "y":390},
                        "size":{
                          "width":77,
                          "height":30},
                        "cornerRadiusTopLeft":"8"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 divjiafen",
                              "objectsToFades":[{
                                  "objectPath":["9df5fce9505247f2bdcc5c9eaeb3902f"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/讲课页面/u84.png"}},
{
                  "id":"30c5eb3ee8b44f76ad88fadfacdcba54",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC},
                    "location":{
                      "x":456,
                      "y":390},
                    "size":{
                      "width":77,
                      "height":30},
                    "cornerRadiusTopLeft":"8"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a8ee147dd43242ca8574b412c4ba483d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFBCBCBC},
                        "location":{
                          "x":456,
                          "y":390},
                        "size":{
                          "width":77,
                          "height":30},
                        "cornerRadiusTopLeft":"8"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 jifen",
                              "objectsToFades":[{
                                  "objectPath":["83aebffb4593450c93f843f4d93dd520"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/讲课页面/u86.png"}},
{
                  "id":"02e19815b0b14a31adc5dd3767a5890f",
                  "label":"",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF3300FF,
                      "opacity":1},
                    "location":{
                      "x":39,
                      "y":148},
                    "size":{
                      "width":388,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d0de73b6ccad46da879acf307b590576",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF3300FF,
                          "opacity":1},
                        "location":{
                          "x":39,
                          "y":148},
                        "size":{
                          "width":388,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9df5fce9505247f2bdcc5c9eaeb3902f",
                  "label":"divjiafen",
                  "parentDynamicPanel":"83aebffb4593450c93f843f4d93dd520",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":281,
                      "y":140},
                    "size":{
                      "width":10,
                      "height":10},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"41872766a16d44b7823f425de16783fb",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"c1d39c60e58d4a9c8e4512bce506be74",
                          "label":"",
                          "parentDynamicPanel":"9df5fce9505247f2bdcc5c9eaeb3902f",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":319,
                              "height":160}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"bfd7658e0ccb48b2ac84df38be6660b9",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"9df5fce9505247f2bdcc5c9eaeb3902f",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":319,
                                  "height":160}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/讲课页面/u91.png"}},
{
                          "id":"696eade4c52f416c89d126d98f602daf",
                          "label":"",
                          "parentDynamicPanel":"9df5fce9505247f2bdcc5c9eaeb3902f",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "location":{
                              "x":42,
                              "y":40},
                            "size":{
                              "width":234,
                              "height":19}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"b4cc3de2c56e42daba24e430c68a2b1f",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"9df5fce9505247f2bdcc5c9eaeb3902f",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"16px",
                                "location":{
                                  "x":42,
                                  "y":40},
                                "size":{
                                  "width":234,
                                  "height":19}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"09b285dd6e414a4d9e88cbd3836ecdc9",
                          "label":"",
                          "parentDynamicPanel":"9df5fce9505247f2bdcc5c9eaeb3902f",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF6699FF},
                            "location":{
                              "x":112,
                              "y":115},
                            "size":{
                              "width":77,
                              "height":30},
                            "cornerRadiusTopLeft":"8"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"4eed59966d5e49fbaabbf2c724f7b05e",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"9df5fce9505247f2bdcc5c9eaeb3902f",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFF6699FF},
                                "location":{
                                  "x":112,
                                  "y":115},
                                "size":{
                                  "width":77,
                                  "height":30},
                                "cornerRadiusTopLeft":"8"},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"隐藏 jifen",
                                      "objectsToFades":[{
                                          "objectPath":["83aebffb4593450c93f843f4d93dd520"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/讲课页面/u84.png"}}]}]}]}]},
{
          "id":"15a8fc1a9f754c2eb2f03d51886efab6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":165},
            "size":{
              "width":302,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9f7fd9f698a4522ac98c56e3b2b4ff4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":165},
                "size":{
                  "width":302,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讲课页面",
                      "target":{
                        "targetType":"page",
                        "url":"讲课页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7245bb66e9d0458a9f9d4b49c0dd1865",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":200},
            "size":{
              "width":302,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3066e9c0207e4986873c6fa557fbbe6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":200},
                "size":{
                  "width":302,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讲课页面",
                      "target":{
                        "targetType":"page",
                        "url":"讲课页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2b5dbab1e4f4901b355fa02bd9fd53a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":234},
            "size":{
              "width":302,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32c82532685a4d08b879e726be599cd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":234},
                "size":{
                  "width":302,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讲课页面",
                      "target":{
                        "targetType":"page",
                        "url":"讲课页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a093df17d06843f68fcf86520e96fdbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":270},
            "size":{
              "width":302,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"922d179deaad41a39dac00969c6bb8a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":270},
                "size":{
                  "width":302,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讲课页面",
                      "target":{
                        "targetType":"page",
                        "url":"讲课页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"666b3ec221874425a20a94b3eb079794",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":310},
            "size":{
              "width":302,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54879e419a8043f29d7ebfa06e56fcd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":310},
                "size":{
                  "width":302,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讲课页面",
                      "target":{
                        "targetType":"page",
                        "url":"讲课页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6418ceb8371f40209a35279d123d6264",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":130},
            "size":{
              "width":10,
              "height":400},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFCC33}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/更换讲次/u90_line.png"}},
{
          "id":"e0a2164c2ba64a7bab9113d894c74ad3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":428,
              "y":430},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea400d3aad354e27924f6f41f339b0e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":428,
                  "y":430},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d2e6ec1362741e2a385e5ab06b3bcb4",
          "label":"liebiaoDIV",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":1,
              "y":62},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"7f28dc3e7c5646a8be455a7337d8e6c4",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3cbba2952b134c6e808d6f438ef462e4",
                  "label":"",
                  "parentDynamicPanel":"1d2e6ec1362741e2a385e5ab06b3bcb4",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1019,
                      "height":643}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d54bc4a7d6d747dd88a14bad7830b9b5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1d2e6ec1362741e2a385e5ab06b3bcb4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1019,
                          "height":643}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u104.png"}},
{
                  "id":"2fc3ee30eced443d8a911213c3bb7b86",
                  "label":"",
                  "parentDynamicPanel":"1d2e6ec1362741e2a385e5ab06b3bcb4",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":290,
                      "y":60},
                    "size":{
                      "width":460,
                      "height":440},
                    "cornerRadiusTopLeft":"7"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"126b8e4cade2477bb261248b31d62d19",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1d2e6ec1362741e2a385e5ab06b3bcb4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":290,
                          "y":60},
                        "size":{
                          "width":460,
                          "height":440},
                        "cornerRadiusTopLeft":"7"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/上讲作业页面/u87.png"}},
{
                  "id":"882fc2de57ae4e81a91fafcffdf205db",
                  "label":"",
                  "parentDynamicPanel":"1d2e6ec1362741e2a385e5ab06b3bcb4",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":716,
                      "y":45},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"51e593c87b70410dba8979e8de78f3a1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1d2e6ec1362741e2a385e5ab06b3bcb4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":716,
                          "y":45},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 liebiaoDIV 向上滑动 500 ms",
                              "objectsToFades":[{
                                  "objectPath":["1d2e6ec1362741e2a385e5ab06b3bcb4"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideUp",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/讲课页面/u108.png"}},
{
                  "id":"27cc5d4771084e3aa182debda188219b",
                  "label":"",
                  "parentDynamicPanel":"1d2e6ec1362741e2a385e5ab06b3bcb4",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":324,
                      "y":90},
                    "size":{
                      "width":70,
                      "height":50},
                    "cornerRadiusTopLeft":"31"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"792a27c19df148dba2cfb59f62ec1fc8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1d2e6ec1362741e2a385e5ab06b3bcb4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":324,
                          "y":90},
                        "size":{
                          "width":70,
                          "height":50},
                        "cornerRadiusTopLeft":"31"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 上讲作业页面",
                              "target":{
                                "targetType":"page",
                                "url":"上讲作业页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/讲课页面/u110.png"}},
{
                  "id":"a55cae6839b141e69e0fced94a00840b",
                  "label":"",
                  "parentDynamicPanel":"1d2e6ec1362741e2a385e5ab06b3bcb4",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":480,
                      "y":90},
                    "size":{
                      "width":70,
                      "height":50},
                    "cornerRadiusTopLeft":"26"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0f8e12fb2c844782a5cce419ed1be44a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1d2e6ec1362741e2a385e5ab06b3bcb4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":480,
                          "y":90},
                        "size":{
                          "width":70,
                          "height":50},
                        "cornerRadiusTopLeft":"26"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 积分排名",
                              "target":{
                                "targetType":"page",
                                "url":"积分排名.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/讲课页面/u110.png"}},
{
                  "id":"58dd55f774c74768816baeb5b37a36cb",
                  "label":"",
                  "parentDynamicPanel":"1d2e6ec1362741e2a385e5ab06b3bcb4",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":477,
                      "y":310},
                    "size":{
                      "width":70,
                      "height":50},
                    "cornerRadiusTopLeft":"24"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8560b735aa7d4295b78360d4902842bb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1d2e6ec1362741e2a385e5ab06b3bcb4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":477,
                          "y":310},
                        "size":{
                          "width":70,
                          "height":50},
                        "cornerRadiusTopLeft":"24"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 知识点分解",
                              "target":{
                                "targetType":"page",
                                "url":"知识点分解.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/讲课页面/u112.png"}},
{
                  "id":"c1671bb3fd5d4cc299148f539cd3739e",
                  "label":"",
                  "parentDynamicPanel":"1d2e6ec1362741e2a385e5ab06b3bcb4",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":624,
                      "y":90},
                    "size":{
                      "width":70,
                      "height":50},
                    "cornerRadiusTopLeft":"28"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"be38b5a243184d0186915c4404469833",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1d2e6ec1362741e2a385e5ab06b3bcb4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":624,
                          "y":90},
                        "size":{
                          "width":70,
                          "height":50},
                        "cornerRadiusTopLeft":"28"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 更换讲次",
                              "target":{
                                "targetType":"page",
                                "url":"更换讲次.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/讲课页面/u110.png"}},
{
                  "id":"47389a3391c54702bb43c67da119f02a",
                  "label":"",
                  "parentDynamicPanel":"1d2e6ec1362741e2a385e5ab06b3bcb4",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":324,
                      "y":260},
                    "size":{
                      "width":376,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/上讲作业页面/u99_line.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "ebc00762436d42f3ab4cf0077a3f88c9":{
      "scriptId":"u0"},
    "e668c2aebd88435a9b9d923384a36e10":{
      "scriptId":"u1"},
    "cd324e736aad4a58b1ef4a7159d77be5":{
      "scriptId":"u2"},
    "7e8ba93fadf442d7bc380ec5e3c6cc39":{
      "scriptId":"u3"},
    "23824ad2a53041cf8804c1ee4b921826":{
      "scriptId":"u4"},
    "8ade5c098f034349983bbb6ec94ce231":{
      "scriptId":"u5"},
    "b9174a9e988c44a2aaf3996b8cd36b64":{
      "scriptId":"u6"},
    "78865b8a3fb64d7e9c5f5ff2c3da6d28":{
      "scriptId":"u7"},
    "f20f7abd8cb54db1a628ac69bae2dbc7":{
      "scriptId":"u8"},
    "bc53a0bc6e8f49c7ad1faff9a0e3599c":{
      "scriptId":"u9"},
    "e93233d908ff46eca74236d22b4ebc42":{
      "scriptId":"u10"},
    "cee8d2c31e284e42a8813e3311d29f31":{
      "scriptId":"u11"},
    "1902b5e0f1674ae89fb2353391aa183f":{
      "scriptId":"u12"},
    "de0c995a27384eaa8c855b6dfedc47ce":{
      "scriptId":"u13"},
    "e7c79de7834849959272f90d90424cfc":{
      "scriptId":"u14"},
    "51436571df084a5facba1bbf64a8fda1":{
      "scriptId":"u15"},
    "5ce7b7fbc5654525b475bdea106e940f":{
      "scriptId":"u16"},
    "e5addb8a95034afb8fd261d3ae2e4122":{
      "scriptId":"u17"},
    "26bb50768cc8495ea127e8c2fbd29523":{
      "scriptId":"u18"},
    "7611c4b6dbc1471eb631129c4e2cb65e":{
      "scriptId":"u19"},
    "3aa2526eeacf4f599a46be26ee4978cd":{
      "scriptId":"u20"},
    "8e6e6135a89048e0993d7c8d2bd99371":{
      "scriptId":"u21"},
    "cdd62ce9809549daa13dd04542debcb0":{
      "scriptId":"u22"},
    "bb584df297694bbb997da06c9f7ee2ef":{
      "scriptId":"u23"},
    "cb3c453225fd45c1bbb67b16f1ffd3f8":{
      "scriptId":"u24"},
    "7ea211596f9c47a0a2d4f8f52e79ad66":{
      "scriptId":"u25"},
    "d98c4cebb01d4e21bd2a07fb619a4093":{
      "scriptId":"u26"},
    "7f97c1ad44804ce4ba989e3dc2f38f0d":{
      "scriptId":"u27"},
    "7ad384ab4e8a4d59aacfad3c57aec146":{
      "scriptId":"u28"},
    "5099152ddfb74de485f53d1c9f7a2642":{
      "scriptId":"u29"},
    "83aebffb4593450c93f843f4d93dd520":{
      "scriptId":"u30"},
    "7ea8189267064221bcb8b76b163151f4":{
      "scriptId":"u31"},
    "d147528a2ff843c39575dc1369c1600f":{
      "scriptId":"u32"},
    "0908d02652d045d5afe6214a2cc185ea":{
      "scriptId":"u33"},
    "b43a2aa778c14d4aa8bd3fec9fc02872":{
      "scriptId":"u34"},
    "0e4be9341ae94976bc382574c3bbb5eb":{
      "scriptId":"u35"},
    "377516b3cf274128b35f156b5a23101f":{
      "scriptId":"u36"},
    "5700b028a76947ac90a2cbd0cf438210":{
      "scriptId":"u37"},
    "a826a1f4aa604ea4a0af21c0dfdb173e":{
      "scriptId":"u38"},
    "a4046ea036ae41ea889632016bdbc8a0":{
      "scriptId":"u39"},
    "71451642950945a4a2d4b6e9096fb015":{
      "scriptId":"u40"},
    "d66a782325c44cd7b582e1559247ae6f":{
      "scriptId":"u41"},
    "8594d1c4c9164a8aa26f73631fdc417c":{
      "scriptId":"u42"},
    "02768ae0a4cd405995aa4d342a18a8b3":{
      "scriptId":"u43"},
    "cd6c562bf589444e91ff942527921ff2":{
      "scriptId":"u44"},
    "16ba9622f97f41a2a1db980c5e63b175":{
      "scriptId":"u45"},
    "0d293dfd35d24bb89b0834789fa2be8e":{
      "scriptId":"u46"},
    "7acd5834a8aa4b1796cfbabd04fa3135":{
      "scriptId":"u47"},
    "2df0f7c5cb244b46b7ea7cfde710346a":{
      "scriptId":"u48"},
    "a11a07ed3ce84434ba17321e461c71ea":{
      "scriptId":"u49"},
    "086f88bea3484561a6515099d8b2e05a":{
      "scriptId":"u50"},
    "9afbe27bee4f43a7bc125aedbf5e9f61":{
      "scriptId":"u51"},
    "c0fbbdde8566476b94915f697c5cf9ae":{
      "scriptId":"u52"},
    "815f5ccfc900453c95e0052244ab8001":{
      "scriptId":"u53"},
    "34beafceff7f434aa252faa18c1ba58e":{
      "scriptId":"u54"},
    "274ffc1198c24d458bdaf31754dbd49e":{
      "scriptId":"u55"},
    "ed828ebd58244f1c9366ce221e4ae034":{
      "scriptId":"u56"},
    "42aa9aa82afc4f0296d5ae344e305a8c":{
      "scriptId":"u57"},
    "0cac02574c1b449e86999134ded33768":{
      "scriptId":"u58"},
    "683c265d92b94cbfa88ca0222a405a7f":{
      "scriptId":"u59"},
    "6c884b7053bf4b07a92e7da7848830d5":{
      "scriptId":"u60"},
    "351f89c718344d0d9c5ed5138349b14b":{
      "scriptId":"u61"},
    "d649e728e0364b989ffeb2d0fa53179d":{
      "scriptId":"u62"},
    "96386648ad034e5cba17dddfd0e3563a":{
      "scriptId":"u63"},
    "e40028b6b6b148a4841102e3f2cc791e":{
      "scriptId":"u64"},
    "c7bd9987f1f64c6ca1fc7f341680fa41":{
      "scriptId":"u65"},
    "7139a8f210424178a62f1934051b75aa":{
      "scriptId":"u66"},
    "324f08e94276461aa41d78289138fba8":{
      "scriptId":"u67"},
    "a9a20ca4c7bc41e6a40e7e5fb8c451eb":{
      "scriptId":"u68"},
    "30c5eb3ee8b44f76ad88fadfacdcba54":{
      "scriptId":"u69"},
    "a8ee147dd43242ca8574b412c4ba483d":{
      "scriptId":"u70"},
    "02e19815b0b14a31adc5dd3767a5890f":{
      "scriptId":"u71"},
    "d0de73b6ccad46da879acf307b590576":{
      "scriptId":"u72"},
    "9df5fce9505247f2bdcc5c9eaeb3902f":{
      "scriptId":"u73"},
    "c1d39c60e58d4a9c8e4512bce506be74":{
      "scriptId":"u74"},
    "bfd7658e0ccb48b2ac84df38be6660b9":{
      "scriptId":"u75"},
    "696eade4c52f416c89d126d98f602daf":{
      "scriptId":"u76"},
    "b4cc3de2c56e42daba24e430c68a2b1f":{
      "scriptId":"u77"},
    "09b285dd6e414a4d9e88cbd3836ecdc9":{
      "scriptId":"u78"},
    "4eed59966d5e49fbaabbf2c724f7b05e":{
      "scriptId":"u79"},
    "15a8fc1a9f754c2eb2f03d51886efab6":{
      "scriptId":"u80"},
    "c9f7fd9f698a4522ac98c56e3b2b4ff4":{
      "scriptId":"u81"},
    "7245bb66e9d0458a9f9d4b49c0dd1865":{
      "scriptId":"u82"},
    "3066e9c0207e4986873c6fa557fbbe6e":{
      "scriptId":"u83"},
    "f2b5dbab1e4f4901b355fa02bd9fd53a":{
      "scriptId":"u84"},
    "32c82532685a4d08b879e726be599cd6":{
      "scriptId":"u85"},
    "a093df17d06843f68fcf86520e96fdbe":{
      "scriptId":"u86"},
    "922d179deaad41a39dac00969c6bb8a4":{
      "scriptId":"u87"},
    "666b3ec221874425a20a94b3eb079794":{
      "scriptId":"u88"},
    "54879e419a8043f29d7ebfa06e56fcd1":{
      "scriptId":"u89"},
    "6418ceb8371f40209a35279d123d6264":{
      "scriptId":"u90"},
    "e0a2164c2ba64a7bab9113d894c74ad3":{
      "scriptId":"u91"},
    "ea400d3aad354e27924f6f41f339b0e8":{
      "scriptId":"u92"},
    "1d2e6ec1362741e2a385e5ab06b3bcb4":{
      "scriptId":"u93"},
    "3cbba2952b134c6e808d6f438ef462e4":{
      "scriptId":"u94"},
    "d54bc4a7d6d747dd88a14bad7830b9b5":{
      "scriptId":"u95"},
    "2fc3ee30eced443d8a911213c3bb7b86":{
      "scriptId":"u96"},
    "126b8e4cade2477bb261248b31d62d19":{
      "scriptId":"u97"},
    "882fc2de57ae4e81a91fafcffdf205db":{
      "scriptId":"u98"},
    "51e593c87b70410dba8979e8de78f3a1":{
      "scriptId":"u99"},
    "27cc5d4771084e3aa182debda188219b":{
      "scriptId":"u100"},
    "792a27c19df148dba2cfb59f62ec1fc8":{
      "scriptId":"u101"},
    "a55cae6839b141e69e0fced94a00840b":{
      "scriptId":"u102"},
    "0f8e12fb2c844782a5cce419ed1be44a":{
      "scriptId":"u103"},
    "58dd55f774c74768816baeb5b37a36cb":{
      "scriptId":"u104"},
    "8560b735aa7d4295b78360d4902842bb":{
      "scriptId":"u105"},
    "c1671bb3fd5d4cc299148f539cd3739e":{
      "scriptId":"u106"},
    "be38b5a243184d0186915c4404469833":{
      "scriptId":"u107"},
    "47389a3391c54702bb43c67da119f02a":{
      "scriptId":"u108"}}});