$axure.loadCurrentPage({
  "url":"加盟服务.html",
  "generationDate":new Date(1494572348998.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"17988d8eb4894070b436e3167ee3b506",
    "type":"Axure:Page",
    "name":"加盟服务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e7d7afc7a2934aee83cb26a51bea4a5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "size":{
              "width":1150,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f5f08069d7441eba407328032f66bac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "size":{
                  "width":1150,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"93d813d7c8714fda9cd30a55efe440e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF515151,
              "opacity":1},
            "location":{
              "x":20,
              "y":7},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"679c7c8410bf4ca9b12272d299f87e56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":7},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"360eeaf42e5b4e01b2150126c847c7fc",
          "label":"login",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1}}},
            "location":{
              "x":730,
              "y":7},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3736c26700840519715bea8556359a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333,
                      "opacity":1}}},
                "location":{
                  "x":730,
                  "y":7},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["360eeaf42e5b4e01b2150126c847c7fc"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["360eeaf42e5b4e01b2150126c847c7fc"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif"}},
{
          "id":"c30b07676a824b0bbe72b7ecf453d766",
          "label":"2weima",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":1024,
              "y":29},
            "size":{
              "width":126,
              "height":100},
            "visible":false,
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cc495ff11f2406fa42918ebc99b562d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":1024,
                  "y":29},
                "size":{
                  "width":126,
                  "height":100},
                "visible":false,
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/2weima_u10.png"}},
{
          "id":"a9f54c2067304ea8a113dc3fb276bce6",
          "label":"login",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1}}},
            "location":{
              "x":950,
              "y":7},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dda18025346b451cb6b979cdfab24592",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333,
                      "opacity":1}}},
                "location":{
                  "x":950,
                  "y":7},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a9f54c2067304ea8a113dc3fb276bce6"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a9f54c2067304ea8a113dc3fb276bce6"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif"}},
{
          "id":"9778562eb3a74685b61f04fe0b7531a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":34,
              "y":52},
            "size":{
              "width":60,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f42c50491a94eae95723f2e843a4395",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":34,
                  "y":52},
                "size":{
                  "width":60,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc8a0030d54443bd9a4b8f74ec964e62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":64},
            "size":{
              "width":79,
              "height":16},
            "rotation":"353",
            "textRotation":"353"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2becda71907a4afab3bdd66ae91b8982",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":64},
                "size":{
                  "width":79,
                  "height":16},
                "rotation":"353",
                "textRotation":"353"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c82eade6afca4463a118c3c61a4bf712",
          "label":"kefu",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1}}},
            "location":{
              "x":867,
              "y":7},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4cfea0a881241fa93da2b948effc9b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333,
                      "opacity":1}}},
                "location":{
                  "x":867,
                  "y":7},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 kefu = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["c82eade6afca4463a118c3c61a4bf712"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"fadeWidget",
                      "description":"显示 qq 弹出效果",
                      "objectsToFades":[{
                          "objectPath":["3c2a13a5c2d543008e8aab74172d4feb"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"flyout"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 kefu = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["c82eade6afca4463a118c3c61a4bf712"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif"}},
{
          "id":"3c2a13a5c2d543008e8aab74172d4feb",
          "label":"qq",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":867,
              "y":29},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"58e575a718a14fb280e971efdb9e9989",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d4d7ebf1dcc64a5bb52c4e2f27a72d15",
                  "label":"",
                  "parentDynamicPanel":"3c2a13a5c2d543008e8aab74172d4feb",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":100},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a3359914cca40548985ecdfdd0c6565",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c2a13a5c2d543008e8aab74172d4feb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":100},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u21.png"}},
{
                  "id":"637c1f1591044eb4a4365051a3e02026",
                  "label":"",
                  "parentDynamicPanel":"3c2a13a5c2d543008e8aab74172d4feb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF868686,
                      "opacity":1},
                    "location":{
                      "x":23,
                      "y":11},
                    "size":{
                      "width":99,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"979fc00868f240cc80022d6ec3970e52",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c2a13a5c2d543008e8aab74172d4feb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF868686,
                          "opacity":1},
                        "location":{
                          "x":23,
                          "y":11},
                        "size":{
                          "width":99,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1a6278d2e54743998663680acc45dd92",
                  "label":"",
                  "parentDynamicPanel":"3c2a13a5c2d543008e8aab74172d4feb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF868686,
                      "opacity":1},
                    "location":{
                      "x":23,
                      "y":37},
                    "size":{
                      "width":99,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d51393ae76bc4efe9e3a0d5b4a9ce009",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c2a13a5c2d543008e8aab74172d4feb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF868686,
                          "opacity":1},
                        "location":{
                          "x":23,
                          "y":37},
                        "size":{
                          "width":99,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"86723f8343304685a508ccd307bf68d8",
                  "label":"",
                  "parentDynamicPanel":"3c2a13a5c2d543008e8aab74172d4feb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF868686,
                      "opacity":1},
                    "location":{
                      "x":23,
                      "y":63},
                    "size":{
                      "width":99,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4eddef7085a14eee91fee0885d03324e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3c2a13a5c2d543008e8aab74172d4feb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF868686,
                          "opacity":1},
                        "location":{
                          "x":23,
                          "y":63},
                        "size":{
                          "width":99,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"da106e0b9ac1444591cbf9e6a4cfc350",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":230,
              "y":78},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c17185cdef54475e8c20f237b4d83328",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":78},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea0d30ebaa814eb29c02a83f0f3259ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":292,
              "y":78},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0757995c93384a3994f826119ffe55b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":292,
                  "y":78},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 金八力课程",
                      "target":{
                        "targetType":"page",
                        "url":"金八力课程.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f0fff38a1af44a5835d72ee7c9bcde1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":399,
              "y":78},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeb32f0ddf184d3f944c53debdcc8bfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":399,
                  "y":78},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 项目优势",
                      "target":{
                        "targetType":"page",
                        "url":"项目优势.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d895ab27efe48dab06d2fb41d687458",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":590,
              "y":78},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6de9121bea24232968ff419bbd58366",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":590,
                  "y":78},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 校区分布",
                      "target":{
                        "targetType":"page",
                        "url":"校区分布.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f263fec658e42208174f823208657b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3366,
              "opacity":1},
            "location":{
              "x":497,
              "y":78},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47ba25be18d94d348c20d6240afa102d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3366,
                  "opacity":1},
                "location":{
                  "x":497,
                  "y":78},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 加盟服务",
                      "target":{
                        "targetType":"page",
                        "url":"加盟服务.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c93c3c0e1444b7aba45e5d122df82cc",
          "label":"login",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3333,
                  "opacity":1}}},
            "location":{
              "x":795,
              "y":7},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0306cf0fe9bb4bf0b762ed59c91006a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF3333,
                      "opacity":1}}},
                "location":{
                  "x":795,
                  "y":7},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 注册",
                      "target":{
                        "targetType":"page",
                        "url":"注册.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 2",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["7c93c3c0e1444b7aba45e5d122df82cc"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 login = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["7c93c3c0e1444b7aba45e5d122df82cc"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif"}},
{
          "id":"ffb6cd72d319426dbdb12aec4ce208fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":124,
              "y":2910},
            "size":{
              "width":53,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"978c10842788483f86370661f15585c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":124,
                  "y":2910},
                "size":{
                  "width":53,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d76b0949a22f4b669398648f39b997dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":230,
              "y":2916},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb90520a4e56460da3cffddf692e741b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":2916},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8db1a2d02e0042d98bc9ca7e68c6851d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":-6,
              "y":1257},
            "size":{
              "width":1165,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6c9757b71c54106ab53f2a9603878b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":-6,
                  "y":1257},
                "size":{
                  "width":1165,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/视频详情/u41.png"}},
{
          "id":"ad8aa8cb6ad34de0838ee8420802d8e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":124,
              "y":1281},
            "size":{
              "width":53,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dfa17dac6e2454c96c0a783a785836b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":124,
                  "y":1281},
                "size":{
                  "width":53,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5807bebd094c4b4fa2dcec08f1bd0fbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":230,
              "y":1287},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c82caf6a19b34bf0a9abd69209d11749",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":1287},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96c712bca93a4e8bbae6d099e70a1d4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":788,
              "y":-30},
            "size":{
              "width":177,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bd3b1e084894647a7edeea336389f86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":788,
                  "y":-30},
                "size":{
                  "width":177,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6034ad396d6743659f1cfa396afb011c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF5E5E5E,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFAEAEAE},
            "location":{
              "x":43.5,
              "y":210},
            "size":{
              "width":41,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72b351fb37eb4cde8f1b2c33119f789b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF5E5E5E,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE},
                "location":{
                  "x":43.5,
                  "y":210},
                "size":{
                  "width":41,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/加盟服务/u49.png"}},
{
          "id":"4ac989676e8147b389c4521445c8b1a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":44,
              "y":299},
            "size":{
              "width":41,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd26774446684c48a9b01cdcc6c3b21b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":299},
                "size":{
                  "width":41,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/加盟服务/u51.png"}},
{
          "id":"5ce3b12e265949ddb1fe9f7660a1f90c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":44,
              "y":341},
            "size":{
              "width":41,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37b0d19a456744469b92032a47e3d9ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":341},
                "size":{
                  "width":41,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/加盟服务/u51.png"}},
{
          "id":"70bacae754cd4e59989bd9fb7535bb8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":44,
              "y":383},
            "size":{
              "width":41,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e27fbd8f9834bffb3f1ecb4909cb25d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":383},
                "size":{
                  "width":41,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/加盟服务/u51.png"}},
{
          "id":"9aab4cd02bb1494abf83ad910dcb0c5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":44,
              "y":425},
            "size":{
              "width":41,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19f9b305c8e74667b1a81f800fe209af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":425},
                "size":{
                  "width":41,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/加盟服务/u51.png"}},
{
          "id":"50e37df11a3c421eb2eaf5b66c9b3b9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":44,
              "y":467},
            "size":{
              "width":41,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c6e74b186794586b6addb8bbf1727c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":467},
                "size":{
                  "width":41,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/加盟服务/u51.png"}},
{
          "id":"9dc2fc61e6704458a6e587251f70286e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":44,
              "y":509},
            "size":{
              "width":41,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81e3c1d89cc548df8fd88f1a9cb37cfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":509},
                "size":{
                  "width":41,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/加盟服务/u51.png"}},
{
          "id":"355ac969dd5c4335a52e431f81e218de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":200},
            "size":{
              "width":990,
              "height":640},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c2251eeb6184ffbbc05f5126c7aaf6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":200},
                "size":{
                  "width":990,
                  "height":640},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/加盟服务/u63.png"}},
{
          "id":"a025b4e0cbf248d99ad335c0701c8436",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":140,
              "y":210},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c1159d987514114acee907cc4ab31cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":210},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"225fa783f95844ad850fb9d1241363b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3366FF,
              "opacity":1},
            "location":{
              "x":267,
              "y":175},
            "size":{
              "width":157,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f505ff6a7ca746b186fa455a0681ce11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF,
                  "opacity":1},
                "location":{
                  "x":267,
                  "y":175},
                "size":{
                  "width":157,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e7d7afc7a2934aee83cb26a51bea4a5d":{
      "scriptId":"u0"},
    "9f5f08069d7441eba407328032f66bac":{
      "scriptId":"u1"},
    "93d813d7c8714fda9cd30a55efe440e0":{
      "scriptId":"u2"},
    "679c7c8410bf4ca9b12272d299f87e56":{
      "scriptId":"u3"},
    "360eeaf42e5b4e01b2150126c847c7fc":{
      "scriptId":"u4"},
    "b3736c26700840519715bea8556359a8":{
      "scriptId":"u5"},
    "c30b07676a824b0bbe72b7ecf453d766":{
      "scriptId":"u6"},
    "1cc495ff11f2406fa42918ebc99b562d":{
      "scriptId":"u7"},
    "a9f54c2067304ea8a113dc3fb276bce6":{
      "scriptId":"u8"},
    "dda18025346b451cb6b979cdfab24592":{
      "scriptId":"u9"},
    "9778562eb3a74685b61f04fe0b7531a0":{
      "scriptId":"u10"},
    "3f42c50491a94eae95723f2e843a4395":{
      "scriptId":"u11"},
    "bc8a0030d54443bd9a4b8f74ec964e62":{
      "scriptId":"u12"},
    "2becda71907a4afab3bdd66ae91b8982":{
      "scriptId":"u13"},
    "c82eade6afca4463a118c3c61a4bf712":{
      "scriptId":"u14"},
    "d4cfea0a881241fa93da2b948effc9b7":{
      "scriptId":"u15"},
    "3c2a13a5c2d543008e8aab74172d4feb":{
      "scriptId":"u16"},
    "d4d7ebf1dcc64a5bb52c4e2f27a72d15":{
      "scriptId":"u17"},
    "7a3359914cca40548985ecdfdd0c6565":{
      "scriptId":"u18"},
    "637c1f1591044eb4a4365051a3e02026":{
      "scriptId":"u19"},
    "979fc00868f240cc80022d6ec3970e52":{
      "scriptId":"u20"},
    "1a6278d2e54743998663680acc45dd92":{
      "scriptId":"u21"},
    "d51393ae76bc4efe9e3a0d5b4a9ce009":{
      "scriptId":"u22"},
    "86723f8343304685a508ccd307bf68d8":{
      "scriptId":"u23"},
    "4eddef7085a14eee91fee0885d03324e":{
      "scriptId":"u24"},
    "da106e0b9ac1444591cbf9e6a4cfc350":{
      "scriptId":"u25"},
    "c17185cdef54475e8c20f237b4d83328":{
      "scriptId":"u26"},
    "ea0d30ebaa814eb29c02a83f0f3259ca":{
      "scriptId":"u27"},
    "0757995c93384a3994f826119ffe55b1":{
      "scriptId":"u28"},
    "2f0fff38a1af44a5835d72ee7c9bcde1":{
      "scriptId":"u29"},
    "eeb32f0ddf184d3f944c53debdcc8bfa":{
      "scriptId":"u30"},
    "2d895ab27efe48dab06d2fb41d687458":{
      "scriptId":"u31"},
    "e6de9121bea24232968ff419bbd58366":{
      "scriptId":"u32"},
    "7f263fec658e42208174f823208657b8":{
      "scriptId":"u33"},
    "47ba25be18d94d348c20d6240afa102d":{
      "scriptId":"u34"},
    "7c93c3c0e1444b7aba45e5d122df82cc":{
      "scriptId":"u35"},
    "0306cf0fe9bb4bf0b762ed59c91006a2":{
      "scriptId":"u36"},
    "ffb6cd72d319426dbdb12aec4ce208fc":{
      "scriptId":"u37"},
    "978c10842788483f86370661f15585c6":{
      "scriptId":"u38"},
    "d76b0949a22f4b669398648f39b997dd":{
      "scriptId":"u39"},
    "eb90520a4e56460da3cffddf692e741b":{
      "scriptId":"u40"},
    "8db1a2d02e0042d98bc9ca7e68c6851d":{
      "scriptId":"u41"},
    "a6c9757b71c54106ab53f2a9603878b9":{
      "scriptId":"u42"},
    "ad8aa8cb6ad34de0838ee8420802d8e8":{
      "scriptId":"u43"},
    "9dfa17dac6e2454c96c0a783a785836b":{
      "scriptId":"u44"},
    "5807bebd094c4b4fa2dcec08f1bd0fbd":{
      "scriptId":"u45"},
    "c82caf6a19b34bf0a9abd69209d11749":{
      "scriptId":"u46"},
    "96c712bca93a4e8bbae6d099e70a1d4f":{
      "scriptId":"u47"},
    "5bd3b1e084894647a7edeea336389f86":{
      "scriptId":"u48"},
    "6034ad396d6743659f1cfa396afb011c":{
      "scriptId":"u49"},
    "72b351fb37eb4cde8f1b2c33119f789b":{
      "scriptId":"u50"},
    "4ac989676e8147b389c4521445c8b1a5":{
      "scriptId":"u51"},
    "dd26774446684c48a9b01cdcc6c3b21b":{
      "scriptId":"u52"},
    "5ce3b12e265949ddb1fe9f7660a1f90c":{
      "scriptId":"u53"},
    "37b0d19a456744469b92032a47e3d9ca":{
      "scriptId":"u54"},
    "70bacae754cd4e59989bd9fb7535bb8c":{
      "scriptId":"u55"},
    "2e27fbd8f9834bffb3f1ecb4909cb25d":{
      "scriptId":"u56"},
    "9aab4cd02bb1494abf83ad910dcb0c5f":{
      "scriptId":"u57"},
    "19f9b305c8e74667b1a81f800fe209af":{
      "scriptId":"u58"},
    "50e37df11a3c421eb2eaf5b66c9b3b9a":{
      "scriptId":"u59"},
    "4c6e74b186794586b6addb8bbf1727c3":{
      "scriptId":"u60"},
    "9dc2fc61e6704458a6e587251f70286e":{
      "scriptId":"u61"},
    "81e3c1d89cc548df8fd88f1a9cb37cfd":{
      "scriptId":"u62"},
    "355ac969dd5c4335a52e431f81e218de":{
      "scriptId":"u63"},
    "5c2251eeb6184ffbbc05f5126c7aaf6c":{
      "scriptId":"u64"},
    "a025b4e0cbf248d99ad335c0701c8436":{
      "scriptId":"u65"},
    "5c1159d987514114acee907cc4ab31cc":{
      "scriptId":"u66"},
    "225fa783f95844ad850fb9d1241363b9":{
      "scriptId":"u67"},
    "f505ff6a7ca746b186fa455a0681ce11":{
      "scriptId":"u68"}}});