$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1494572349117.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"66dd9a4183914d52817adafbda18e4e1",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"27be4219902e4b959bfff2be146f8f32",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":130},
            "size":{
              "width":1139,
              "height":490}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a41ec4953c574bbfa7063387bc7cb2b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":130},
                "size":{
                  "width":1139,
                  "height":490}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"328a52d90c574d10be256f56beecd904",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":40},
            "size":{
              "width":68,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e41091babc814ea5a7b84e81bbd4cdd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":40},
                "size":{
                  "width":68,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f5b73f3bd5b48bfbd162632561e901c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":795,
              "y":357},
            "size":{
              "width":235,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eece61b6f0034edab69279cb6bee6ef8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":795,
                  "y":357},
                "size":{
                  "width":235,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u4.png"}},
{
          "id":"fbca8ece766045cfa96bdfd76ca83b0a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":764,
              "y":478},
            "size":{
              "width":296,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3117fd200a17456f9b6e4dde19dd876c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":764,
                  "y":478},
                "size":{
                  "width":296,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u6.png"}},
{
          "id":"3cf0439b24704ebeb807c9ae1eb3a939",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":795,
              "y":439},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00bbde955f35409c901cb7abab649c62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":795,
                  "y":439},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3cf2111e86b4cd685c05ec4555ff10b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":966,
              "y":439},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2f1e98e9e724d2e9cc924ab09161112",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":966,
                  "y":439},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90dc78a3cb3d4b12876a29a9dd8dd195",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":795,
              "y":389},
            "size":{
              "width":235,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"e627181afc914d6d91fc8cc6ea7dff3b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":795,
              "y":439},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 注册",
                      "target":{
                        "targetType":"page",
                        "url":"注册.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "27be4219902e4b959bfff2be146f8f32":{
      "scriptId":"u0"},
    "a41ec4953c574bbfa7063387bc7cb2b4":{
      "scriptId":"u1"},
    "328a52d90c574d10be256f56beecd904":{
      "scriptId":"u2"},
    "e41091babc814ea5a7b84e81bbd4cdd7":{
      "scriptId":"u3"},
    "6f5b73f3bd5b48bfbd162632561e901c":{
      "scriptId":"u4"},
    "eece61b6f0034edab69279cb6bee6ef8":{
      "scriptId":"u5"},
    "fbca8ece766045cfa96bdfd76ca83b0a":{
      "scriptId":"u6"},
    "3117fd200a17456f9b6e4dde19dd876c":{
      "scriptId":"u7"},
    "3cf0439b24704ebeb807c9ae1eb3a939":{
      "scriptId":"u8"},
    "00bbde955f35409c901cb7abab649c62":{
      "scriptId":"u9"},
    "e3cf2111e86b4cd685c05ec4555ff10b":{
      "scriptId":"u10"},
    "d2f1e98e9e724d2e9cc924ab09161112":{
      "scriptId":"u11"},
    "90dc78a3cb3d4b12876a29a9dd8dd195":{
      "scriptId":"u12"},
    "e627181afc914d6d91fc8cc6ea7dff3b":{
      "scriptId":"u13"}}});