$axure.loadCurrentPage({
  "url":"分享添加照片.html",
  "generationDate":new Date(1494572329426.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7f7d99d805944165a0d889f6e792165d",
    "type":"Axure:Page",
    "name":"分享添加照片",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"62ae0ad8ecb04e32ab869bf62e170b54",
          "label":"tushangchuan",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":40,
              "y":280},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"af5447f60e604f92ae3544bca821e07a",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"45be404e26ed408a9c62e1e0b03e6d13",
                  "label":"",
                  "parentDynamicPanel":"62ae0ad8ecb04e32ab869bf62e170b54",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE,
                      "opacity":1},
                    "size":{
                      "width":130,
                      "height":140},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ed51e71a25144367b5142f3d94df7198",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"62ae0ad8ecb04e32ab869bf62e170b54",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFAEAEAE,
                          "opacity":1},
                        "size":{
                          "width":130,
                          "height":140},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 delect 向上滑动 500 ms 弹出效果",
                              "objectsToFades":[{
                                  "objectPath":["d8b9e5bfc43647c791457753bb8d0f9d"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"slideUp",
                                      "duration":500,
                                      "showType":"flyout"}}}]}]}]}},
                  "images":{
                    "normal~":"images/分享添加照片/u1.png"}},
{
                  "id":"d8b9e5bfc43647c791457753bb8d0f9d",
                  "label":"delect",
                  "parentDynamicPanel":"62ae0ad8ecb04e32ab869bf62e170b54",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xA3000000},
                    "size":{
                      "width":130,
                      "height":140},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e0fe6e0f72194c4480bd1e01e143b36f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"62ae0ad8ecb04e32ab869bf62e170b54",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xA3000000},
                        "size":{
                          "width":130,
                          "height":140},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/分享添加照片/delect_u3.png"}}]}]},
{
          "id":"6096297bc7154914b1342ccc780eb285",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":55},
            "size":{
              "width":736,
              "height":167}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41d84afdae1a4bc0a1d8f069c438333a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":55},
                "size":{
                  "width":736,
                  "height":167}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/授课/u0.png"}},
{
          "id":"f8dc8905811c4551be2ab414e5cddae7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":65},
            "size":{
              "width":97,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af5b83931dc2416f8603ac4d171f5df6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":65},
                "size":{
                  "width":97,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/授课/u2.png"}},
{
          "id":"ce68b14f346f490ab60291e576e4dd54",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":65},
            "size":{
              "width":97,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7817be5443d404cbdadbd0ab18ae222",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":65},
                "size":{
                  "width":97,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/授课/u2.png"}},
{
          "id":"3efd9b7de800443eba3680523dfc7434",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":81},
            "size":{
              "width":97,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"089194320bab41e4bfc8dcd04d5058cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":81},
                "size":{
                  "width":97,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/授课/u2.png"}},
{
          "id":"b92677be57884b45b7769096297829c9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":84},
            "size":{
              "width":97,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee2e8e45ed504d8785d19dfd5a7eede3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":84},
                "size":{
                  "width":97,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/授课/u2.png"}},
{
          "id":"bd3e1e0852984befb29da18c3096e874",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":123,
              "y":70},
            "size":{
              "width":93,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3799b9e0db3749e2a782fb274d27794b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":123,
                  "y":70},
                "size":{
                  "width":93,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8729dea61db54d419b0c183e7ec1dbac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF434343,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xE2AEDE7B},
            "location":{
              "x":235,
              "y":126},
            "size":{
              "width":60,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF8CC55A},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"952fc31dc41044ae874e00ee55322a7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF434343,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xE2AEDE7B},
                "location":{
                  "x":235,
                  "y":126},
                "size":{
                  "width":60,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF8CC55A},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页/授课",
                      "target":{
                        "targetType":"page",
                        "url":"首页_授课.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/授课/u34.png"}},
{
          "id":"c7956a4fa4184358a3bb8fd30afbb53b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF515151,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFABDD75},
            "location":{
              "x":295,
              "y":122},
            "size":{
              "width":60,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF8CC55A},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a452d666038444e2b61e95b2eb8c03b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF515151,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFABDD75},
                "location":{
                  "x":295,
                  "y":122},
                "size":{
                  "width":60,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF8CC55A},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 授课",
                      "target":{
                        "targetType":"page",
                        "url":"授课.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/课表管理/u34.png"}},
{
          "id":"a23db41b7c2346529a072ae5240d5e05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF434343,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFAEDE7B},
            "location":{
              "x":355,
              "y":126},
            "size":{
              "width":60,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF8CC55A},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a7f481d24b34c0c8fc0d5fca2156b48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF434343,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFAEDE7B},
                "location":{
                  "x":355,
                  "y":126},
                "size":{
                  "width":60,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF8CC55A},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课表管理",
                      "target":{
                        "targetType":"page",
                        "url":"课表管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/分享_班级/u16.png"}},
{
          "id":"cc2111f7abbf4343927aaf078ed1c93f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF235E4D},
            "location":{
              "x":415,
              "y":122},
            "size":{
              "width":60,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF8CC55A},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bf21a09a5aa4532a7f3daa2015c98cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF235E4D},
                "location":{
                  "x":415,
                  "y":122},
                "size":{
                  "width":60,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF8CC55A},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 分享/班级",
                      "target":{
                        "targetType":"page",
                        "url":"分享_班级.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/分享_班级/u18.png"}},
{
          "id":"ae369cee111d496fbd7aed054b9a87cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF434343,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xE2AEDE7B},
            "location":{
              "x":475,
              "y":122},
            "size":{
              "width":60,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF8CC55A},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"449956e1db4945b29ca1dc23ad235a9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF434343,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xE2AEDE7B},
                "location":{
                  "x":475,
                  "y":122},
                "size":{
                  "width":60,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF8CC55A},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 记录/学员聊天",
                      "target":{
                        "targetType":"page",
                        "url":"记录_学员聊天.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/授课/u34.png"}},
{
          "id":"82fd0fc133a740cba6b0fc7585b5c592",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF434343,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xE2AEDE7B},
            "location":{
              "x":535,
              "y":126},
            "size":{
              "width":60,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF8CC55A},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"257bfa144c394a1d9bbd23ac8094f3e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF434343,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xE2AEDE7B},
                "location":{
                  "x":535,
                  "y":126},
                "size":{
                  "width":60,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF8CC55A},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 设置/个人中心",
                      "target":{
                        "targetType":"page",
                        "url":"设置_个人中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/授课/u34.png"}},
{
          "id":"d8e6cb2588f34bb5be646e9d666f2f9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3300FF,
              "opacity":1},
            "location":{
              "x":780,
              "y":84},
            "size":{
              "width":170,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a337c128a34e40a88ca70e08cca38ea4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF,
                  "opacity":1},
                "location":{
                  "x":780,
                  "y":84},
                "size":{
                  "width":170,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abf8e4e01916419c8a6ff3d926551a06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":164,
              "y":214},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9119f25c725c4d1eb51d9ec520f73057",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":164,
                  "y":214},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2d1d4b9f6144bebb30ff86b78489147",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3366FF,
              "opacity":1},
            "location":{
              "x":254,
              "y":195},
            "size":{
              "width":57,
              "height":16},
            "rotation":"353",
            "textRotation":"353"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb0708c0f2d7453a9d46befb4504ef7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF,
                  "opacity":1},
                "location":{
                  "x":254,
                  "y":195},
                "size":{
                  "width":57,
                  "height":16},
                "rotation":"353",
                "textRotation":"353"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43605d1d077c4de8be87bfc70aa16633",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":343,
              "y":191},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61a8f7c453724e87b38859d0638319dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":343,
                  "y":191},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c08d25beccf405496aad06e824bf09e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":450,
              "y":191},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6f2783b74294187b78ea480ee596853",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":450,
                  "y":191},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ee21398caca40bcb9c49f6849e6122a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9,
              "opacity":1},
            "location":{
              "x":770,
              "y":270},
            "size":{
              "width":64,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"023184d157594efc97e451c85a969e93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9,
                  "opacity":1},
                "location":{
                  "x":770,
                  "y":270},
                "size":{
                  "width":64,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 班级照分享",
                      "target":{
                        "targetType":"page",
                        "url":"班级照分享.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/班级照分享/u34.png"}},
{
          "id":"2750d851485a466babc6b028acc7ded0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3300FF,
              "opacity":1},
            "location":{
              "x":688,
              "y":754},
            "size":{
              "width":183,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3014b28b8a7347cbad32e15142fe9adc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3300FF,
                  "opacity":1},
                "location":{
                  "x":688,
                  "y":754},
                "size":{
                  "width":183,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4add3aa4b86a4e8fb595f6f1b23b5506",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":900},
            "size":{
              "width":832,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e362498461d14a9fbc1619858f676d70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":900},
                "size":{
                  "width":832,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/备课/u131.png"}},
{
          "id":"dd580743eb1c4212b37963cf76f17437",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF336666,
              "opacity":1},
            "location":{
              "x":58,
              "y":913},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"756f189af9384e99bc0edee7ac448c64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF336666,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":913},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"466d70f030f34719a18d56d0d397a67c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9,
              "opacity":1},
            "location":{
              "x":697,
              "y":270},
            "size":{
              "width":64,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1304691261434e05baf3e53acb2bb371",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9,
                  "opacity":1},
                "location":{
                  "x":697,
                  "y":270},
                "size":{
                  "width":64,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 zhaopdiv",
                      "objectsToFades":[{
                          "objectPath":["03d09694502448e488ea312f0065e222"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/班级照分享/u34.png"}},
{
          "id":"74a4f636da3549b586c0d51cd506cec1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3333FF,
              "opacity":1},
            "location":{
              "x":33,
              "y":500},
            "size":{
              "width":304,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15738f1c8e954ea0b67f7011d3c57ab1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3333FF,
                  "opacity":1},
                "location":{
                  "x":33,
                  "y":500},
                "size":{
                  "width":304,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53981f2639f8475997d637f7f2d6794c",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":69,
              "y":280},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 tushangchuan 推 部件 right",
                      "objectsToFades":[{
                          "objectPath":["62ae0ad8ecb04e32ab869bf62e170b54"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"compress",
                              "vertical":false,
                              "compressEasing":"none",
                              "compressDuration":500}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"cbf9025d88b94324bad753b4fc529332",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5510e4d6c97a43de9b016c4d5af4cb64",
                  "label":"",
                  "parentDynamicPanel":"53981f2639f8475997d637f7f2d6794c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":130,
                      "height":140},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9},
                    "linePattern":"dotted"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8a8ffaa5768849edbc83dd6688cffef7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"53981f2639f8475997d637f7f2d6794c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":130,
                          "height":140},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9},
                        "linePattern":"dotted"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/分享添加照片/u52.png"}},
{
                  "id":"8e088f9bb02441e38086211ec3140b69",
                  "label":"",
                  "parentDynamicPanel":"53981f2639f8475997d637f7f2d6794c",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":29.5,
                      "y":60},
                    "size":{
                      "width":71,
                      "height":10},
                    "borderWidth":"3",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/添加照片页/u66_line.png"}},
{
                  "id":"0570b9a736d14c82bf2077c6ae3f368b",
                  "label":"",
                  "parentDynamicPanel":"53981f2639f8475997d637f7f2d6794c",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":29.5,
                      "y":60},
                    "size":{
                      "width":71,
                      "height":10},
                    "rotation":"90",
                    "borderWidth":"3",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/添加照片页/u66_line.png"}}]}]},
{
          "id":"03d09694502448e488ea312f0065e222",
          "label":"zhaopdiv",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":257,
              "y":272},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"591a34e1870b4bf6b11a77eeb6584f08",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"966a2bedf5ee4af3b259e8d76adcfee6",
                  "label":"",
                  "parentDynamicPanel":"03d09694502448e488ea312f0065e222",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":338,
                      "height":169},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9582321325f4a0da6bd93897559c3b6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03d09694502448e488ea312f0065e222",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":338,
                          "height":169},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/分享添加照片/u57.png"}},
{
                  "id":"56f75fe29ec34fc18293d4aae7fd4708",
                  "label":"",
                  "parentDynamicPanel":"03d09694502448e488ea312f0065e222",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFA1A1A1,
                      "opacity":1},
                    "location":{
                      "x":86,
                      "y":49},
                    "size":{
                      "width":161,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c5b333cfd2684305a29b26c64c6d6fa1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03d09694502448e488ea312f0065e222",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFA1A1A1,
                          "opacity":1},
                        "location":{
                          "x":86,
                          "y":49},
                        "size":{
                          "width":161,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d8b7117e3782471c8ca83f49c0e35eab",
                  "label":"",
                  "parentDynamicPanel":"03d09694502448e488ea312f0065e222",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE,
                      "opacity":1},
                    "location":{
                      "x":80.5,
                      "y":108},
                    "size":{
                      "width":68,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"67c20dcd34844e86876f4994124391dc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03d09694502448e488ea312f0065e222",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFAEAEAE,
                          "opacity":1},
                        "location":{
                          "x":80.5,
                          "y":108},
                        "size":{
                          "width":68,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 zhaopdiv to 状态2",
                              "panelsToStates":[{
                                  "panelPath":["03d09694502448e488ea312f0065e222"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"wait",
                              "description":"等待3000毫秒",
                              "waitTime":3000},
{
                              "action":"setPanelState",
                              "description":"设置 zhaopdiv to 状态1",
                              "panelsToStates":[{
                                  "panelPath":["03d09694502448e488ea312f0065e222"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 班级照分享",
                              "target":{
                                "targetType":"page",
                                "url":"班级照分享.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/分享添加照片/u61.png"}},
{
                  "id":"3ae5f3ff18c943d1a116f524a9f02b10",
                  "label":"",
                  "parentDynamicPanel":"03d09694502448e488ea312f0065e222",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE,
                      "opacity":1},
                    "location":{
                      "x":182,
                      "y":108},
                    "size":{
                      "width":68,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"001f0d522331480fafa9ccd374b34d7d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03d09694502448e488ea312f0065e222",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFAEAEAE,
                          "opacity":1},
                        "location":{
                          "x":182,
                          "y":108},
                        "size":{
                          "width":68,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 zhaopdiv",
                              "objectsToFades":[{
                                  "objectPath":["03d09694502448e488ea312f0065e222"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/分享添加照片/u61.png"}}]},
{
              "id":"6df589c1544644848512a74c4ba9a920",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1f3f3e718c2543e3afb8392eebf1405c",
                  "label":"",
                  "parentDynamicPanel":"03d09694502448e488ea312f0065e222",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":338,
                      "height":169},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5330f0738a104fa1b52ae55394a9f5f9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03d09694502448e488ea312f0065e222",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":338,
                          "height":169},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/分享添加照片/u57.png"}},
{
                  "id":"a0f5827e01f4496eabed74b5bcf0c022",
                  "label":"",
                  "parentDynamicPanel":"03d09694502448e488ea312f0065e222",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFA1A1A1,
                      "opacity":1},
                    "location":{
                      "x":105,
                      "y":58},
                    "size":{
                      "width":113,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ed141c8f38424956aa114f991d09e053",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"03d09694502448e488ea312f0065e222",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFA1A1A1,
                          "opacity":1},
                        "location":{
                          "x":105,
                          "y":58},
                        "size":{
                          "width":113,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"fd171b9e17a742f1a5324c732aa49c84",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":219,
              "y":41},
            "size":{
              "width":77,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF33CCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/备课/u137_line.png"}},
{
          "id":"90523a7460ed4839beb276b97b80a3f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":740,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10f308ee4d904e3f88f8cf0afe2f6359",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":740,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/授课/u104.png"}},
{
          "id":"cd352154540e44d590b1891d4c058ca4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":9},
            "size":{
              "width":68,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2c1db38493747e78cdf32741c5a3745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":9},
                "size":{
                  "width":68,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2df243d149bd4ec98279c072b90eaf3f",
          "label":"beike",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":119,
              "y":14},
            "size":{
              "width":80,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f18959c209cb43b68235451e2e98e0b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":119,
                  "y":14},
                "size":{
                  "width":80,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 备课",
                      "target":{
                        "targetType":"page",
                        "url":"备课.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 beike = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2df243d149bd4ec98279c072b90eaf3f"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 beike = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2df243d149bd4ec98279c072b90eaf3f"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/备课/beike_u6.png",
            "selected~":"images/备课/beike_u6_selected.png"}},
{
          "id":"74df74cbfa0f490a9ee6a6ad4a476f63",
          "label":"souke",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":215,
              "y":14},
            "size":{
              "width":80,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2a7eba179b84bd4b4ac57bb3d0ee7e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":215,
                  "y":14},
                "size":{
                  "width":80,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页/授课",
                      "target":{
                        "targetType":"page",
                        "url":"首页_授课.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 souke = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["74df74cbfa0f490a9ee6a6ad4a476f63"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 souke = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["74df74cbfa0f490a9ee6a6ad4a476f63"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/备课/beike_u6.png",
            "selected~":"images/备课/beike_u6_selected.png"}},
{
          "id":"8a5dd02c2a3c43b4af504042623c9f48",
          "label":"guanli",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":310,
              "y":14},
            "size":{
              "width":80,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a374f2ccac446f294cb962b051334e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":310,
                  "y":14},
                "size":{
                  "width":80,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 校内管理",
                      "target":{
                        "targetType":"page",
                        "url":"校内管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 guanli = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8a5dd02c2a3c43b4af504042623c9f48"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 guanli = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8a5dd02c2a3c43b4af504042623c9f48"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/备课/beike_u6.png",
            "selected~":"images/备课/beike_u6_selected.png"}},
{
          "id":"ad509970de9e4f60b0e18407237c7d6e",
          "label":"ceping",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":409,
              "y":14},
            "size":{
              "width":80,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e183a31751d49ab9eeefe082da0cceb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":409,
                  "y":14},
                "size":{
                  "width":80,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测评",
                      "target":{
                        "targetType":"page",
                        "url":"测评.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 ceping = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["ad509970de9e4f60b0e18407237c7d6e"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 ceping = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["ad509970de9e4f60b0e18407237c7d6e"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/备课/beike_u6.png",
            "selected~":"images/备课/beike_u6_selected.png"}},
{
          "id":"3a46b3d2b0bb41779a5f6b0aa76c2d79",
          "label":"peixun",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":512,
              "y":14},
            "size":{
              "width":80,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4af598c19d1f42da828d997b98a81b0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":512,
                  "y":14},
                "size":{
                  "width":80,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 培训",
                      "target":{
                        "targetType":"page",
                        "url":"培训.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["3a46b3d2b0bb41779a5f6b0aa76c2d79"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["3a46b3d2b0bb41779a5f6b0aa76c2d79"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/备课/beike_u6.png",
            "selected~":"images/备课/beike_u6_selected.png"}},
{
          "id":"60fcf84404de4198b28e54a9907deb3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":14},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF3399},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf72decab5fd435e951e82c3d5797a1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":14},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF3399},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 user 弹出效果",
                      "objectsToFades":[{
                          "objectPath":["404c6cfb8da64c0ba5f886256558d848"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"flyout"}}}]}]}]}},
          "images":{
            "normal~":"images/首页_授课/u112.png"}},
{
          "id":"404c6cfb8da64c0ba5f886256558d848",
          "label":"user",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":630,
              "y":43},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5ac5bb8612ff47fc9900ffae1d9a5ee3",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"974100f57cef423d859153799e38f895",
                  "label":"",
                  "parentDynamicPanel":"404c6cfb8da64c0ba5f886256558d848",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFA1A1A1,
                      "opacity":1},
                    "size":{
                      "width":90,
                      "height":27},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF3399}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"271e4e8c271d422ba9e55dcc45902a36",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"404c6cfb8da64c0ba5f886256558d848",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFA1A1A1,
                          "opacity":1},
                        "size":{
                          "width":90,
                          "height":27},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF3399}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/备课/u53.png"}},
{
                  "id":"c6c04a4e03ff469aadf4f1f17d6f4834",
                  "label":"",
                  "parentDynamicPanel":"404c6cfb8da64c0ba5f886256558d848",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFA1A1A1,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":26},
                    "size":{
                      "width":90,
                      "height":27},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF3399}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"803c7ae3aa2b46e4abebbf3c8220e2dd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"404c6cfb8da64c0ba5f886256558d848",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFA1A1A1,
                          "opacity":1},
                        "location":{
                          "x":0,
                          "y":26},
                        "size":{
                          "width":90,
                          "height":27},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF3399}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/备课/u53.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "62ae0ad8ecb04e32ab869bf62e170b54":{
      "scriptId":"u0"},
    "45be404e26ed408a9c62e1e0b03e6d13":{
      "scriptId":"u1"},
    "ed51e71a25144367b5142f3d94df7198":{
      "scriptId":"u2"},
    "d8b9e5bfc43647c791457753bb8d0f9d":{
      "scriptId":"u3"},
    "e0fe6e0f72194c4480bd1e01e143b36f":{
      "scriptId":"u4"},
    "6096297bc7154914b1342ccc780eb285":{
      "scriptId":"u5"},
    "41d84afdae1a4bc0a1d8f069c438333a":{
      "scriptId":"u6"},
    "f8dc8905811c4551be2ab414e5cddae7":{
      "scriptId":"u7"},
    "af5b83931dc2416f8603ac4d171f5df6":{
      "scriptId":"u8"},
    "ce68b14f346f490ab60291e576e4dd54":{
      "scriptId":"u9"},
    "a7817be5443d404cbdadbd0ab18ae222":{
      "scriptId":"u10"},
    "3efd9b7de800443eba3680523dfc7434":{
      "scriptId":"u11"},
    "089194320bab41e4bfc8dcd04d5058cb":{
      "scriptId":"u12"},
    "b92677be57884b45b7769096297829c9":{
      "scriptId":"u13"},
    "ee2e8e45ed504d8785d19dfd5a7eede3":{
      "scriptId":"u14"},
    "bd3e1e0852984befb29da18c3096e874":{
      "scriptId":"u15"},
    "3799b9e0db3749e2a782fb274d27794b":{
      "scriptId":"u16"},
    "8729dea61db54d419b0c183e7ec1dbac":{
      "scriptId":"u17"},
    "952fc31dc41044ae874e00ee55322a7c":{
      "scriptId":"u18"},
    "c7956a4fa4184358a3bb8fd30afbb53b":{
      "scriptId":"u19"},
    "a452d666038444e2b61e95b2eb8c03b8":{
      "scriptId":"u20"},
    "a23db41b7c2346529a072ae5240d5e05":{
      "scriptId":"u21"},
    "3a7f481d24b34c0c8fc0d5fca2156b48":{
      "scriptId":"u22"},
    "cc2111f7abbf4343927aaf078ed1c93f":{
      "scriptId":"u23"},
    "6bf21a09a5aa4532a7f3daa2015c98cf":{
      "scriptId":"u24"},
    "ae369cee111d496fbd7aed054b9a87cd":{
      "scriptId":"u25"},
    "449956e1db4945b29ca1dc23ad235a9b":{
      "scriptId":"u26"},
    "82fd0fc133a740cba6b0fc7585b5c592":{
      "scriptId":"u27"},
    "257bfa144c394a1d9bbd23ac8094f3e1":{
      "scriptId":"u28"},
    "d8e6cb2588f34bb5be646e9d666f2f9c":{
      "scriptId":"u29"},
    "a337c128a34e40a88ca70e08cca38ea4":{
      "scriptId":"u30"},
    "abf8e4e01916419c8a6ff3d926551a06":{
      "scriptId":"u31"},
    "9119f25c725c4d1eb51d9ec520f73057":{
      "scriptId":"u32"},
    "b2d1d4b9f6144bebb30ff86b78489147":{
      "scriptId":"u33"},
    "cb0708c0f2d7453a9d46befb4504ef7f":{
      "scriptId":"u34"},
    "43605d1d077c4de8be87bfc70aa16633":{
      "scriptId":"u35"},
    "61a8f7c453724e87b38859d0638319dc":{
      "scriptId":"u36"},
    "8c08d25beccf405496aad06e824bf09e":{
      "scriptId":"u37"},
    "b6f2783b74294187b78ea480ee596853":{
      "scriptId":"u38"},
    "6ee21398caca40bcb9c49f6849e6122a":{
      "scriptId":"u39"},
    "023184d157594efc97e451c85a969e93":{
      "scriptId":"u40"},
    "2750d851485a466babc6b028acc7ded0":{
      "scriptId":"u41"},
    "3014b28b8a7347cbad32e15142fe9adc":{
      "scriptId":"u42"},
    "4add3aa4b86a4e8fb595f6f1b23b5506":{
      "scriptId":"u43"},
    "e362498461d14a9fbc1619858f676d70":{
      "scriptId":"u44"},
    "dd580743eb1c4212b37963cf76f17437":{
      "scriptId":"u45"},
    "756f189af9384e99bc0edee7ac448c64":{
      "scriptId":"u46"},
    "466d70f030f34719a18d56d0d397a67c":{
      "scriptId":"u47"},
    "1304691261434e05baf3e53acb2bb371":{
      "scriptId":"u48"},
    "74a4f636da3549b586c0d51cd506cec1":{
      "scriptId":"u49"},
    "15738f1c8e954ea0b67f7011d3c57ab1":{
      "scriptId":"u50"},
    "53981f2639f8475997d637f7f2d6794c":{
      "scriptId":"u51"},
    "5510e4d6c97a43de9b016c4d5af4cb64":{
      "scriptId":"u52"},
    "8a8ffaa5768849edbc83dd6688cffef7":{
      "scriptId":"u53"},
    "8e088f9bb02441e38086211ec3140b69":{
      "scriptId":"u54"},
    "0570b9a736d14c82bf2077c6ae3f368b":{
      "scriptId":"u55"},
    "03d09694502448e488ea312f0065e222":{
      "scriptId":"u56"},
    "966a2bedf5ee4af3b259e8d76adcfee6":{
      "scriptId":"u57"},
    "e9582321325f4a0da6bd93897559c3b6":{
      "scriptId":"u58"},
    "56f75fe29ec34fc18293d4aae7fd4708":{
      "scriptId":"u59"},
    "c5b333cfd2684305a29b26c64c6d6fa1":{
      "scriptId":"u60"},
    "d8b7117e3782471c8ca83f49c0e35eab":{
      "scriptId":"u61"},
    "67c20dcd34844e86876f4994124391dc":{
      "scriptId":"u62"},
    "3ae5f3ff18c943d1a116f524a9f02b10":{
      "scriptId":"u63"},
    "001f0d522331480fafa9ccd374b34d7d":{
      "scriptId":"u64"},
    "1f3f3e718c2543e3afb8392eebf1405c":{
      "scriptId":"u65"},
    "5330f0738a104fa1b52ae55394a9f5f9":{
      "scriptId":"u66"},
    "a0f5827e01f4496eabed74b5bcf0c022":{
      "scriptId":"u67"},
    "ed141c8f38424956aa114f991d09e053":{
      "scriptId":"u68"},
    "fd171b9e17a742f1a5324c732aa49c84":{
      "scriptId":"u69"},
    "90523a7460ed4839beb276b97b80a3f1":{
      "scriptId":"u70"},
    "10f308ee4d904e3f88f8cf0afe2f6359":{
      "scriptId":"u71"},
    "cd352154540e44d590b1891d4c058ca4":{
      "scriptId":"u72"},
    "c2c1db38493747e78cdf32741c5a3745":{
      "scriptId":"u73"},
    "2df243d149bd4ec98279c072b90eaf3f":{
      "scriptId":"u74"},
    "f18959c209cb43b68235451e2e98e0b3":{
      "scriptId":"u75"},
    "74df74cbfa0f490a9ee6a6ad4a476f63":{
      "scriptId":"u76"},
    "c2a7eba179b84bd4b4ac57bb3d0ee7e5":{
      "scriptId":"u77"},
    "8a5dd02c2a3c43b4af504042623c9f48":{
      "scriptId":"u78"},
    "2a374f2ccac446f294cb962b051334e6":{
      "scriptId":"u79"},
    "ad509970de9e4f60b0e18407237c7d6e":{
      "scriptId":"u80"},
    "2e183a31751d49ab9eeefe082da0cceb":{
      "scriptId":"u81"},
    "3a46b3d2b0bb41779a5f6b0aa76c2d79":{
      "scriptId":"u82"},
    "4af598c19d1f42da828d997b98a81b0b":{
      "scriptId":"u83"},
    "60fcf84404de4198b28e54a9907deb3b":{
      "scriptId":"u84"},
    "cf72decab5fd435e951e82c3d5797a1e":{
      "scriptId":"u85"},
    "404c6cfb8da64c0ba5f886256558d848":{
      "scriptId":"u86"},
    "974100f57cef423d859153799e38f895":{
      "scriptId":"u87"},
    "271e4e8c271d422ba9e55dcc45902a36":{
      "scriptId":"u88"},
    "c6c04a4e03ff469aadf4f1f17d6f4834":{
      "scriptId":"u89"},
    "803c7ae3aa2b46e4abebbf3c8220e2dd":{
      "scriptId":"u90"}}});