$axure.loadCurrentPage({
  "url":"用例图.html",
  "generationDate":new Date(1494572349664.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5a966014458b46ea8c2a428264a0594e",
    "type":"Axure:Page",
    "name":"用例图",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"18881705f7554b9d8797300527ae4b8e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":160},
            "size":{
              "width":50,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feb2596f4db648e5b3272f6ed2321c75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":160},
                "size":{
                  "width":50,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用例图/u0.png"}},
{
          "id":"8889d8f61d5a472a9aab33c2484b7a61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":160,
              "y":160},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0e88f37bff945368b2c29013e5e6d90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":160,
                  "y":160},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e38005396e1d4f918859ea6ddf39dc40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":230,
              "y":264},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36e2e80c834846be88315a8d56ed0770",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":264},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b16dcc931aad485484a9a095ba1b42d5",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":454,
              "y":177.5},
            "size":{
              "width":156,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44c471c51fe7427ab66ca2bd541e8f52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":454,
                  "y":177.5},
                "size":{
                  "width":156,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用例图/u6.png"}},
{
          "id":"68fe44e93b2a439ab3e0b1cd04bc91ef",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"528530da33ff48f6a08708737a4517aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":200}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "18881705f7554b9d8797300527ae4b8e":{
      "scriptId":"u0"},
    "feb2596f4db648e5b3272f6ed2321c75":{
      "scriptId":"u1"},
    "8889d8f61d5a472a9aab33c2484b7a61":{
      "scriptId":"u2"},
    "b0e88f37bff945368b2c29013e5e6d90":{
      "scriptId":"u3"},
    "e38005396e1d4f918859ea6ddf39dc40":{
      "scriptId":"u4"},
    "36e2e80c834846be88315a8d56ed0770":{
      "scriptId":"u5"},
    "b16dcc931aad485484a9a095ba1b42d5":{
      "scriptId":"u6"},
    "44c471c51fe7427ab66ca2bd541e8f52":{
      "scriptId":"u7"},
    "68fe44e93b2a439ab3e0b1cd04bc91ef":{
      "scriptId":"u8"},
    "528530da33ff48f6a08708737a4517aa":{
      "scriptId":"u9"}}});