$axure.loadCurrentPage({
  "url":"知识点分解.html",
  "generationDate":new Date(1494572325201.86),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b4ec70d931c74aaa9e41ad226a47abb0",
    "type":"Axure:Page",
    "name":"知识点分解",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ce1991041bc64482ae5f4d17fb6c175a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":668},
            "size":{
              "width":979,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e45c580b012a4f8097684074ff35a5e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":668},
                "size":{
                  "width":979,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/备课/u131.png"}},
{
          "id":"b2305329108741e7820663ad96acdf5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF336666,
              "opacity":1},
            "location":{
              "x":51,
              "y":681},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8d322f7014b4b6ea63a8e2ee5fb4461",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF336666,
                  "opacity":1},
                "location":{
                  "x":51,
                  "y":681},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38b2160df7464f888ed495b72e8e33c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1020,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f7a06f452f143729119cf349131c150",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1020,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/讲课页面/u4.png"}},
{
          "id":"ef81766527b74d0da2c4d9a6aa8f168c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":20},
            "size":{
              "width":119,
              "height":82},
            "rotation":"270",
            "textRotation":"270",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF66FFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e25f453da23c427b9709c3e49d29ec25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":20},
                "size":{
                  "width":119,
                  "height":82},
                "rotation":"270",
                "textRotation":"270",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF66FFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/讲课页面/u6.png"}},
{
          "id":"07e71e7fd7964d1fbf6d347536341539",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":19},
            "size":{
              "width":53,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09565b0fb2234eed969535c69fd35bda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":19},
                "size":{
                  "width":53,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f69dfe7c7f9b4d34b4d63a84c053d73c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":69},
            "size":{
              "width":34,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d02a4d902a224c28b0433898eac5a718",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":69},
                "size":{
                  "width":34,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b77a115d752417e8ab846c0a1e7ab66",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCAED92},
            "location":{
              "x":944,
              "y":10},
            "size":{
              "width":60,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d92596370d884691ac3bff71af53ed82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCAED92},
                "location":{
                  "x":944,
                  "y":10},
                "size":{
                  "width":60,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 授课",
                      "target":{
                        "targetType":"page",
                        "url":"授课.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课页面/u12.png"}},
{
          "id":"f16a9ddccff74273bec7f1deb0fe5679",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFF009933},
            "location":{
              "x":646,
              "y":10},
            "size":{
              "width":60,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47b8f695118642f5a06c33eae2f7e527",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009933},
                "location":{
                  "x":646,
                  "y":10},
                "size":{
                  "width":60,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讲课页面",
                      "target":{
                        "targetType":"page",
                        "url":"讲课页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课页面/u14.png"}},
{
          "id":"0d531a9c8f0846ffbdd200cdf6a297b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCAED92},
            "location":{
              "x":730,
              "y":10},
            "size":{
              "width":60,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d13b3cb7c6f47a6a51b2419d274667b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCAED92},
                "location":{
                  "x":730,
                  "y":10},
                "size":{
                  "width":60,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 jifen 向下滑动 500 ms 灯箱效果",
                      "objectsToFades":[{
                          "objectPath":["97405db56f4e45cb868fb7b35bb67c7e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"lightbox",
                              "lightbox":{
                                "r":67,
                                "g":67,
                                "b":67,
                                "a":155}}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课页面/u12.png"}},
{
          "id":"4a59e22b715f47439f485f7cce50f8a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":749,
              "y":32},
            "size":{
              "width":23,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20a7f3c71f614e56bbd2f9d187d8b954",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":749,
                  "y":32},
                "size":{
                  "width":23,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1e0172a185c49548f715632397d3a00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCAED92},
            "location":{
              "x":806,
              "y":10},
            "size":{
              "width":60,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a303c4a1bab468fb113ca12659e578b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCAED92},
                "location":{
                  "x":806,
                  "y":10},
                "size":{
                  "width":60,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 提问",
                      "target":{
                        "targetType":"page",
                        "url":"提问.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课页面/u12.png"}},
{
          "id":"0dcbd88b752f403baa85f431e7e5c8af",
          "label":"liebiao",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":876,
              "y":10},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 liebiaoDIV 向下滑动 500 ms",
                      "objectsToFades":[{
                          "objectPath":["f97e9e8c62264918a165fff187e60e75"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"646fe1f48d0d41e2b497e3270470a200",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"028f8544d6fe4dd29c230eb64d18b6cc",
                  "label":"",
                  "parentDynamicPanel":"0dcbd88b752f403baa85f431e7e5c8af",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCAED92},
                    "size":{
                      "width":60,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "cornerRadiusTopLeft":"30"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"271b2d2733fc46fcb05f707171773308",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0dcbd88b752f403baa85f431e7e5c8af",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCAED92},
                        "size":{
                          "width":60,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "cornerRadiusTopLeft":"30"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u12.png"}},
{
                  "id":"a8487d264e0541bd943ebb21562dc66b",
                  "label":"",
                  "parentDynamicPanel":"0dcbd88b752f403baa85f431e7e5c8af",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":15,
                      "y":4},
                    "size":{
                      "width":30,
                      "height":10},
                    "borderWidth":"4"},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/讲课页面/u25_line.png"}},
{
                  "id":"c3bac923c5204fcfab737173c4a3d86c",
                  "label":"",
                  "parentDynamicPanel":"0dcbd88b752f403baa85f431e7e5c8af",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":15,
                      "y":15},
                    "size":{
                      "width":30,
                      "height":10},
                    "borderWidth":"4"},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/讲课页面/u25_line.png"}},
{
                  "id":"d2cc9833aaa744ed929b2c8890375c94",
                  "label":"",
                  "parentDynamicPanel":"0dcbd88b752f403baa85f431e7e5c8af",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":15,
                      "y":26},
                    "size":{
                      "width":30,
                      "height":10},
                    "borderWidth":"4"},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/讲课页面/u25_line.png"}}]}]},
{
          "id":"3c4f03c09ff247cf990fcc719e4a6fcb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":346,
              "y":100},
            "size":{
              "width":580,
              "height":440},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCC33},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46797292a3154ea9afe35693874537a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":346,
                  "y":100},
                "size":{
                  "width":580,
                  "height":440},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCC33},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/知识点分解/u28.png"}},
{
          "id":"97405db56f4e45cb868fb7b35bb67c7e",
          "label":"jifen",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":99,
              "y":85},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"1173cf000f954c9e8d19721c6bbea6de",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ec8d80cabeb64f4cb0b9a7abe5de5fc2",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":860,
                      "height":525}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0631939e06a04b65992578c71df45246",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":860,
                          "height":525}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u31.png"}},
{
                  "id":"6e78cf8472c2427e8f70718d0c2c733e",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":828,
                      "y":4},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5c474e292d1f41ed9152ea77a52c858b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":828,
                          "y":4},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 jifen",
                              "objectsToFades":[{
                                  "objectPath":["97405db56f4e45cb868fb7b35bb67c7e"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"87b22a913e684e00aaf164aea1a9e79a",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":30,
                      "y":24},
                    "size":{
                      "width":33,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b7da65a03134fffb82a22630e54f502",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":30,
                          "y":24},
                        "size":{
                          "width":33,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8db96cf2e0f64e2ea7cebff23e1d3ec5",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":43},
                    "size":{
                      "width":20,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0a09307c64b643c48f1ce3188b2d7499",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":19,
                          "y":43},
                        "size":{
                          "width":20,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u38.png"}},
{
                  "id":"e20c9e932a194b47a0682497cc648fef",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":49,
                      "y":43},
                    "size":{
                      "width":20,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b5c1a77505084dae96d3fbf0a415b9b0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":49,
                          "y":43},
                        "size":{
                          "width":20,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u38.png"}},
{
                  "id":"f10eced5c41d4aa3be4adbd4c2e1cd95",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":86,
                      "y":30},
                    "size":{
                      "width":12,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b42c752b3c864088b921da8b37440129",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":86,
                          "y":30},
                        "size":{
                          "width":12,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"027d2f976fcc45f0b9ac6cff692d365c",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":171,
                      "y":24},
                    "size":{
                      "width":33,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ecfba32c23f14db5a515069182286907",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":171,
                          "y":24},
                        "size":{
                          "width":33,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1d2d79c4926e4e33a087b5c767fed140",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":43},
                    "size":{
                      "width":20,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8c720b30a77e457691f480da9366ebd5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":160,
                          "y":43},
                        "size":{
                          "width":20,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u38.png"}},
{
                  "id":"6494335a5a044a579f76571cc10d58f7",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":190,
                      "y":43},
                    "size":{
                      "width":20,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"758f073360a24246bb9282ffd4be1c82",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":190,
                          "y":43},
                        "size":{
                          "width":20,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u38.png"}},
{
                  "id":"e56a348cf80e403da1464ac0f290021b",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":227,
                      "y":30},
                    "size":{
                      "width":12,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"782b10b8dbff4e4ca82c76fbe3c5f310",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":227,
                          "y":30},
                        "size":{
                          "width":12,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"efd2a1b1a8684634b45edc6511644973",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":292,
                      "y":24},
                    "size":{
                      "width":33,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f55a0075d15443dbb8950f786aa5ecf4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":292,
                          "y":24},
                        "size":{
                          "width":33,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6bb0866223ad49609e8c10070d67ec63",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":281,
                      "y":43},
                    "size":{
                      "width":20,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e924aa0f0613404c82331786901e613a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":281,
                          "y":43},
                        "size":{
                          "width":20,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u38.png"}},
{
                  "id":"1c64e74d6d894f118aa24acfc3549b1d",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":311,
                      "y":43},
                    "size":{
                      "width":20,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a915485eb09c499f8c48f99adec944c4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":311,
                          "y":43},
                        "size":{
                          "width":20,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u38.png"}},
{
                  "id":"514c1a20542d43e5afa10759476d7701",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":348,
                      "y":30},
                    "size":{
                      "width":12,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cbd53e9a2c93424ba47e8ede0de89150",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":348,
                          "y":30},
                        "size":{
                          "width":12,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"54cbe5b5d0f840daa76a5cfdc0ec4335",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":411,
                      "y":24},
                    "size":{
                      "width":33,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3d2a63fd9fcd4dd2b3aa830d54c87df5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":411,
                          "y":24},
                        "size":{
                          "width":33,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9f3828e8797648aca03a49b5a64565a2",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":400,
                      "y":43},
                    "size":{
                      "width":20,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"60f9088a4ddb4be69e2a8635a6f913e1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":400,
                          "y":43},
                        "size":{
                          "width":20,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u38.png"}},
{
                  "id":"73952765dcbf4ab8a228fdbc6398a860",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":430,
                      "y":43},
                    "size":{
                      "width":20,
                      "height":18}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8586d430940942a9a2dd1cc53eb9a31f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":430,
                          "y":43},
                        "size":{
                          "width":20,
                          "height":18}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u38.png"}},
{
                  "id":"cce6e58b8ed14ab5abf9713f7009923d",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":467,
                      "y":30},
                    "size":{
                      "width":12,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6120bec0d4ad4daf9c44e2ca9e464fc1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":467,
                          "y":30},
                        "size":{
                          "width":12,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c70f7cf3f34f486983a0fe5e0963b741",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF6699FF},
                    "location":{
                      "x":288,
                      "y":390},
                    "size":{
                      "width":77,
                      "height":30},
                    "cornerRadiusTopLeft":"8"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"781b5731413141a5b16953ceb427fb22",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF6699FF},
                        "location":{
                          "x":288,
                          "y":390},
                        "size":{
                          "width":77,
                          "height":30},
                        "cornerRadiusTopLeft":"8"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 divjiafen",
                              "objectsToFades":[{
                                  "objectPath":["e86fb4fff3574eccad8737cc74a989bf"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/讲课页面/u84.png"}},
{
                  "id":"620be22f1331458bb31d35d6879f3a92",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC},
                    "location":{
                      "x":456,
                      "y":390},
                    "size":{
                      "width":77,
                      "height":30},
                    "cornerRadiusTopLeft":"8"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e4ba9c26871e49439de6755b18e3ef48",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFBCBCBC},
                        "location":{
                          "x":456,
                          "y":390},
                        "size":{
                          "width":77,
                          "height":30},
                        "cornerRadiusTopLeft":"8"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 jifen",
                              "objectsToFades":[{
                                  "objectPath":["97405db56f4e45cb868fb7b35bb67c7e"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/讲课页面/u86.png"}},
{
                  "id":"f15a33f89b574ca0a16f3d92bbf594e0",
                  "label":"",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF3300FF,
                      "opacity":1},
                    "location":{
                      "x":39,
                      "y":148},
                    "size":{
                      "width":388,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"94c3cff2a0ea4545b81db656ff26f7c9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF3300FF,
                          "opacity":1},
                        "location":{
                          "x":39,
                          "y":148},
                        "size":{
                          "width":388,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e86fb4fff3574eccad8737cc74a989bf",
                  "label":"divjiafen",
                  "parentDynamicPanel":"97405db56f4e45cb868fb7b35bb67c7e",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":281,
                      "y":140},
                    "size":{
                      "width":10,
                      "height":10},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"0b2d6bb1afd049378b5342a0d99c80e3",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"8cf00c40c0ba428894444fc1570419ea",
                          "label":"",
                          "parentDynamicPanel":"e86fb4fff3574eccad8737cc74a989bf",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":319,
                              "height":160}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"007e3fdc69904baa9bc825ec6d7ad22d",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"e86fb4fff3574eccad8737cc74a989bf",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":319,
                                  "height":160}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/讲课页面/u91.png"}},
{
                          "id":"ca9144156cbc4c978f7ec775524acd40",
                          "label":"",
                          "parentDynamicPanel":"e86fb4fff3574eccad8737cc74a989bf",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "location":{
                              "x":42,
                              "y":40},
                            "size":{
                              "width":234,
                              "height":19}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"d36ef64a50934d27b66a3119818934bc",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"e86fb4fff3574eccad8737cc74a989bf",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"16px",
                                "location":{
                                  "x":42,
                                  "y":40},
                                "size":{
                                  "width":234,
                                  "height":19}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"220e95bd3e0d427d842b725b6b23550e",
                          "label":"",
                          "parentDynamicPanel":"e86fb4fff3574eccad8737cc74a989bf",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF6699FF},
                            "location":{
                              "x":112,
                              "y":115},
                            "size":{
                              "width":77,
                              "height":30},
                            "cornerRadiusTopLeft":"8"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9080555bc56e4880aa5d0196751c7d4b",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"e86fb4fff3574eccad8737cc74a989bf",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFF6699FF},
                                "location":{
                                  "x":112,
                                  "y":115},
                                "size":{
                                  "width":77,
                                  "height":30},
                                "cornerRadiusTopLeft":"8"},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"fadeWidget",
                                      "description":"隐藏 jifen",
                                      "objectsToFades":[{
                                          "objectPath":["97405db56f4e45cb868fb7b35bb67c7e"],
                                          "fadeInfo":{
                                            "fadeType":"hide",
                                            "options":{
                                              "showType":"none"}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/讲课页面/u84.png"}}]}]}]}]},
{
          "id":"b022a03df84243d299775f838374e269",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":100},
            "size":{
              "width":190,
              "height":440},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCC33},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39bf613626ee41519269dc6d05830500",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":100},
                "size":{
                  "width":190,
                  "height":440},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCC33},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/知识点分解/u80.png"}},
{
          "id":"ea837d66b30847a18bf17601960f257f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":130},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60b79ed9afaf423bb1b52e92f679bc39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":130},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27b79d99d55d49d1b31007366c75f61c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":156},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f142963e54974448979673f41d37c21b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":156},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38ee05c59e0c4368b8b9094077236cb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":182},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8631b8c923964af4b3e8fc3a575c28ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":182},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f97e9e8c62264918a165fff187e60e75",
          "label":"liebiaoDIV",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":1,
              "y":62},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"02b216fb4a824a7ba3421838e33c6354",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"87f8af87010d45e9801ddb9338108d30",
                  "label":"",
                  "parentDynamicPanel":"f97e9e8c62264918a165fff187e60e75",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1019,
                      "height":643}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4da7859a9809488e86135714bb175f3e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f97e9e8c62264918a165fff187e60e75",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1019,
                          "height":643}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课页面/u104.png"}},
{
                  "id":"8599d5e0b6ce4e59a9741272ef3d56fe",
                  "label":"",
                  "parentDynamicPanel":"f97e9e8c62264918a165fff187e60e75",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":290,
                      "y":60},
                    "size":{
                      "width":460,
                      "height":440},
                    "cornerRadiusTopLeft":"7"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"00a0070ad8bb476cb0df1959395acdcf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f97e9e8c62264918a165fff187e60e75",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":290,
                          "y":60},
                        "size":{
                          "width":460,
                          "height":440},
                        "cornerRadiusTopLeft":"7"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/上讲作业页面/u87.png"}},
{
                  "id":"06e1be940bf64455892964a228740bf0",
                  "label":"",
                  "parentDynamicPanel":"f97e9e8c62264918a165fff187e60e75",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":716,
                      "y":45},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7497faa5c45d47f381175ea0a2a80647",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f97e9e8c62264918a165fff187e60e75",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":716,
                          "y":45},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 liebiaoDIV 向上滑动 500 ms",
                              "objectsToFades":[{
                                  "objectPath":["f97e9e8c62264918a165fff187e60e75"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideUp",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/讲课页面/u108.png"}},
{
                  "id":"6bd1ba8605944e249ccbd32ab1f3f1c0",
                  "label":"",
                  "parentDynamicPanel":"f97e9e8c62264918a165fff187e60e75",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":324,
                      "y":90},
                    "size":{
                      "width":70,
                      "height":50},
                    "cornerRadiusTopLeft":"31"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"70d1dccb77f54a3f95dd52a4475539a2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f97e9e8c62264918a165fff187e60e75",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":324,
                          "y":90},
                        "size":{
                          "width":70,
                          "height":50},
                        "cornerRadiusTopLeft":"31"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 上讲作业页面",
                              "target":{
                                "targetType":"page",
                                "url":"上讲作业页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/讲课页面/u110.png"}},
{
                  "id":"ea0be9633a0e44819f021d22d84a1b91",
                  "label":"",
                  "parentDynamicPanel":"f97e9e8c62264918a165fff187e60e75",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":480,
                      "y":90},
                    "size":{
                      "width":70,
                      "height":50},
                    "cornerRadiusTopLeft":"26"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"388895fb19bb45cdaf531d25a3741929",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f97e9e8c62264918a165fff187e60e75",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":480,
                          "y":90},
                        "size":{
                          "width":70,
                          "height":50},
                        "cornerRadiusTopLeft":"26"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 积分排名",
                              "target":{
                                "targetType":"page",
                                "url":"积分排名.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/讲课页面/u110.png"}},
{
                  "id":"915f32d002a04af897073148155aca3d",
                  "label":"",
                  "parentDynamicPanel":"f97e9e8c62264918a165fff187e60e75",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":477,
                      "y":310},
                    "size":{
                      "width":70,
                      "height":50},
                    "cornerRadiusTopLeft":"24"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"af59d88a31cc4b38b194ecb875b2ac01",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f97e9e8c62264918a165fff187e60e75",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":477,
                          "y":310},
                        "size":{
                          "width":70,
                          "height":50},
                        "cornerRadiusTopLeft":"24"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 知识点分解",
                              "target":{
                                "targetType":"page",
                                "url":"知识点分解.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/讲课页面/u112.png"}},
{
                  "id":"d89a33e4009c431fb2ed0a223dbbeffe",
                  "label":"",
                  "parentDynamicPanel":"f97e9e8c62264918a165fff187e60e75",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":624,
                      "y":90},
                    "size":{
                      "width":70,
                      "height":50},
                    "cornerRadiusTopLeft":"28"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e156082d48a84c3c83becb19de83eed7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f97e9e8c62264918a165fff187e60e75",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":624,
                          "y":90},
                        "size":{
                          "width":70,
                          "height":50},
                        "cornerRadiusTopLeft":"28"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 更换讲次",
                              "target":{
                                "targetType":"page",
                                "url":"更换讲次.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/讲课页面/u110.png"}},
{
                  "id":"7a89bbf11328400597fc8524d473bcef",
                  "label":"",
                  "parentDynamicPanel":"f97e9e8c62264918a165fff187e60e75",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":324,
                      "y":260},
                    "size":{
                      "width":376,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/上讲作业页面/u99_line.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "ce1991041bc64482ae5f4d17fb6c175a":{
      "scriptId":"u0"},
    "e45c580b012a4f8097684074ff35a5e4":{
      "scriptId":"u1"},
    "b2305329108741e7820663ad96acdf5b":{
      "scriptId":"u2"},
    "e8d322f7014b4b6ea63a8e2ee5fb4461":{
      "scriptId":"u3"},
    "38b2160df7464f888ed495b72e8e33c6":{
      "scriptId":"u4"},
    "4f7a06f452f143729119cf349131c150":{
      "scriptId":"u5"},
    "ef81766527b74d0da2c4d9a6aa8f168c":{
      "scriptId":"u6"},
    "e25f453da23c427b9709c3e49d29ec25":{
      "scriptId":"u7"},
    "07e71e7fd7964d1fbf6d347536341539":{
      "scriptId":"u8"},
    "09565b0fb2234eed969535c69fd35bda":{
      "scriptId":"u9"},
    "f69dfe7c7f9b4d34b4d63a84c053d73c":{
      "scriptId":"u10"},
    "d02a4d902a224c28b0433898eac5a718":{
      "scriptId":"u11"},
    "6b77a115d752417e8ab846c0a1e7ab66":{
      "scriptId":"u12"},
    "d92596370d884691ac3bff71af53ed82":{
      "scriptId":"u13"},
    "f16a9ddccff74273bec7f1deb0fe5679":{
      "scriptId":"u14"},
    "47b8f695118642f5a06c33eae2f7e527":{
      "scriptId":"u15"},
    "0d531a9c8f0846ffbdd200cdf6a297b3":{
      "scriptId":"u16"},
    "7d13b3cb7c6f47a6a51b2419d274667b":{
      "scriptId":"u17"},
    "4a59e22b715f47439f485f7cce50f8a2":{
      "scriptId":"u18"},
    "20a7f3c71f614e56bbd2f9d187d8b954":{
      "scriptId":"u19"},
    "d1e0172a185c49548f715632397d3a00":{
      "scriptId":"u20"},
    "8a303c4a1bab468fb113ca12659e578b":{
      "scriptId":"u21"},
    "0dcbd88b752f403baa85f431e7e5c8af":{
      "scriptId":"u22"},
    "028f8544d6fe4dd29c230eb64d18b6cc":{
      "scriptId":"u23"},
    "271b2d2733fc46fcb05f707171773308":{
      "scriptId":"u24"},
    "a8487d264e0541bd943ebb21562dc66b":{
      "scriptId":"u25"},
    "c3bac923c5204fcfab737173c4a3d86c":{
      "scriptId":"u26"},
    "d2cc9833aaa744ed929b2c8890375c94":{
      "scriptId":"u27"},
    "3c4f03c09ff247cf990fcc719e4a6fcb":{
      "scriptId":"u28"},
    "46797292a3154ea9afe35693874537a2":{
      "scriptId":"u29"},
    "97405db56f4e45cb868fb7b35bb67c7e":{
      "scriptId":"u30"},
    "ec8d80cabeb64f4cb0b9a7abe5de5fc2":{
      "scriptId":"u31"},
    "0631939e06a04b65992578c71df45246":{
      "scriptId":"u32"},
    "6e78cf8472c2427e8f70718d0c2c733e":{
      "scriptId":"u33"},
    "5c474e292d1f41ed9152ea77a52c858b":{
      "scriptId":"u34"},
    "87b22a913e684e00aaf164aea1a9e79a":{
      "scriptId":"u35"},
    "4b7da65a03134fffb82a22630e54f502":{
      "scriptId":"u36"},
    "8db96cf2e0f64e2ea7cebff23e1d3ec5":{
      "scriptId":"u37"},
    "0a09307c64b643c48f1ce3188b2d7499":{
      "scriptId":"u38"},
    "e20c9e932a194b47a0682497cc648fef":{
      "scriptId":"u39"},
    "b5c1a77505084dae96d3fbf0a415b9b0":{
      "scriptId":"u40"},
    "f10eced5c41d4aa3be4adbd4c2e1cd95":{
      "scriptId":"u41"},
    "b42c752b3c864088b921da8b37440129":{
      "scriptId":"u42"},
    "027d2f976fcc45f0b9ac6cff692d365c":{
      "scriptId":"u43"},
    "ecfba32c23f14db5a515069182286907":{
      "scriptId":"u44"},
    "1d2d79c4926e4e33a087b5c767fed140":{
      "scriptId":"u45"},
    "8c720b30a77e457691f480da9366ebd5":{
      "scriptId":"u46"},
    "6494335a5a044a579f76571cc10d58f7":{
      "scriptId":"u47"},
    "758f073360a24246bb9282ffd4be1c82":{
      "scriptId":"u48"},
    "e56a348cf80e403da1464ac0f290021b":{
      "scriptId":"u49"},
    "782b10b8dbff4e4ca82c76fbe3c5f310":{
      "scriptId":"u50"},
    "efd2a1b1a8684634b45edc6511644973":{
      "scriptId":"u51"},
    "f55a0075d15443dbb8950f786aa5ecf4":{
      "scriptId":"u52"},
    "6bb0866223ad49609e8c10070d67ec63":{
      "scriptId":"u53"},
    "e924aa0f0613404c82331786901e613a":{
      "scriptId":"u54"},
    "1c64e74d6d894f118aa24acfc3549b1d":{
      "scriptId":"u55"},
    "a915485eb09c499f8c48f99adec944c4":{
      "scriptId":"u56"},
    "514c1a20542d43e5afa10759476d7701":{
      "scriptId":"u57"},
    "cbd53e9a2c93424ba47e8ede0de89150":{
      "scriptId":"u58"},
    "54cbe5b5d0f840daa76a5cfdc0ec4335":{
      "scriptId":"u59"},
    "3d2a63fd9fcd4dd2b3aa830d54c87df5":{
      "scriptId":"u60"},
    "9f3828e8797648aca03a49b5a64565a2":{
      "scriptId":"u61"},
    "60f9088a4ddb4be69e2a8635a6f913e1":{
      "scriptId":"u62"},
    "73952765dcbf4ab8a228fdbc6398a860":{
      "scriptId":"u63"},
    "8586d430940942a9a2dd1cc53eb9a31f":{
      "scriptId":"u64"},
    "cce6e58b8ed14ab5abf9713f7009923d":{
      "scriptId":"u65"},
    "6120bec0d4ad4daf9c44e2ca9e464fc1":{
      "scriptId":"u66"},
    "c70f7cf3f34f486983a0fe5e0963b741":{
      "scriptId":"u67"},
    "781b5731413141a5b16953ceb427fb22":{
      "scriptId":"u68"},
    "620be22f1331458bb31d35d6879f3a92":{
      "scriptId":"u69"},
    "e4ba9c26871e49439de6755b18e3ef48":{
      "scriptId":"u70"},
    "f15a33f89b574ca0a16f3d92bbf594e0":{
      "scriptId":"u71"},
    "94c3cff2a0ea4545b81db656ff26f7c9":{
      "scriptId":"u72"},
    "e86fb4fff3574eccad8737cc74a989bf":{
      "scriptId":"u73"},
    "8cf00c40c0ba428894444fc1570419ea":{
      "scriptId":"u74"},
    "007e3fdc69904baa9bc825ec6d7ad22d":{
      "scriptId":"u75"},
    "ca9144156cbc4c978f7ec775524acd40":{
      "scriptId":"u76"},
    "d36ef64a50934d27b66a3119818934bc":{
      "scriptId":"u77"},
    "220e95bd3e0d427d842b725b6b23550e":{
      "scriptId":"u78"},
    "9080555bc56e4880aa5d0196751c7d4b":{
      "scriptId":"u79"},
    "b022a03df84243d299775f838374e269":{
      "scriptId":"u80"},
    "39bf613626ee41519269dc6d05830500":{
      "scriptId":"u81"},
    "ea837d66b30847a18bf17601960f257f":{
      "scriptId":"u82"},
    "60b79ed9afaf423bb1b52e92f679bc39":{
      "scriptId":"u83"},
    "27b79d99d55d49d1b31007366c75f61c":{
      "scriptId":"u84"},
    "f142963e54974448979673f41d37c21b":{
      "scriptId":"u85"},
    "38ee05c59e0c4368b8b9094077236cb3":{
      "scriptId":"u86"},
    "8631b8c923964af4b3e8fc3a575c28ff":{
      "scriptId":"u87"},
    "f97e9e8c62264918a165fff187e60e75":{
      "scriptId":"u88"},
    "87f8af87010d45e9801ddb9338108d30":{
      "scriptId":"u89"},
    "4da7859a9809488e86135714bb175f3e":{
      "scriptId":"u90"},
    "8599d5e0b6ce4e59a9741272ef3d56fe":{
      "scriptId":"u91"},
    "00a0070ad8bb476cb0df1959395acdcf":{
      "scriptId":"u92"},
    "06e1be940bf64455892964a228740bf0":{
      "scriptId":"u93"},
    "7497faa5c45d47f381175ea0a2a80647":{
      "scriptId":"u94"},
    "6bd1ba8605944e249ccbd32ab1f3f1c0":{
      "scriptId":"u95"},
    "70d1dccb77f54a3f95dd52a4475539a2":{
      "scriptId":"u96"},
    "ea0be9633a0e44819f021d22d84a1b91":{
      "scriptId":"u97"},
    "388895fb19bb45cdaf531d25a3741929":{
      "scriptId":"u98"},
    "915f32d002a04af897073148155aca3d":{
      "scriptId":"u99"},
    "af59d88a31cc4b38b194ecb875b2ac01":{
      "scriptId":"u100"},
    "d89a33e4009c431fb2ed0a223dbbeffe":{
      "scriptId":"u101"},
    "e156082d48a84c3c83becb19de83eed7":{
      "scriptId":"u102"},
    "7a89bbf11328400597fc8524d473bcef":{
      "scriptId":"u103"}}});