$axure.loadCurrentPage({
  "url":"考试测评.html",
  "generationDate":new Date(1494572345786.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"39adca97ffc34eff8829c59834414c02",
    "type":"Axure:Page",
    "name":"考试测评",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"36e1bdf8ce074dd3adde47f47c59e0c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":950,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc720ced01354a6eaf9181fb35b011d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":950,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/备课/u2.png"}},
{
          "id":"4b8ac9d64b8f4b09a71ac9bc9d91b34d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":9},
            "size":{
              "width":68,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf710858695541639bde01eaaf89eb6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":9},
                "size":{
                  "width":68,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83576a273d674be9861c2c9a06c66084",
          "label":"beike",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":119,
              "y":14},
            "size":{
              "width":80,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7d41853eadd4deb8b44ac449da95996",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":119,
                  "y":14},
                "size":{
                  "width":80,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 beike = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["83576a273d674be9861c2c9a06c66084"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 beike = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["83576a273d674be9861c2c9a06c66084"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/备课/beike_u6.png",
            "selected~":"images/备课/beike_u6_selected.png"}},
{
          "id":"0da3edc5e13e4b49ac77fd73b4e8c224",
          "label":"souke",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":208,
              "y":14},
            "size":{
              "width":65,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5602acbb8b847deaab98834ae735395",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":208,
                  "y":14},
                "size":{
                  "width":65,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 souke = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["0da3edc5e13e4b49ac77fd73b4e8c224"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 souke = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["0da3edc5e13e4b49ac77fd73b4e8c224"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/备课/souke_u8.png",
            "selected~":"images/备课/souke_u8_selected.png"}},
{
          "id":"4181c4fc658e4b558c7fb62fdb9f693a",
          "label":"guanli",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":282,
              "y":14},
            "size":{
              "width":70,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1c3a028e33d49d1b7025354db332233",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":282,
                  "y":14},
                "size":{
                  "width":70,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 guanli = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["4181c4fc658e4b558c7fb62fdb9f693a"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 guanli = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["4181c4fc658e4b558c7fb62fdb9f693a"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/校内管理/guanli_u13.png",
            "selected~":"images/校内管理/guanli_u13_selected.png"}},
{
          "id":"6cf60b1f02fa4f04b177fe934e1d4773",
          "label":"ceping",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":362,
              "y":14},
            "size":{
              "width":51,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0b5358de1f24fb08d314b6e3d796872",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":362,
                  "y":14},
                "size":{
                  "width":51,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 ceping = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6cf60b1f02fa4f04b177fe934e1d4773"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 ceping = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6cf60b1f02fa4f04b177fe934e1d4773"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/备课/ceping_u12.png",
            "selected~":"images/备课/ceping_u12_selected.png"}},
{
          "id":"4746c730ab744ae3a7a3f8f4f32b9e1d",
          "label":"peixun",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":423,
              "y":14},
            "size":{
              "width":58,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3671b9a0ef274708b87916bdb709889b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":423,
                  "y":14},
                "size":{
                  "width":58,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["4746c730ab744ae3a7a3f8f4f32b9e1d"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["4746c730ab744ae3a7a3f8f4f32b9e1d"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "images":{
            "normal~":"images/备课/peixun_u14.png",
            "selected~":"images/备课/peixun_u14_selected.png"}},
{
          "id":"095645b40a634e229c046c879675e5c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":14},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"defa8d13ae2e439cbd5b2ee2fcd894f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":850,
                  "y":14},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "images":{
            "normal~":"images/备课/u16.png"}},
{
          "id":"5a241cbfe1d94b4bb1580ba08763eb5d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":723},
            "size":{
              "width":964,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a139a281bcf4712ae8459d148d3f778",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":723},
                "size":{
                  "width":964,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/备课/u131.png"}},
{
          "id":"a965ebfd6b51497597c520c5c3b60e63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF336666,
              "opacity":1},
            "location":{
              "x":38,
              "y":736},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1741f5193003492ea037e948c3bede59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF336666,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":736},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4fa0d8c7e95f40489d11c786ef52f626",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":39},
            "size":{
              "width":79,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF33CCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/校内管理/u27_line.png"}},
{
          "id":"ffb456a2d47a42a5a9f34f6c964e687c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":678,
              "y":9},
            "size":{
              "width":79,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a072185d127f4a63b87fcb82f1da82ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":678,
                  "y":9},
                "size":{
                  "width":79,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"714c9184a3ed4dd6876c974df7336964",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":13,
              "y":106},
            "size":{
              "width":920,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"913eccf3c8d14129a66e8cee563ee1d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":13,
                  "y":106},
                "size":{
                  "width":920,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u23.png"}},
{
          "id":"9710a83535b2476da40d3e1c10fc0fff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":37,
              "y":123},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80381bc5dc474f8db7fa67caab505939",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":37,
                  "y":123},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测评",
                      "target":{
                        "targetType":"page",
                        "url":"测评.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"044a7c1d3baa4c58ac6439e443d97c25",
          "label":"ggxiaotu",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":55},
            "size":{
              "width":950,
              "height":50}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"62abf928c16147309da860f73eb22a18",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4488ac3ff2404485a43e4a6d3d727fda",
                  "label":"",
                  "parentDynamicPanel":"044a7c1d3baa4c58ac6439e443d97c25",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF66CCFF,
                      "opacity":1},
                    "size":{
                      "width":950,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9b916ba4272b48d0a71fbd7a3580b9aa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"044a7c1d3baa4c58ac6439e443d97c25",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF66CCFF,
                          "opacity":1},
                        "size":{
                          "width":950,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/测评/u28.png"}},
{
                  "id":"b7dd89fea9b54fbab0f5d1cb2b6b4626",
                  "label":"kongzhiqi",
                  "parentDynamicPanel":"044a7c1d3baa4c58ac6439e443d97c25",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":884,
                      "y":0},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"fb222c7d508846d38426d7e258b80b20",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"64d355e8d9a44db7b01e6fb41a95668a",
                          "label":"",
                          "parentDynamicPanel":"b7dd89fea9b54fbab0f5d1cb2b6b4626",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":66,
                              "height":30}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"d4dcd9115d8e4e59a7ee9f7e6a4e1c57",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b7dd89fea9b54fbab0f5d1cb2b6b4626",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":66,
                                  "height":30}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/校内管理/u32.png"}}]}]}]}]},
{
          "id":"7e3b6ade5cfb44b1a1aa8d05f404b439",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":13,
              "y":172},
            "size":{
              "width":920,
              "height":108},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59cd94674a6b41f893e10360bbb2cef3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":13,
                  "y":172},
                "size":{
                  "width":920,
                  "height":108},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u38.png"}},
{
          "id":"303901dd658541028d332d92cbb228e7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":210},
            "size":{
              "width":890,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/测评/u40_line.png"}},
{
          "id":"74e67be2805646c5942dbbad66578a03",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":25,
              "y":182},
            "size":{
              "width":93,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1a0c515187d4c2fb5d6383486f61d4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":25,
                  "y":182},
                "size":{
                  "width":93,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u41.png"}},
{
          "id":"9bb45f79b4394fa0a3729d8d8c889478",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":210},
            "size":{
              "width":93,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF33CCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/测评/u43_line.png"}},
{
          "id":"9c497b5d5984488488f355bff360ba51",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":118,
              "y":182},
            "size":{
              "width":93,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"169df8a1e77c4a6882eed80f9c202132",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":118,
                  "y":182},
                "size":{
                  "width":93,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 考试结果",
                      "target":{
                        "targetType":"page",
                        "url":"考试结果.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/测评/u41.png"}},
{
          "id":"11f5abf3acf5418eb234739563723fb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":13,
              "y":314},
            "size":{
              "width":920,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"706cfc3b302f4bd3a8fe1b2bcc39dd99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":13,
                  "y":314},
                "size":{
                  "width":920,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 试卷查看",
                      "target":{
                        "targetType":"page",
                        "url":"试卷查看.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/测评/u64.png",
            "mouseOver~":"images/测评/u23.png"}},
{
          "id":"13d42275f62a4056a10cedc564a829b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "location":{
              "x":19,
              "y":290},
            "size":{
              "width":61,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad3a48bb283f49aeb0f47641d3a05512",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":290},
                "size":{
                  "width":61,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5f43f7242564a29b074069a74c0a105",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":819,
              "y":322},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"31"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d33478ffebf74b23846bf38d3b58d5be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":819,
                  "y":322},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"31"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u68.png"}},
{
          "id":"498d30c2032c45aa884c19ab5e066fd8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":322},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"32"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c372ac5cd0b64b8495011ea2c3a747cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":322},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"32"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u70.png"}},
{
          "id":"d2a8d4aac6c74931a82abeb2531ebb9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":13,
              "y":369},
            "size":{
              "width":920,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05a02bac9cdc42b6910fe3924a0f6f3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":13,
                  "y":369},
                "size":{
                  "width":920,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 试卷查看",
                      "target":{
                        "targetType":"page",
                        "url":"试卷查看.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/测评/u64.png",
            "mouseOver~":"images/测评/u23.png"}},
{
          "id":"79edd5986b6b4d47bb8eaded93f968ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":819,
              "y":377},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"31"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"240a14c92b864d0c90b00f3d6877b7bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":819,
                  "y":377},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"31"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u68.png"}},
{
          "id":"5ca1e8f89b5a46b18d9326b3638a8bed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":377},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"32"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3733009205634c239b049e290c2d2df3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":377},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"32"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u70.png"}},
{
          "id":"e57b261d918b401f9ebada5da73dcefa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":13,
              "y":424},
            "size":{
              "width":920,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95551f54a9894974a8d1241e5ad26b0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":13,
                  "y":424},
                "size":{
                  "width":920,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 试卷查看",
                      "target":{
                        "targetType":"page",
                        "url":"试卷查看.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/测评/u64.png",
            "mouseOver~":"images/测评/u23.png"}},
{
          "id":"095ca87793ac42a9b0a9b7a03b755cf8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":819,
              "y":432},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"31"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f6245cebfd64782881b944784e752d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":819,
                  "y":432},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"31"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u68.png"}},
{
          "id":"afa6987d7e6d41689ebc66dc1f64b97d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":432},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"32"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dd9ad95ab8d482182bb25f4f183851c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":432},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"32"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u70.png"}},
{
          "id":"f67c9d961b9c43ca82d2e38334af0c0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}}},
            "location":{
              "x":13,
              "y":479},
            "size":{
              "width":920,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"733a5575f43040b5924fd67f6bdb7def",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}}},
                "location":{
                  "x":13,
                  "y":479},
                "size":{
                  "width":920,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 试卷查看",
                      "target":{
                        "targetType":"page",
                        "url":"试卷查看.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/测评/u64.png",
            "mouseOver~":"images/测评/u23.png"}},
{
          "id":"afb2330363364b27b06546ef9f7152d6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":819,
              "y":487},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"31"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90e04d314118495f95cef48630b420af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":819,
                  "y":487},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"31"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u68.png"}},
{
          "id":"732f71a2d02a47309521c979531ca0f4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":487},
            "size":{
              "width":40,
              "height":40},
            "cornerRadiusTopLeft":"32"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b32beefcdc7c4da9b3e337a0c55f1cf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":487},
                "size":{
                  "width":40,
                  "height":40},
                "cornerRadiusTopLeft":"32"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/测评/u70.png"}},
{
          "id":"b7d7680862bb4cbca836f2fbdc9fd6bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":398,
              "y":601},
            "size":{
              "width":103,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea381438b1ed4ab3ac0aa531f9981bee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":398,
                  "y":601},
                "size":{
                  "width":103,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba8f37f5173248eaa2a6cd9463a32978",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "location":{
              "x":138,
              "y":123},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f13e1e3531224b27945f9e92befc54cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "location":{
                  "x":138,
                  "y":123},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 考试测评",
                      "target":{
                        "targetType":"page",
                        "url":"考试测评.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bab7cae5cf5842c4bc2e43f5ceb37924",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":494,
              "y":235},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b04607f50ce64e09b6a7b58198552474",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":494,
                  "y":235},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4fb2454f1d964134ac5520411b2654e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":561,
              "y":230},
            "size":{
              "width":269,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e468ef98b4524622b8a57d094739240c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":561,
                  "y":230},
                "size":{
                  "width":269,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考试测评/u73.png"}},
{
          "id":"375b037c42974d269f2ae3449ce0f3eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":840,
              "y":230},
            "size":{
              "width":60,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecb5a9741c584a77a47d283e2b032a46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":840,
                  "y":230},
                "size":{
                  "width":60,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考试测评/u75.png"}},
{
          "id":"e39b678731804b9e8d2e3d0e75b8821e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "location":{
              "x":236,
              "y":123},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b3ab9a8a72e46e89add4e837a0e4404",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "location":{
                  "x":236,
                  "y":123},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 老师测评",
                      "target":{
                        "targetType":"page",
                        "url":"老师测评.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a6415168b5641e0aac038b78f8c1eed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3333FF,
              "opacity":1},
            "location":{
              "x":998,
              "y":182},
            "size":{
              "width":157,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da315865aa04448d97eb45457a83b521",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3333FF,
                  "opacity":1},
                "location":{
                  "x":998,
                  "y":182},
                "size":{
                  "width":157,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd37f9ddf1084f528e07421f77caa90a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":37,
              "y":234},
            "size":{
              "width":123,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ee244b76d2ea4aafb6578122e5d43bb3",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":179,
              "y":234},
            "size":{
              "width":123,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"e0fe654f50e54ced9e3ab72579383c14",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":326,
              "y":234},
            "size":{
              "width":123,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "36e1bdf8ce074dd3adde47f47c59e0c5":{
      "scriptId":"u0"},
    "cc720ced01354a6eaf9181fb35b011d2":{
      "scriptId":"u1"},
    "4b8ac9d64b8f4b09a71ac9bc9d91b34d":{
      "scriptId":"u2"},
    "cf710858695541639bde01eaaf89eb6a":{
      "scriptId":"u3"},
    "83576a273d674be9861c2c9a06c66084":{
      "scriptId":"u4"},
    "c7d41853eadd4deb8b44ac449da95996":{
      "scriptId":"u5"},
    "0da3edc5e13e4b49ac77fd73b4e8c224":{
      "scriptId":"u6"},
    "f5602acbb8b847deaab98834ae735395":{
      "scriptId":"u7"},
    "4181c4fc658e4b558c7fb62fdb9f693a":{
      "scriptId":"u8"},
    "c1c3a028e33d49d1b7025354db332233":{
      "scriptId":"u9"},
    "6cf60b1f02fa4f04b177fe934e1d4773":{
      "scriptId":"u10"},
    "d0b5358de1f24fb08d314b6e3d796872":{
      "scriptId":"u11"},
    "4746c730ab744ae3a7a3f8f4f32b9e1d":{
      "scriptId":"u12"},
    "3671b9a0ef274708b87916bdb709889b":{
      "scriptId":"u13"},
    "095645b40a634e229c046c879675e5c5":{
      "scriptId":"u14"},
    "defa8d13ae2e439cbd5b2ee2fcd894f6":{
      "scriptId":"u15"},
    "5a241cbfe1d94b4bb1580ba08763eb5d":{
      "scriptId":"u16"},
    "4a139a281bcf4712ae8459d148d3f778":{
      "scriptId":"u17"},
    "a965ebfd6b51497597c520c5c3b60e63":{
      "scriptId":"u18"},
    "1741f5193003492ea037e948c3bede59":{
      "scriptId":"u19"},
    "4fa0d8c7e95f40489d11c786ef52f626":{
      "scriptId":"u20"},
    "ffb456a2d47a42a5a9f34f6c964e687c":{
      "scriptId":"u21"},
    "a072185d127f4a63b87fcb82f1da82ee":{
      "scriptId":"u22"},
    "714c9184a3ed4dd6876c974df7336964":{
      "scriptId":"u23"},
    "913eccf3c8d14129a66e8cee563ee1d5":{
      "scriptId":"u24"},
    "9710a83535b2476da40d3e1c10fc0fff":{
      "scriptId":"u25"},
    "80381bc5dc474f8db7fa67caab505939":{
      "scriptId":"u26"},
    "044a7c1d3baa4c58ac6439e443d97c25":{
      "scriptId":"u27"},
    "4488ac3ff2404485a43e4a6d3d727fda":{
      "scriptId":"u28"},
    "9b916ba4272b48d0a71fbd7a3580b9aa":{
      "scriptId":"u29"},
    "b7dd89fea9b54fbab0f5d1cb2b6b4626":{
      "scriptId":"u30"},
    "64d355e8d9a44db7b01e6fb41a95668a":{
      "scriptId":"u31"},
    "d4dcd9115d8e4e59a7ee9f7e6a4e1c57":{
      "scriptId":"u32"},
    "7e3b6ade5cfb44b1a1aa8d05f404b439":{
      "scriptId":"u33"},
    "59cd94674a6b41f893e10360bbb2cef3":{
      "scriptId":"u34"},
    "303901dd658541028d332d92cbb228e7":{
      "scriptId":"u35"},
    "74e67be2805646c5942dbbad66578a03":{
      "scriptId":"u36"},
    "f1a0c515187d4c2fb5d6383486f61d4b":{
      "scriptId":"u37"},
    "9bb45f79b4394fa0a3729d8d8c889478":{
      "scriptId":"u38"},
    "9c497b5d5984488488f355bff360ba51":{
      "scriptId":"u39"},
    "169df8a1e77c4a6882eed80f9c202132":{
      "scriptId":"u40"},
    "11f5abf3acf5418eb234739563723fb2":{
      "scriptId":"u41"},
    "706cfc3b302f4bd3a8fe1b2bcc39dd99":{
      "scriptId":"u42"},
    "13d42275f62a4056a10cedc564a829b3":{
      "scriptId":"u43"},
    "ad3a48bb283f49aeb0f47641d3a05512":{
      "scriptId":"u44"},
    "e5f43f7242564a29b074069a74c0a105":{
      "scriptId":"u45"},
    "d33478ffebf74b23846bf38d3b58d5be":{
      "scriptId":"u46"},
    "498d30c2032c45aa884c19ab5e066fd8":{
      "scriptId":"u47"},
    "c372ac5cd0b64b8495011ea2c3a747cc":{
      "scriptId":"u48"},
    "d2a8d4aac6c74931a82abeb2531ebb9e":{
      "scriptId":"u49"},
    "05a02bac9cdc42b6910fe3924a0f6f3d":{
      "scriptId":"u50"},
    "79edd5986b6b4d47bb8eaded93f968ce":{
      "scriptId":"u51"},
    "240a14c92b864d0c90b00f3d6877b7bd":{
      "scriptId":"u52"},
    "5ca1e8f89b5a46b18d9326b3638a8bed":{
      "scriptId":"u53"},
    "3733009205634c239b049e290c2d2df3":{
      "scriptId":"u54"},
    "e57b261d918b401f9ebada5da73dcefa":{
      "scriptId":"u55"},
    "95551f54a9894974a8d1241e5ad26b0a":{
      "scriptId":"u56"},
    "095ca87793ac42a9b0a9b7a03b755cf8":{
      "scriptId":"u57"},
    "5f6245cebfd64782881b944784e752d7":{
      "scriptId":"u58"},
    "afa6987d7e6d41689ebc66dc1f64b97d":{
      "scriptId":"u59"},
    "5dd9ad95ab8d482182bb25f4f183851c":{
      "scriptId":"u60"},
    "f67c9d961b9c43ca82d2e38334af0c0b":{
      "scriptId":"u61"},
    "733a5575f43040b5924fd67f6bdb7def":{
      "scriptId":"u62"},
    "afb2330363364b27b06546ef9f7152d6":{
      "scriptId":"u63"},
    "90e04d314118495f95cef48630b420af":{
      "scriptId":"u64"},
    "732f71a2d02a47309521c979531ca0f4":{
      "scriptId":"u65"},
    "b32beefcdc7c4da9b3e337a0c55f1cf0":{
      "scriptId":"u66"},
    "b7d7680862bb4cbca836f2fbdc9fd6bb":{
      "scriptId":"u67"},
    "ea381438b1ed4ab3ac0aa531f9981bee":{
      "scriptId":"u68"},
    "ba8f37f5173248eaa2a6cd9463a32978":{
      "scriptId":"u69"},
    "f13e1e3531224b27945f9e92befc54cb":{
      "scriptId":"u70"},
    "bab7cae5cf5842c4bc2e43f5ceb37924":{
      "scriptId":"u71"},
    "b04607f50ce64e09b6a7b58198552474":{
      "scriptId":"u72"},
    "4fb2454f1d964134ac5520411b2654e2":{
      "scriptId":"u73"},
    "e468ef98b4524622b8a57d094739240c":{
      "scriptId":"u74"},
    "375b037c42974d269f2ae3449ce0f3eb":{
      "scriptId":"u75"},
    "ecb5a9741c584a77a47d283e2b032a46":{
      "scriptId":"u76"},
    "e39b678731804b9e8d2e3d0e75b8821e":{
      "scriptId":"u77"},
    "9b3ab9a8a72e46e89add4e837a0e4404":{
      "scriptId":"u78"},
    "9a6415168b5641e0aac038b78f8c1eed":{
      "scriptId":"u79"},
    "da315865aa04448d97eb45457a83b521":{
      "scriptId":"u80"},
    "bd37f9ddf1084f528e07421f77caa90a":{
      "scriptId":"u81"},
    "ee244b76d2ea4aafb6578122e5d43bb3":{
      "scriptId":"u82"},
    "e0fe654f50e54ced9e3ab72579383c14":{
      "scriptId":"u83"}}});