$axure.loadCurrentPage({
  "url":"课件_1.html",
  "generationDate":new Date(1494572322558.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"37853265129e4817b726a7823d8d56c3",
    "type":"Axure:Page",
    "name":"课件",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6bd2821bf8924887af1dc836f2b0e59c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":997,
              "y":77},
            "size":{
              "width":313,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9f1d8cd15b644b2bbfc9059ffe54555",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":997,
                  "y":77},
                "size":{
                  "width":313,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"853c191f9af349a6b6bcd25de9055390",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":54},
            "size":{
              "width":980,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcacb3e8bc744d93a11a3d76ecb30dea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":54},
                "size":{
                  "width":980,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课堂实录/u2.png"}},
{
          "id":"69b1e173c2a047bf8ae23124ea6c3e05",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "location":{
              "x":155,
              "y":72},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5b8319b7742430f8c3c2972b9638b39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "location":{
                  "x":155,
                  "y":72},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 备课",
                      "target":{
                        "targetType":"page",
                        "url":"备课.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e669c35d5a1400096ec6bc818c75799",
          "label":"xueke",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1}}},
            "location":{
              "x":371,
              "y":72},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c174a31be5b749298ad280eb731e8101",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF33CCCC,
                      "opacity":1}}},
                "location":{
                  "x":371,
                  "y":72},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学科介绍",
                      "target":{
                        "targetType":"page",
                        "url":"学科介绍.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 xueke = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8e669c35d5a1400096ec6bc818c75799"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 xueke = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8e669c35d5a1400096ec6bc818c75799"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif"}},
{
          "id":"16a0936c8e70436c8cb010de306fd874",
          "label":"peixun1",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1}}},
            "location":{
              "x":580,
              "y":72},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fd4f408c85147f290e358afaa0ee4b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF33CCCC,
                      "opacity":1}}},
                "location":{
                  "x":580,
                  "y":72},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 培训中心",
                      "target":{
                        "targetType":"page",
                        "url":"培训中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun1 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["16a0936c8e70436c8cb010de306fd874"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun1 = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["16a0936c8e70436c8cb010de306fd874"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif"}},
{
          "id":"e53536b6c077406295e11b4887dc3732",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":137,
              "y":102},
            "size":{
              "width":105,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF33CCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/备课/u51_line.png"}},
{
          "id":"61e21e6eadd94be3ab1664b926e47afe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":900},
            "size":{
              "width":964,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9647222037c4464e967c1ad25fd0e773",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":16,
                  "y":900},
                "size":{
                  "width":964,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/备课/u131.png"}},
{
          "id":"5d6d736a25e0463f98059ff0883a3e54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF336666,
              "opacity":1},
            "location":{
              "x":54,
              "y":913},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c075f3e1c1b342368fb27565606e26f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF336666,
                  "opacity":1},
                "location":{
                  "x":54,
                  "y":913},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9698ff6eb67d404dabc1e700db725457",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":122},
            "size":{
              "width":980,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "outerShadow":{
              "on":false,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":2,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8ef17976ff9477aa5623deca36bf2af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":122},
                "size":{
                  "width":980,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "outerShadow":{
                  "on":false,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":2,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课堂实录/u15.png"}},
{
          "id":"b9c63c1c645140e2aa5c40dca57d072f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":16,
              "y":137},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afbaa109394742049533456fbc4a2fd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":137},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8829bde83e8b448fb13ae096aa970006",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":90,
              "y":142},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f217434c11e9456a9ff74df463107adc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":90,
                  "y":142},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/讲课_教师讲义/u42.png"}},
{
          "id":"8046c007fed84381944a3df743ce4878",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":110,
              "y":136},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1955bc334fb46b9b015f153900f79a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":136},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1f4c16486a94e96850e3462e6ef5062",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00}}},
            "location":{
              "x":1,
              "y":169},
            "size":{
              "width":224,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90269099965a4c649eb346192aea01a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00FF00}}},
                "location":{
                  "x":1,
                  "y":169},
                "size":{
                  "width":224,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讲课/教师讲义",
                      "target":{
                        "targetType":"page",
                        "url":"讲课_教师讲义.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/u52.png",
            "mouseOver~":"images/讲课_教师讲义/u48.png"}},
{
          "id":"400fcebd59c54453afae28059cde9748",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":169},
            "size":{
              "width":748,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa75cf08cd8e4c1b992039d076c6abd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":169},
                "size":{
                  "width":748,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课堂实录/u29.png"}},
{
          "id":"570e6f930ae1483494d0c3eb7ef411d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF00},
            "location":{
              "x":1,
              "y":229},
            "size":{
              "width":224,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac8411c8b1074174a0fedc841abad952",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00FF00}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00},
                "location":{
                  "x":1,
                  "y":229},
                "size":{
                  "width":224,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课件",
                      "target":{
                        "targetType":"page",
                        "url":"课件.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/u48.png",
            "mouseOver~":"images/讲课_教师讲义/u48.png"}},
{
          "id":"45ba77e48a7742818216a762d86dc2e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00}}},
            "location":{
              "x":1,
              "y":289},
            "size":{
              "width":224,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b12066047f4247e29949fa8c3d17f097",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00FF00}}},
                "location":{
                  "x":1,
                  "y":289},
                "size":{
                  "width":224,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课堂实录",
                      "target":{
                        "targetType":"page",
                        "url":"课堂实录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/u52.png",
            "mouseOver~":"images/讲课_教师讲义/u48.png"}},
{
          "id":"3b1cc40a81464b9e8ccebdb71bd43c26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "location":{
              "x":734,
              "y":132},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8bdac4bde62403e974170562b442fe6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "location":{
                  "x":734,
                  "y":132},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 shipinbfq 灯箱效果",
                      "objectsToFades":[{
                          "objectPath":["9e36675d65d5499c8fc5315b2238d127"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"lightbox",
                              "lightbox":{
                                "r":47,
                                "g":79,
                                "b":79,
                                "a":155}}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/u58.png",
            "mouseOver~":"images/讲课_教师讲义/u58_mouseOver.png"}},
{
          "id":"47a077e48c014a478074adb9d139ca55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":677,
              "y":140},
            "size":{
              "width":46,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9850af61cfa455cb7456fb450eb58fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":677,
                  "y":140},
                "size":{
                  "width":46,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea413e01f15145d1b47af3f0e4acc3b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "location":{
              "x":778,
              "y":132},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5476b5b4e3284b48acd00aa68ca1d9d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "location":{
                  "x":778,
                  "y":132},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 shipinbfq 灯箱效果",
                      "objectsToFades":[{
                          "objectPath":["9e36675d65d5499c8fc5315b2238d127"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"lightbox",
                              "lightbox":{
                                "r":47,
                                "g":79,
                                "b":79,
                                "a":155}}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/u58.png",
            "mouseOver~":"images/讲课_教师讲义/u58_mouseOver.png"}},
{
          "id":"fa7deb881fe34ac9b93a25390d6e29e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "location":{
              "x":821,
              "y":132},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5eb9dab5e106420a83f41669875d8753",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "location":{
                  "x":821,
                  "y":132},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 shipinbfq 灯箱效果",
                      "objectsToFades":[{
                          "objectPath":["9e36675d65d5499c8fc5315b2238d127"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"lightbox",
                              "lightbox":{
                                "r":47,
                                "g":79,
                                "b":79,
                                "a":155}}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/u58.png",
            "mouseOver~":"images/讲课_教师讲义/u58_mouseOver.png"}},
{
          "id":"a2e48cf46b8e4bbdbf232afb912a89c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "location":{
              "x":861,
              "y":132},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b879ce36e40842a3b58ede2dde15def9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "location":{
                  "x":861,
                  "y":132},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 shipinbfq 灯箱效果",
                      "objectsToFades":[{
                          "objectPath":["9e36675d65d5499c8fc5315b2238d127"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"lightbox",
                              "lightbox":{
                                "r":47,
                                "g":79,
                                "b":79,
                                "a":155}}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/u58.png",
            "mouseOver~":"images/讲课_教师讲义/u58_mouseOver.png"}},
{
          "id":"f94b159a440948dcb76344d79ec3422a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00FF00,
                  "opacity":1}}},
            "location":{
              "x":859,
              "y":182},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a58934c015c0424183d690002c9d6c26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF00FF00,
                      "opacity":1}}},
                "location":{
                  "x":859,
                  "y":182},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"b4b9f06636c242258e0bfff7774cf357",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":209},
            "size":{
              "width":748,
              "height":681},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0f0bf763ea946ebac9b1c9fc89b2de9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":209},
                "size":{
                  "width":748,
                  "height":681},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课堂实录/u49.png"}},
{
          "id":"497e692ded1c4c2790d6ee9e37e3dfc6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":960,
              "y":204},
            "size":{
              "width":220,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/讲课_教师讲义/u72_line.png"}},
{
          "id":"39df8921061643958e25642b9ac32044",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":967,
              "y":169},
            "size":{
              "width":261,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2607435f306541578cf90f0156deb9a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":967,
                  "y":169},
                "size":{
                  "width":261,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ec9969061fc431e91f920f772c42a57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":967,
              "y":127},
            "size":{
              "width":339,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9880ca3bb754d439d8006bcc629ee49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":967,
                  "y":127},
                "size":{
                  "width":339,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61f59f806d6a4554aa7dc9e9492503ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":960,
              "y":240},
            "size":{
              "width":326,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99a0d56c7dd74705966e3cd694d717cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":960,
                  "y":240},
                "size":{
                  "width":326,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99213e06b5b04f80b1fe19bef92a5c94",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":209},
            "size":{
              "width":677,
              "height":510}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e21eef82c7544ce49f567afdb200a9ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":209},
                "size":{
                  "width":677,
                  "height":510}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课件/u58.png"}},
{
          "id":"9e36675d65d5499c8fc5315b2238d127",
          "label":"shipinbfq",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":80,
              "y":204},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"61c5e169d18143fcbcda60221d5a321f",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8f7b447db6624394946aaf10eb80c3d2",
                  "label":"",
                  "parentDynamicPanel":"9e36675d65d5499c8fc5315b2238d127",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":805,
                      "height":440},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7641f187c93d46c4bff148df9044a933",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9e36675d65d5499c8fc5315b2238d127",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":805,
                          "height":440},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课_教师讲义/u80.png"}},
{
                  "id":"790b5f139b724fdb9e8fa1d5001a8af2",
                  "label":"",
                  "parentDynamicPanel":"9e36675d65d5499c8fc5315b2238d127",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":766,
                      "y":4},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0d74b0ec29294ba288155fed04c1b15a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9e36675d65d5499c8fc5315b2238d127",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":766,
                          "y":4},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 shipinbfq",
                              "objectsToFades":[{
                                  "objectPath":["9e36675d65d5499c8fc5315b2238d127"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"8fb15c99a9d547babe9d555eb9d981a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":950,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98fad27e22d04e35b71f5799454284f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":950,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/备课/u2.png"}},
{
          "id":"1320b81005344f54a8c247f4da958a6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":9},
            "size":{
              "width":68,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f656b23b72d45159025fd4da5b8984b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":9},
                "size":{
                  "width":68,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea06158aa8a64dc68fcca48d8eb12b62",
          "label":"beike",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":119,
              "y":14},
            "size":{
              "width":80,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41963a1382a44997825bb09d54685761",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":119,
                  "y":14},
                "size":{
                  "width":80,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 备课",
                      "target":{
                        "targetType":"page",
                        "url":"备课.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 beike = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["ea06158aa8a64dc68fcca48d8eb12b62"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 beike = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["ea06158aa8a64dc68fcca48d8eb12b62"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/beike_u4.png",
            "selected~":"images/讲课_教师讲义/beike_u4_selected.png"}},
{
          "id":"c4604287d50a42418fa6dcd8e68260e5",
          "label":"souke",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":208,
              "y":14},
            "size":{
              "width":65,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70dca594012a425184f02890f40fcdc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":208,
                  "y":14},
                "size":{
                  "width":65,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页/授课",
                      "target":{
                        "targetType":"page",
                        "url":"首页_授课.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 souke = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["c4604287d50a42418fa6dcd8e68260e5"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 souke = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["c4604287d50a42418fa6dcd8e68260e5"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/souke_u6.png",
            "selected~":"images/讲课_教师讲义/souke_u6_selected.png"}},
{
          "id":"319cfcf0f608490d9c1614e29ef4c383",
          "label":"guanli",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":282,
              "y":14},
            "size":{
              "width":70,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eecaa9a482764e5c82548f5a7f0d9e8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":282,
                  "y":14},
                "size":{
                  "width":70,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 校内管理",
                      "target":{
                        "targetType":"page",
                        "url":"校内管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 guanli = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["319cfcf0f608490d9c1614e29ef4c383"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 guanli = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["319cfcf0f608490d9c1614e29ef4c383"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/guanli_u8.png",
            "selected~":"images/讲课_教师讲义/guanli_u8_selected.png"}},
{
          "id":"1bb9779464f34c8d9392114057b4954d",
          "label":"ceping",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":362,
              "y":14},
            "size":{
              "width":51,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91dbc173e38a46d08a4046c929eb29f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":362,
                  "y":14},
                "size":{
                  "width":51,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测评",
                      "target":{
                        "targetType":"page",
                        "url":"测评.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 ceping = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["1bb9779464f34c8d9392114057b4954d"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 ceping = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["1bb9779464f34c8d9392114057b4954d"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/ceping_u10.png",
            "selected~":"images/讲课_教师讲义/ceping_u10_selected.png"}},
{
          "id":"65e69c9e3c604ce1bb8102b3031b2203",
          "label":"peixun",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":423,
              "y":14},
            "size":{
              "width":58,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a90e91aa00eb49d9a675f82b0dc4d5a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":423,
                  "y":14},
                "size":{
                  "width":58,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 培训",
                      "target":{
                        "targetType":"page",
                        "url":"培训.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["65e69c9e3c604ce1bb8102b3031b2203"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["65e69c9e3c604ce1bb8102b3031b2203"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/peixun_u12.png",
            "selected~":"images/讲课_教师讲义/peixun_u12_selected.png"}},
{
          "id":"9b93edd5ded0489e8c4d2573a06c2dfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":14},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92fe81e3f1904598a1926437640ed96e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":850,
                  "y":14},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 user 弹出效果",
                      "objectsToFades":[{
                          "objectPath":["ba2de5c33da54607aeebc1db4717f227"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"flyout"}}}]}]}]}},
          "images":{
            "normal~":"images/备课/u16.png"}},
{
          "id":"ba2de5c33da54607aeebc1db4717f227",
          "label":"user",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":850,
              "y":43},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"c62c125a63644bd7ba5ffc0f925dc6f7",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"48a52a49b839450386b7914f9c8b5509",
                  "label":"",
                  "parentDynamicPanel":"ba2de5c33da54607aeebc1db4717f227",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFA1A1A1,
                      "opacity":1},
                    "size":{
                      "width":90,
                      "height":27},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF3399}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"abe7ce05e6774f8695ad21172365174d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ba2de5c33da54607aeebc1db4717f227",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFA1A1A1,
                          "opacity":1},
                        "size":{
                          "width":90,
                          "height":27},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF3399}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/备课/u53.png"}},
{
                  "id":"0621dbd0ace44e7092ee643e86bfe425",
                  "label":"",
                  "parentDynamicPanel":"ba2de5c33da54607aeebc1db4717f227",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFA1A1A1,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":26},
                    "size":{
                      "width":90,
                      "height":27},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF3399}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fc86516979be4e6a8111d7103ae9f3eb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ba2de5c33da54607aeebc1db4717f227",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFA1A1A1,
                          "opacity":1},
                        "location":{
                          "x":0,
                          "y":26},
                        "size":{
                          "width":90,
                          "height":27},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF3399}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/备课/u53.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "6bd2821bf8924887af1dc836f2b0e59c":{
      "scriptId":"u0"},
    "f9f1d8cd15b644b2bbfc9059ffe54555":{
      "scriptId":"u1"},
    "853c191f9af349a6b6bcd25de9055390":{
      "scriptId":"u2"},
    "fcacb3e8bc744d93a11a3d76ecb30dea":{
      "scriptId":"u3"},
    "69b1e173c2a047bf8ae23124ea6c3e05":{
      "scriptId":"u4"},
    "a5b8319b7742430f8c3c2972b9638b39":{
      "scriptId":"u5"},
    "8e669c35d5a1400096ec6bc818c75799":{
      "scriptId":"u6"},
    "c174a31be5b749298ad280eb731e8101":{
      "scriptId":"u7"},
    "16a0936c8e70436c8cb010de306fd874":{
      "scriptId":"u8"},
    "7fd4f408c85147f290e358afaa0ee4b6":{
      "scriptId":"u9"},
    "e53536b6c077406295e11b4887dc3732":{
      "scriptId":"u10"},
    "61e21e6eadd94be3ab1664b926e47afe":{
      "scriptId":"u11"},
    "9647222037c4464e967c1ad25fd0e773":{
      "scriptId":"u12"},
    "5d6d736a25e0463f98059ff0883a3e54":{
      "scriptId":"u13"},
    "c075f3e1c1b342368fb27565606e26f9":{
      "scriptId":"u14"},
    "9698ff6eb67d404dabc1e700db725457":{
      "scriptId":"u15"},
    "e8ef17976ff9477aa5623deca36bf2af":{
      "scriptId":"u16"},
    "b9c63c1c645140e2aa5c40dca57d072f":{
      "scriptId":"u17"},
    "afbaa109394742049533456fbc4a2fd3":{
      "scriptId":"u18"},
    "8829bde83e8b448fb13ae096aa970006":{
      "scriptId":"u19"},
    "f217434c11e9456a9ff74df463107adc":{
      "scriptId":"u20"},
    "8046c007fed84381944a3df743ce4878":{
      "scriptId":"u21"},
    "f1955bc334fb46b9b015f153900f79a8":{
      "scriptId":"u22"},
    "a1f4c16486a94e96850e3462e6ef5062":{
      "scriptId":"u23"},
    "90269099965a4c649eb346192aea01a5":{
      "scriptId":"u24"},
    "400fcebd59c54453afae28059cde9748":{
      "scriptId":"u25"},
    "aa75cf08cd8e4c1b992039d076c6abd3":{
      "scriptId":"u26"},
    "570e6f930ae1483494d0c3eb7ef411d3":{
      "scriptId":"u27"},
    "ac8411c8b1074174a0fedc841abad952":{
      "scriptId":"u28"},
    "45ba77e48a7742818216a762d86dc2e1":{
      "scriptId":"u29"},
    "b12066047f4247e29949fa8c3d17f097":{
      "scriptId":"u30"},
    "3b1cc40a81464b9e8ccebdb71bd43c26":{
      "scriptId":"u31"},
    "f8bdac4bde62403e974170562b442fe6":{
      "scriptId":"u32"},
    "47a077e48c014a478074adb9d139ca55":{
      "scriptId":"u33"},
    "e9850af61cfa455cb7456fb450eb58fb":{
      "scriptId":"u34"},
    "ea413e01f15145d1b47af3f0e4acc3b4":{
      "scriptId":"u35"},
    "5476b5b4e3284b48acd00aa68ca1d9d0":{
      "scriptId":"u36"},
    "fa7deb881fe34ac9b93a25390d6e29e7":{
      "scriptId":"u37"},
    "5eb9dab5e106420a83f41669875d8753":{
      "scriptId":"u38"},
    "a2e48cf46b8e4bbdbf232afb912a89c1":{
      "scriptId":"u39"},
    "b879ce36e40842a3b58ede2dde15def9":{
      "scriptId":"u40"},
    "f94b159a440948dcb76344d79ec3422a":{
      "scriptId":"u41"},
    "a58934c015c0424183d690002c9d6c26":{
      "scriptId":"u42"},
    "b4b9f06636c242258e0bfff7774cf357":{
      "scriptId":"u43"},
    "b0f0bf763ea946ebac9b1c9fc89b2de9":{
      "scriptId":"u44"},
    "497e692ded1c4c2790d6ee9e37e3dfc6":{
      "scriptId":"u45"},
    "39df8921061643958e25642b9ac32044":{
      "scriptId":"u46"},
    "2607435f306541578cf90f0156deb9a8":{
      "scriptId":"u47"},
    "7ec9969061fc431e91f920f772c42a57":{
      "scriptId":"u48"},
    "b9880ca3bb754d439d8006bcc629ee49":{
      "scriptId":"u49"},
    "61f59f806d6a4554aa7dc9e9492503ba":{
      "scriptId":"u50"},
    "99a0d56c7dd74705966e3cd694d717cb":{
      "scriptId":"u51"},
    "99213e06b5b04f80b1fe19bef92a5c94":{
      "scriptId":"u52"},
    "e21eef82c7544ce49f567afdb200a9ee":{
      "scriptId":"u53"},
    "9e36675d65d5499c8fc5315b2238d127":{
      "scriptId":"u54"},
    "8f7b447db6624394946aaf10eb80c3d2":{
      "scriptId":"u55"},
    "7641f187c93d46c4bff148df9044a933":{
      "scriptId":"u56"},
    "790b5f139b724fdb9e8fa1d5001a8af2":{
      "scriptId":"u57"},
    "0d74b0ec29294ba288155fed04c1b15a":{
      "scriptId":"u58"},
    "8fb15c99a9d547babe9d555eb9d981a2":{
      "scriptId":"u59"},
    "98fad27e22d04e35b71f5799454284f6":{
      "scriptId":"u60"},
    "1320b81005344f54a8c247f4da958a6c":{
      "scriptId":"u61"},
    "8f656b23b72d45159025fd4da5b8984b":{
      "scriptId":"u62"},
    "ea06158aa8a64dc68fcca48d8eb12b62":{
      "scriptId":"u63"},
    "41963a1382a44997825bb09d54685761":{
      "scriptId":"u64"},
    "c4604287d50a42418fa6dcd8e68260e5":{
      "scriptId":"u65"},
    "70dca594012a425184f02890f40fcdc8":{
      "scriptId":"u66"},
    "319cfcf0f608490d9c1614e29ef4c383":{
      "scriptId":"u67"},
    "eecaa9a482764e5c82548f5a7f0d9e8a":{
      "scriptId":"u68"},
    "1bb9779464f34c8d9392114057b4954d":{
      "scriptId":"u69"},
    "91dbc173e38a46d08a4046c929eb29f1":{
      "scriptId":"u70"},
    "65e69c9e3c604ce1bb8102b3031b2203":{
      "scriptId":"u71"},
    "a90e91aa00eb49d9a675f82b0dc4d5a7":{
      "scriptId":"u72"},
    "9b93edd5ded0489e8c4d2573a06c2dfb":{
      "scriptId":"u73"},
    "92fe81e3f1904598a1926437640ed96e":{
      "scriptId":"u74"},
    "ba2de5c33da54607aeebc1db4717f227":{
      "scriptId":"u75"},
    "48a52a49b839450386b7914f9c8b5509":{
      "scriptId":"u76"},
    "abe7ce05e6774f8695ad21172365174d":{
      "scriptId":"u77"},
    "0621dbd0ace44e7092ee643e86bfe425":{
      "scriptId":"u78"},
    "fc86516979be4e6a8111d7103ae9f3eb":{
      "scriptId":"u79"}}});