$axure.loadCurrentPage({
  "url":"课堂实录_1.html",
  "generationDate":new Date(1494572322751.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c8ca12bff3484205a5f51b00b2271169",
    "type":"Axure:Page",
    "name":"课堂实录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"35883f4c7eab4147a3da12149411decb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":997,
              "y":77},
            "size":{
              "width":313,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c126df58d4a4335bcaeed20b898b22a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":997,
                  "y":77},
                "size":{
                  "width":313,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a49ef5b418642299a61734248e2f637",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":54},
            "size":{
              "width":980,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8658d4197b8243d3a653704a7f318f1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":54},
                "size":{
                  "width":980,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课堂实录/u2.png"}},
{
          "id":"e1f7fe55c2da442d910e46603c0df30b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"17px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33CCCC,
              "opacity":1},
            "location":{
              "x":155,
              "y":72},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66c8c02837da4f0690661e6951b5fc95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"17px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1},
                "location":{
                  "x":155,
                  "y":72},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 备课",
                      "target":{
                        "targetType":"page",
                        "url":"备课.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"140e8bf515664b05aab8e1ff6b486e69",
          "label":"xueke",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1}}},
            "location":{
              "x":371,
              "y":72},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5295244d15d444d81defd2ec61b9da6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF33CCCC,
                      "opacity":1}}},
                "location":{
                  "x":371,
                  "y":72},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学科介绍",
                      "target":{
                        "targetType":"page",
                        "url":"学科介绍.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 xueke = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["140e8bf515664b05aab8e1ff6b486e69"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 xueke = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["140e8bf515664b05aab8e1ff6b486e69"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif"}},
{
          "id":"d998d84ee23c418180b9fc413b4445d7",
          "label":"peixun1",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"17px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFAEAEAE,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33CCCC,
                  "opacity":1}}},
            "location":{
              "x":580,
              "y":72},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3dd49fc9e2e4e299440a46200d5349d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"17px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFAEAEAE,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF33CCCC,
                      "opacity":1}}},
                "location":{
                  "x":580,
                  "y":72},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 培训中心",
                      "target":{
                        "targetType":"page",
                        "url":"培训中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun1 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["d998d84ee23c418180b9fc413b4445d7"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun1 = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["d998d84ee23c418180b9fc413b4445d7"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "selected~":"resources/images/transparent.gif"}},
{
          "id":"1c60d27d6ecf404192a20a79ce5ce75d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":137,
              "y":102},
            "size":{
              "width":105,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF33CCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/备课/u51_line.png"}},
{
          "id":"232df10b052142cdb8e9f05953a38a92",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":900},
            "size":{
              "width":964,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c33aa22beef24076a1cb610af4d6ba3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":16,
                  "y":900},
                "size":{
                  "width":964,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/备课/u131.png"}},
{
          "id":"960f469b6674452dbaddd5379998f7cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF336666,
              "opacity":1},
            "location":{
              "x":54,
              "y":913},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38a9af47fabc41c4aad97d8fd2555b9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF336666,
                  "opacity":1},
                "location":{
                  "x":54,
                  "y":913},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6168a78f4d84b68ad32c03eee304e15",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":122},
            "size":{
              "width":980,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "outerShadow":{
              "on":false,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":2,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a006d195e03a400585f153d20b2b4968",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":122},
                "size":{
                  "width":980,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "outerShadow":{
                  "on":false,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":2,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课堂实录/u15.png"}},
{
          "id":"11e6d4f019c14d90b49d54ee373ac4a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":16,
              "y":137},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e3b383a64604267a54ddc90cfb1ff96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":16,
                  "y":137},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cc09e5b11994c17a453b4fbf9468024",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":90,
              "y":142},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b1d8beb19524c78bc2042d054b25d21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":90,
                  "y":142},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/讲课_教师讲义/u42.png"}},
{
          "id":"a9732fde5864430fa67d49cc7dd3cd86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":120,
              "y":136},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23409cc61ed44703bea772be7b776e4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":136},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc4cdb049134448d8d68e8e347efcd94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00}}},
            "location":{
              "x":1,
              "y":169},
            "size":{
              "width":224,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13a0f235655044f5aec9399ddd70a773",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00FF00}}},
                "location":{
                  "x":1,
                  "y":169},
                "size":{
                  "width":224,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 讲课/教师讲义",
                      "target":{
                        "targetType":"page",
                        "url":"讲课_教师讲义.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/u52.png",
            "mouseOver~":"images/讲课_教师讲义/u48.png"}},
{
          "id":"684c7525179d4368a24160876e67afcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":169},
            "size":{
              "width":748,
              "height":41},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af1ab2afd4344391ba229abf57c2c147",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":169},
                "size":{
                  "width":748,
                  "height":41},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课堂实录/u29.png"}},
{
          "id":"f98f966e28e149728400bc4b2eb1848e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00}}},
            "location":{
              "x":1,
              "y":229},
            "size":{
              "width":224,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a30b3e7a1b64652a6a73bf9313be37d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00FF00}}},
                "location":{
                  "x":1,
                  "y":229},
                "size":{
                  "width":224,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课件",
                      "target":{
                        "targetType":"page",
                        "url":"课件.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/u52.png",
            "mouseOver~":"images/讲课_教师讲义/u48.png"}},
{
          "id":"d55867c9e13f4088b40f693d0ff1130c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF00},
            "location":{
              "x":0,
              "y":290},
            "size":{
              "width":224,
              "height":61},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3bf4f97c25d47e6835a5ff7ca63bb0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF00FF00}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00},
                "location":{
                  "x":0,
                  "y":290},
                "size":{
                  "width":224,
                  "height":61},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 课堂实录",
                      "target":{
                        "targetType":"page",
                        "url":"课堂实录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/u48.png",
            "mouseOver~":"images/讲课_教师讲义/u48.png"}},
{
          "id":"57cfcca1ddb84b6e8663b4b427088830",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "location":{
              "x":734,
              "y":132},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd4abee5d9554120bbef1c0d3861d2af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "location":{
                  "x":734,
                  "y":132},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 shipinbfq",
                      "objectsToFades":[{
                          "objectPath":["e18d8e3735a049619043af4662f0cccf"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/u58.png",
            "mouseOver~":"images/讲课_教师讲义/u58_mouseOver.png"}},
{
          "id":"cfd40af688464943966b1e4fa7bfed9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "location":{
              "x":677,
              "y":140},
            "size":{
              "width":46,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08af48c8b5dd42c9842f21516e5ea371",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "location":{
                  "x":677,
                  "y":140},
                "size":{
                  "width":46,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"903142f07feb427ba4940bc05516f730",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "location":{
              "x":778,
              "y":132},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5994df43b9cb42b0b692c2751aea3ba2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "location":{
                  "x":778,
                  "y":132},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 shipinbfq",
                      "objectsToFades":[{
                          "objectPath":["e18d8e3735a049619043af4662f0cccf"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/u58.png",
            "mouseOver~":"images/讲课_教师讲义/u58_mouseOver.png"}},
{
          "id":"bf2696cf6c6849fa868dbd7fd0a4e6d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "location":{
              "x":821,
              "y":132},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24398efc0cc846999608c62a2382dfe9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "location":{
                  "x":821,
                  "y":132},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 shipinbfq",
                      "objectsToFades":[{
                          "objectPath":["e18d8e3735a049619043af4662f0cccf"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/u58.png",
            "mouseOver~":"images/讲课_教师讲义/u58_mouseOver.png"}},
{
          "id":"a2528b08d22345f2bbc728d86c9f508e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "location":{
              "x":861,
              "y":132},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53ee409a2fc041868a7933880da7026b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "location":{
                  "x":861,
                  "y":132},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 shipinbfq",
                      "objectsToFades":[{
                          "objectPath":["e18d8e3735a049619043af4662f0cccf"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/u58.png",
            "mouseOver~":"images/讲课_教师讲义/u58_mouseOver.png"}},
{
          "id":"63fbf48b87734ac4a006bca5b7010b26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00FF00,
                  "opacity":1}}},
            "location":{
              "x":859,
              "y":182},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb2a8a38be2d4e22b3841a7e924b4b4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF00FF00,
                      "opacity":1}}},
                "location":{
                  "x":859,
                  "y":182},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"94533cd7f437495eb47d7e3f7d8f66fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":209},
            "size":{
              "width":748,
              "height":681},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55c89fde890c471f82a5d05cf689a104",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":232,
                  "y":209},
                "size":{
                  "width":748,
                  "height":681},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课堂实录/u49.png"}},
{
          "id":"267fb8af3fde4d5984d1fde40db72be6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":960,
              "y":204},
            "size":{
              "width":220,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/讲课_教师讲义/u72_line.png"}},
{
          "id":"6dc9b5faaf48482cb95a5bc46be7233b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":967,
              "y":169},
            "size":{
              "width":261,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c1258e62a054f0398ad546bd61d32e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":967,
                  "y":169},
                "size":{
                  "width":261,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93a939e6a3a54587a9cf66ddcc19c954",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":967,
              "y":127},
            "size":{
              "width":339,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c3e6ea7613747ce829e63406e038ffd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":967,
                  "y":127},
                "size":{
                  "width":339,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99332b0f4cee4431866566c3fe7ea2a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":960,
              "y":240},
            "size":{
              "width":326,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66823068f2994bb485e4e5ef1a7fa31b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":960,
                  "y":240},
                "size":{
                  "width":326,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4319fd152e84fac83f4cec0f888e6d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":220},
            "size":{
              "width":650,
              "height":540},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d0841885b3347f8b51fbe92dc076957",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":220},
                "size":{
                  "width":650,
                  "height":540},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/课堂实录/u58.png"}},
{
          "id":"e18d8e3735a049619043af4662f0cccf",
          "label":"shipinbfq",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":80,
              "y":204},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"872e9bab1b37457397de0f843418edc6",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"345e5605629c4284a6b5aed46a3de7ce",
                  "label":"",
                  "parentDynamicPanel":"e18d8e3735a049619043af4662f0cccf",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":805,
                      "height":440},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ac1e315c22f64f27ac260e12ce1bc77d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e18d8e3735a049619043af4662f0cccf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":805,
                          "height":440},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/讲课_教师讲义/u80.png"}},
{
                  "id":"a21dde3e0623412b8a602e6f26605e46",
                  "label":"",
                  "parentDynamicPanel":"e18d8e3735a049619043af4662f0cccf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":766,
                      "y":4},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4bc7d3d292f345d5806e7ce10d0f5858",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e18d8e3735a049619043af4662f0cccf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":766,
                          "y":4},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 shipinbfq",
                              "objectsToFades":[{
                                  "objectPath":["e18d8e3735a049619043af4662f0cccf"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"e6be0d0264014400b35ac276d47372d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":950,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"062974d8f4a64253b63e74be3b2db612",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":950,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/备课/u2.png"}},
{
          "id":"3e186fea5f734c89b3f749eacf8996f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":9},
            "size":{
              "width":68,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f653070f5e7149fdb7fa38a9c81bdec4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":9},
                "size":{
                  "width":68,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6ff5b811c1a4cbf8343de6ecfaea9c3",
          "label":"beike",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":119,
              "y":14},
            "size":{
              "width":80,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e414e8025b48480bbe10072f96b5a31a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":119,
                  "y":14},
                "size":{
                  "width":80,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 备课",
                      "target":{
                        "targetType":"page",
                        "url":"备课.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 beike = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a6ff5b811c1a4cbf8343de6ecfaea9c3"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 beike = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a6ff5b811c1a4cbf8343de6ecfaea9c3"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/beike_u4.png",
            "selected~":"images/讲课_教师讲义/beike_u4_selected.png"}},
{
          "id":"7a2995f083924c8eba7efcf418df90a6",
          "label":"souke",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":208,
              "y":14},
            "size":{
              "width":65,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad10182a65d24c1f832c94e89d36de13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":208,
                  "y":14},
                "size":{
                  "width":65,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页/授课",
                      "target":{
                        "targetType":"page",
                        "url":"首页_授课.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 souke = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["7a2995f083924c8eba7efcf418df90a6"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 souke = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["7a2995f083924c8eba7efcf418df90a6"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/souke_u6.png",
            "selected~":"images/讲课_教师讲义/souke_u6_selected.png"}},
{
          "id":"2fed1a9c4a954f71947b758fc92b8d12",
          "label":"guanli",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":282,
              "y":14},
            "size":{
              "width":70,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83a7d956bb46470ca049b6d109b6e9dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":282,
                  "y":14},
                "size":{
                  "width":70,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 校内管理",
                      "target":{
                        "targetType":"page",
                        "url":"校内管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 guanli = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2fed1a9c4a954f71947b758fc92b8d12"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 guanli = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2fed1a9c4a954f71947b758fc92b8d12"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/guanli_u8.png",
            "selected~":"images/讲课_教师讲义/guanli_u8_selected.png"}},
{
          "id":"bddeda486e2b41089e0abdee647b2b9e",
          "label":"ceping",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":362,
              "y":14},
            "size":{
              "width":51,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"782ec7ca4376461c9e03405af7227c13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":362,
                  "y":14},
                "size":{
                  "width":51,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 测评",
                      "target":{
                        "targetType":"page",
                        "url":"测评.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 ceping = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["bddeda486e2b41089e0abdee647b2b9e"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 ceping = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["bddeda486e2b41089e0abdee647b2b9e"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/ceping_u10.png",
            "selected~":"images/讲课_教师讲义/ceping_u10_selected.png"}},
{
          "id":"649bf044b86c435e92e9ded80c631b6e",
          "label":"peixun",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC66}}},
            "location":{
              "x":423,
              "y":14},
            "size":{
              "width":58,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF99},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc98c8bfeab2482dbf657f9b4275bbaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFCC66}}},
                "location":{
                  "x":423,
                  "y":14},
                "size":{
                  "width":58,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF99},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 培训",
                      "target":{
                        "targetType":"page",
                        "url":"培训.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["649bf044b86c435e92e9ded80c631b6e"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 peixun = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["649bf044b86c435e92e9ded80c631b6e"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/讲课_教师讲义/peixun_u12.png",
            "selected~":"images/讲课_教师讲义/peixun_u12_selected.png"}},
{
          "id":"ae138ba7289b47b7ad5ed637c1733139",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":14},
            "size":{
              "width":90,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4530695726644676841b54e25a0311d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":850,
                  "y":14},
                "size":{
                  "width":90,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 user 弹出效果",
                      "objectsToFades":[{
                          "objectPath":["8e7dcd1d5f7d4e23992a450dc3d62870"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"flyout"}}}]}]}]}},
          "images":{
            "normal~":"images/备课/u16.png"}},
{
          "id":"8e7dcd1d5f7d4e23992a450dc3d62870",
          "label":"user",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":850,
              "y":43},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"11711950c9b84c3baa5567f7021f5e96",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ac91d9e1d61440daa81acc1247b3d869",
                  "label":"",
                  "parentDynamicPanel":"8e7dcd1d5f7d4e23992a450dc3d62870",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFA1A1A1,
                      "opacity":1},
                    "size":{
                      "width":90,
                      "height":27},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF3399}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eac59a6fa73247808b8d95c1309c39fc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8e7dcd1d5f7d4e23992a450dc3d62870",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFA1A1A1,
                          "opacity":1},
                        "size":{
                          "width":90,
                          "height":27},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF3399}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/备课/u53.png"}},
{
                  "id":"cdd535be72944c96a5c21d63da8f769b",
                  "label":"",
                  "parentDynamicPanel":"8e7dcd1d5f7d4e23992a450dc3d62870",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFA1A1A1,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":26},
                    "size":{
                      "width":90,
                      "height":27},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF3399}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a61aa5357e64fb985875a07712f6e56",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8e7dcd1d5f7d4e23992a450dc3d62870",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFA1A1A1,
                          "opacity":1},
                        "location":{
                          "x":0,
                          "y":26},
                        "size":{
                          "width":90,
                          "height":27},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF3399}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/备课/u53.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "35883f4c7eab4147a3da12149411decb":{
      "scriptId":"u0"},
    "7c126df58d4a4335bcaeed20b898b22a":{
      "scriptId":"u1"},
    "1a49ef5b418642299a61734248e2f637":{
      "scriptId":"u2"},
    "8658d4197b8243d3a653704a7f318f1f":{
      "scriptId":"u3"},
    "e1f7fe55c2da442d910e46603c0df30b":{
      "scriptId":"u4"},
    "66c8c02837da4f0690661e6951b5fc95":{
      "scriptId":"u5"},
    "140e8bf515664b05aab8e1ff6b486e69":{
      "scriptId":"u6"},
    "a5295244d15d444d81defd2ec61b9da6":{
      "scriptId":"u7"},
    "d998d84ee23c418180b9fc413b4445d7":{
      "scriptId":"u8"},
    "f3dd49fc9e2e4e299440a46200d5349d":{
      "scriptId":"u9"},
    "1c60d27d6ecf404192a20a79ce5ce75d":{
      "scriptId":"u10"},
    "232df10b052142cdb8e9f05953a38a92":{
      "scriptId":"u11"},
    "c33aa22beef24076a1cb610af4d6ba3b":{
      "scriptId":"u12"},
    "960f469b6674452dbaddd5379998f7cb":{
      "scriptId":"u13"},
    "38a9af47fabc41c4aad97d8fd2555b9d":{
      "scriptId":"u14"},
    "e6168a78f4d84b68ad32c03eee304e15":{
      "scriptId":"u15"},
    "a006d195e03a400585f153d20b2b4968":{
      "scriptId":"u16"},
    "11e6d4f019c14d90b49d54ee373ac4a8":{
      "scriptId":"u17"},
    "6e3b383a64604267a54ddc90cfb1ff96":{
      "scriptId":"u18"},
    "9cc09e5b11994c17a453b4fbf9468024":{
      "scriptId":"u19"},
    "0b1d8beb19524c78bc2042d054b25d21":{
      "scriptId":"u20"},
    "a9732fde5864430fa67d49cc7dd3cd86":{
      "scriptId":"u21"},
    "23409cc61ed44703bea772be7b776e4f":{
      "scriptId":"u22"},
    "bc4cdb049134448d8d68e8e347efcd94":{
      "scriptId":"u23"},
    "13a0f235655044f5aec9399ddd70a773":{
      "scriptId":"u24"},
    "684c7525179d4368a24160876e67afcc":{
      "scriptId":"u25"},
    "af1ab2afd4344391ba229abf57c2c147":{
      "scriptId":"u26"},
    "f98f966e28e149728400bc4b2eb1848e":{
      "scriptId":"u27"},
    "5a30b3e7a1b64652a6a73bf9313be37d":{
      "scriptId":"u28"},
    "d55867c9e13f4088b40f693d0ff1130c":{
      "scriptId":"u29"},
    "c3bf4f97c25d47e6835a5ff7ca63bb0c":{
      "scriptId":"u30"},
    "57cfcca1ddb84b6e8663b4b427088830":{
      "scriptId":"u31"},
    "cd4abee5d9554120bbef1c0d3861d2af":{
      "scriptId":"u32"},
    "cfd40af688464943966b1e4fa7bfed9e":{
      "scriptId":"u33"},
    "08af48c8b5dd42c9842f21516e5ea371":{
      "scriptId":"u34"},
    "903142f07feb427ba4940bc05516f730":{
      "scriptId":"u35"},
    "5994df43b9cb42b0b692c2751aea3ba2":{
      "scriptId":"u36"},
    "bf2696cf6c6849fa868dbd7fd0a4e6d4":{
      "scriptId":"u37"},
    "24398efc0cc846999608c62a2382dfe9":{
      "scriptId":"u38"},
    "a2528b08d22345f2bbc728d86c9f508e":{
      "scriptId":"u39"},
    "53ee409a2fc041868a7933880da7026b":{
      "scriptId":"u40"},
    "63fbf48b87734ac4a006bca5b7010b26":{
      "scriptId":"u41"},
    "bb2a8a38be2d4e22b3841a7e924b4b4b":{
      "scriptId":"u42"},
    "94533cd7f437495eb47d7e3f7d8f66fd":{
      "scriptId":"u43"},
    "55c89fde890c471f82a5d05cf689a104":{
      "scriptId":"u44"},
    "267fb8af3fde4d5984d1fde40db72be6":{
      "scriptId":"u45"},
    "6dc9b5faaf48482cb95a5bc46be7233b":{
      "scriptId":"u46"},
    "4c1258e62a054f0398ad546bd61d32e7":{
      "scriptId":"u47"},
    "93a939e6a3a54587a9cf66ddcc19c954":{
      "scriptId":"u48"},
    "7c3e6ea7613747ce829e63406e038ffd":{
      "scriptId":"u49"},
    "99332b0f4cee4431866566c3fe7ea2a4":{
      "scriptId":"u50"},
    "66823068f2994bb485e4e5ef1a7fa31b":{
      "scriptId":"u51"},
    "b4319fd152e84fac83f4cec0f888e6d5":{
      "scriptId":"u52"},
    "7d0841885b3347f8b51fbe92dc076957":{
      "scriptId":"u53"},
    "e18d8e3735a049619043af4662f0cccf":{
      "scriptId":"u54"},
    "345e5605629c4284a6b5aed46a3de7ce":{
      "scriptId":"u55"},
    "ac1e315c22f64f27ac260e12ce1bc77d":{
      "scriptId":"u56"},
    "a21dde3e0623412b8a602e6f26605e46":{
      "scriptId":"u57"},
    "4bc7d3d292f345d5806e7ce10d0f5858":{
      "scriptId":"u58"},
    "e6be0d0264014400b35ac276d47372d7":{
      "scriptId":"u59"},
    "062974d8f4a64253b63e74be3b2db612":{
      "scriptId":"u60"},
    "3e186fea5f734c89b3f749eacf8996f7":{
      "scriptId":"u61"},
    "f653070f5e7149fdb7fa38a9c81bdec4":{
      "scriptId":"u62"},
    "a6ff5b811c1a4cbf8343de6ecfaea9c3":{
      "scriptId":"u63"},
    "e414e8025b48480bbe10072f96b5a31a":{
      "scriptId":"u64"},
    "7a2995f083924c8eba7efcf418df90a6":{
      "scriptId":"u65"},
    "ad10182a65d24c1f832c94e89d36de13":{
      "scriptId":"u66"},
    "2fed1a9c4a954f71947b758fc92b8d12":{
      "scriptId":"u67"},
    "83a7d956bb46470ca049b6d109b6e9dd":{
      "scriptId":"u68"},
    "bddeda486e2b41089e0abdee647b2b9e":{
      "scriptId":"u69"},
    "782ec7ca4376461c9e03405af7227c13":{
      "scriptId":"u70"},
    "649bf044b86c435e92e9ded80c631b6e":{
      "scriptId":"u71"},
    "cc98c8bfeab2482dbf657f9b4275bbaf":{
      "scriptId":"u72"},
    "ae138ba7289b47b7ad5ed637c1733139":{
      "scriptId":"u73"},
    "4530695726644676841b54e25a0311d5":{
      "scriptId":"u74"},
    "8e7dcd1d5f7d4e23992a450dc3d62870":{
      "scriptId":"u75"},
    "ac91d9e1d61440daa81acc1247b3d869":{
      "scriptId":"u76"},
    "eac59a6fa73247808b8d95c1309c39fc":{
      "scriptId":"u77"},
    "cdd535be72944c96a5c21d63da8f769b":{
      "scriptId":"u78"},
    "6a61aa5357e64fb985875a07712f6e56":{
      "scriptId":"u79"}}});